[NavigationBar] - Added Accessibility Enforcer
material-components/material-components-ios pull request #1109
Opened 2016-12-27 19:04 UTC by ShepJGoogle

Added initial implementation of MDCNavigationBarAccessibilityEnforcer

- Created a enforcer class for MDCNavigationBar
- Implemented config method to update colors on MDCNavigationBar's title and bar button items

Design Doc: https://docs.google.com/a/google.com/document/d/1QHdBcW8pIkmJ796ou_W-wIznLXT_vzcxWwwlqSSN9x8/edit?usp=sharing

2017-01-05 15:22 UTC, willlarche commented
Is this blocked?

2017-01-05 16:18 UTC, ShepJGoogle commented
No I think just waiting on review of the design doc attached and the changes.

2017-02-07 15:59 UTC, ianegordon commented
Does this work with the UIAppearance proxy?  (Is that a concern?)

2017-02-07 16:07 UTC, randallli requested changes

2017-02-07 16:07 UTC, randallli commented on components/NavigationBar/src/MDCNavigationBar.h
> +- (void)enforceFontColorAccessibility:(nonnull MDCNavigationBar *)navBar;
enforceTextColor

2017-02-07 16:07 UTC, randallli commented on components/NavigationBar/src/MDCNavigationBar.h
> +@interface MDCNavigationBarAccessibilityEnforcer : NSObject
MDCNavigationBarTextColorAccessibilityMutator

2017-02-07 16:07 UTC, randallli commented on components/NavigationBar/src/MDCNavigationBar.h
> +- (void)enforceFontColorAccessibility:(nonnull MDCNavigationBar *)navBar;
actually can we just change this to:
- (void)mutate:(nonnull MDCNavigationBar *)navBar;
or
- (void)mutate:(id)navBar;

this way other mutators can have the same api signature.

2017-02-08 21:28 UTC, randallli commented on components/NavigationBar/examples/NavigationBarTypicalUseExample.m
> +  MDCNavigationBarAccessibilityEnforcer *enforcer =
these need to be changed too i think

2017-02-10 19:58 UTC, randallli approved these changes

2017-02-10 20:04 UTC, ShepJGoogle commented
@ianegordon @randallli and I just did some investigation and UIAppearance proxy returns an instancetype of whatever class you call it on. As such, passing this instance as an argument of the mutate: does in fact mutate the proxy.

2017-02-10 20:05 UTC, randallli commented
merge when your ready.

2017-02-10 20:07 UTC, merged