[Typography] Added isLargeForContrastRatio to protocol
material-components/material-components-ios pull request #1232
Opened 2017-03-01 19:47 UTC by randallli

So that we can make the font tell us if it is has large fonts.

MDC wants to treat medium fonts as large when under 18pts.
Other than looking at the font names there is no way to get the weight of a UIFont. Therefore it has to be the responsibility of the fontloader to determine if a font is large.

2017-03-01 21:01 UTC, randallli commented on components/Typography/src/MDCTypography.h
> +@optional
should i make it optional?

2017-03-01 21:43 UTC, randallli commented
@ianegordon points out that we have the weight via mdc_weight

2017-03-01 22:07 UTC, ajsecord requested changes

2017-03-01 22:07 UTC, ajsecord commented on components/Typography/src/MDCTypography.h
> +@optional
Wouldn't all of these actually be optional? Do all fonts have all of these?

2017-03-01 22:38 UTC, randallli commented
i am dropping this in favor of https://github.com/material-foundation/material-text-accessibility-ios/pull/14

2017-03-06 20:44 UTC, randallli commented on components/Typography/src/MDCTypography.h
> +@optional
actually the light, medium, and regular are required. italic and bold are not. I will move the optional to there.

2017-03-07 15:57 UTC, ajsecord requested changes

2017-03-07 15:57 UTC, ajsecord commented on components/Typography/src/MDCTypography.m
> +  if ([font.fontName rangeOfString:@"medium" options:NSCaseInsensitiveSearch].location != NSNotFound) {
This is only for Roboto—omit.

2017-03-07 16:57 UTC, ajsecord commented on components/Typography/src/MDCTypography.m
> +  if ([font.fontName rangeOfString:@"medium" options:NSCaseInsensitiveSearch].location != NSNotFound) {
My bad—I missed that this was in MDCSystemFontLoader. Consider splitting it out.

2017-03-07 16:57 UTC, ajsecord approved these changes

2017-03-07 21:58 UTC, ianegordon approved these changes
Verified weak checking of constants on the 8.1 simulator.
test_all worked as expected.

2017-03-07 21:58 UTC, merged