[Typography] Added strong dependency to MDFTextAccessiblity for fallbackack logic when isLargeForContrastRatios: is unspecified.
material-components/material-components-ios pull request #1250
Opened 2017-03-13 20:35 UTC by randallli

2017-03-13 20:44 UTC, randallli commented
actually i think its better to just make it a non-optional method.
https://github.com/material-components/material-components-ios/pull/1251

2017-03-14 20:32 UTC, ianegordon requested changes

2017-03-14 20:32 UTC, ianegordon commented on components/Typography/src/MDCTypography.m
> ++ (BOOL)isLargeForContrastRatios:(nullable UIFont *)font {
nonnull UIFont to match the font loaders?

Otherwise, shortcircuit return NO if font == nil.

2017-03-14 22:50 UTC, randallli commented on components/Typography/src/MDCTypography.m
> ++ (BOOL)isLargeForContrastRatios:(nullable UIFont *)font {
fixed.
good catch.

2017-03-14 23:04 UTC, ianegordon approved these changes

2017-03-14 23:09 UTC, ianegordon commented
Waiting on TravisCI before Merge.

2017-03-15 01:58 UTC, merged