[CollectionCells] Add accessibility hint in edit mode
material-components/material-components-ios pull request #1258
Opened 2017-03-16 11:57 UTC by Arcank

When editing, selectable/deselectable cells now give an accessibility
hint: "Double tap to select.". This helps users to know what they can do
while in edit mode.

Related: #1257

2017-03-16 15:27 UTC, randallli approved these changes

2017-03-16 15:28 UTC, randallli requested changes

2017-03-16 15:28 UTC, randallli commented on components/CollectionCells/src/MDCCollectionViewCell.m
> +- (NSString *)accessibilityHint {
can we and a unit test?

2017-03-17 18:24 UTC, Arcank commented on components/CollectionCells/src/MDCCollectionViewCell.m
> +- (NSString *)accessibilityHint {
Added tests.

2017-03-20 10:52 UTC, Arcank commented
Kindly ping.

2017-03-20 22:31 UTC, Arcank commented
@randallli: Can you have a look? I added test coverage.

2017-03-21 13:37 UTC, randallli commented
Sorry will look when I get in.
On Mon, Mar 20, 2017 at 6:31 PM Louis Romero <notifications@github.com>
wrote:

> @randallli <https://github.com/randallli>: Can you have a look? I added
> test coverage.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/material-components/material-components-ios/pull/1258#issuecomment-287918612>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AA5lzQPMYu_4jN-pEgYIvsUmRauXc05tks5rnv45gaJpZM4MfMlS>
> .
>

2017-03-21 14:54 UTC, randallli approved these changes

2017-03-21 14:54 UTC, merged