Fix feature highlight on iOS8 devices
material-components/material-components-ios pull request #1281
Opened 2017-03-28 19:35 UTC by samnm

Fixes #1272

Turns out `convertPoint:toView:` changed from iOS8 to iOS9, so we have to use `convertPoint:toCoordinateSpace:` on iOS8.

2017-03-28 22:42 UTC, ianegordon requested changes

2017-03-28 22:42 UTC, ianegordon commented on components/FeatureHighlight/src/MDCFeatureHighlightViewController.m
> +  } else {
Won't all iOS version iOS 8+ will return YES for deviceUsersCoordinateSpaces?
If that is the case, this else clause will never be called.

2017-03-28 23:26 UTC, samnm commented on components/FeatureHighlight/src/MDCFeatureHighlightViewController.m
> +  } else {
Oops, you're right! Fixed.

2017-03-29 17:50 UTC, ianegordon commented
Tested on iPhone 5 Sim 8.1 and 10.3.
LGTM.

2017-03-29 17:51 UTC, ianegordon approved these changes

2017-03-29 17:51 UTC, merged