[Feature highlight] Accessibility fixes
material-components/material-components-ios pull request #1284
Opened 2017-03-28 21:23 UTC by samnm

This change allows the highlightedView to be accessed with voiceover and also adds a 'double tap to dismiss' accessibility hint to the title of the feature highlight.

Closes #782

2017-03-31 20:53 UTC, ianegordon commented
When you dismiss the feature highlight, the original view should still be highlighted.

Repro:
MDCCatalog -> Feature Highlight -> Demo
Navigate to the GO! button
Double tap to invoke the button's action
Double tap to dismiss the feature highlight
The Navigation - Back button is selected instead of the GO! button.

2017-03-31 20:53 UTC, ianegordon requested changes

2017-03-31 20:53 UTC, ianegordon commented on components/FeatureHighlight/src/private/MDCFeatureHighlightView.m
> +NSString *const MDCFeatureHighlightViewTitleA11yHint = @"Double-tap to dismiss.";
Wrap in NSLocalizedString so we can (eventually) pull this out for l10n.

2017-03-31 22:23 UTC, samnm commented
> When you dismiss the feature highlight, the original view should still be highlighted.

Is this the standard? Dialogs doesn't do this, and I'm not sure how you would implement it.

2017-04-04 22:06 UTC, samnm commented on components/FeatureHighlight/src/private/MDCFeatureHighlightView.m
> +NSString *const MDCFeatureHighlightViewTitleA11yHint = @"Double-tap to dismiss.";
Done.

2017-04-05 20:52 UTC, ianegordon requested changes

2017-04-05 20:52 UTC, ianegordon commented on components/FeatureHighlight/src/private/MDCFeatureHighlightView.m
> +    _titleLabel.accessibilityHint = NSLocalizedString(MDCFeatureHighlightViewTitleA11yHint, nil);
This will fail as it will try and load from the mainBundle, see MDCPageControl for an example of how to load from a local .bundle.

2017-04-05 20:53 UTC, ianegordon commented
Lets push on the state after the feature has been rejected.  I'll open an issue to investigate.

2017-04-06 20:09 UTC, samnm commented
Updated to load the accessibility hint from a bundle.

2017-04-07 18:39 UTC, ianegordon commented
Tested on an iPhone 7.
Please rebase before merge.
LGTM.

2017-04-07 18:39 UTC, ianegordon approved these changes

2017-04-07 19:32 UTC, merged