[Tabs] API review: Bottom navigation support
material-components/material-components-ios pull request #1299
Opened 2017-04-04 14:15 UTC by brianjmoore

This API change adds support for bottom navigation bars to MDCTabBar by adding tab bar "configurations" and defining a configuration for bottom navigation bars.

A configuration is a set of properties which determine how the tab bar looks and behaves. Some of these properties may be private (for example, bottom navigation has slightly different internal metrics), which gives the library more implementation flexibility. The default initializers for MDCTabBar still create top tabs.

Usage example:
https://github.com/brianjmoore/material-components-ios/blob/inplace-bottomnav/components/Tabs/examples/BottomNavigationBarExample.m

2017-04-05 14:57 UTC, ajsecord requested changes
Any reason all of this configuration couldn't be replaced with UI_APPEARANCE properties on the views themselves?

2017-04-05 20:25 UTC, ianegordon requested changes

2017-04-05 20:25 UTC, ianegordon commented on components/Tabs/src/MDCTabBar.h
> +@interface MDCTabBarConfiguration : NSObject <NSCopying>
Can we mimic Apple and attach UIBarPositioningDelegate to MDCTabBarDelegate?
Doing so might eliminate the top/bottomConfiguration and allow us to move the remaining properties to MDCTabBar as IBInspectable @properties.

2017-04-13 13:20 UTC, brianjmoore commented on components/Tabs/src/MDCTabBar.h
> +@interface MDCTabBarConfiguration : NSObject <NSCopying>
I really like this idea!

My only concern would be that it makes the default values for affected properties weird. For example, the default alignment for top tabs should be Leading but for bottom tabs should be Justified. Similar deal for the other two properties that are public on the configuration. 

What would [[MDCTabBar alloc] init].alignment return? What if a delegate is set?
A. Specifically Leading or Justified, chosen arbitrarily or based on whatever the delegate returns.
B. A new sentinel alignment case Default that specifies it's whatever is the default value for the context. This approach works for enums and objects, but would require changing BOOL properties into an enum.
C. Explicitly undefined - querying the alignment before setting it is not correct use of the API. Prone to misuse, but clearly simplest to implement.

2017-04-13 13:25 UTC, brianjmoore commented
@ajsecord I had a few reasons for wrapping this all up into the configuration

* To avoid the complexity for the user of having to set a dozen or so properties to fairly specific values to achieve a particular look. For an example of the breadth of properties that would need to be set, see https://github.com/brianjmoore/material-components-ios/blob/inplace-bottomnav/components/Tabs/src/MDCTabBar.m#L371. Ian's UIBarPosition idea would take care of this problem if we can resolve the default values problem.
* Some of the properties we need to achieve the bottom navigation style are pretty darn fiddly. It boils down to essentially what we have on MDCItemBarStyle: https://github.com/material-components/material-components-ios/blob/develop/components/Tabs/src/private/MDCItemBarStyle.h. In particular, I'm not sure we want to support customizing things like the title-image padding, ink color or maximum item width. I suppose they can always be deprecated and become no-ops in the future, though.

2017-04-13 13:30 UTC, brianjmoore commented on components/Tabs/src/MDCTabBar.h
> +@interface MDCTabBarConfiguration : NSObject <NSCopying>
Or I suppose
D: Change all the properties to methods that take a bar position.

2017-04-21 15:49 UTC, ianegordon commented on components/Tabs/src/MDCTabBar.h
> +@interface MDCTabBarConfiguration : NSObject <NSCopying>
We can pick the most common case for the default.  I would guess Top.

Could we add alignment to MDCTabBarPositioning / MDCTabBarPositioningDelegate? (Which would inherit from UIBarPositioning and UIBarPositioningDelegate respectively)

This matches Apple's use of default, toolbars are at the top and tabbars are at the bottom.

2017-04-25 20:28 UTC, brianjmoore commented
Updated proposal to use UIBarPositioning, and also updated draft implementation at:
https://github.com/material-components/material-components-ios/compare/develop...brianjmoore:inplace-bottomnav-v2

Overall this does simplify the API a ton, but has some drawbacks:
* Setting alignment/itemAppearance/displaysUppercaseTitles the first time now has special meaning and effectively imposes an override of the position-based default value.
* sizeThatFits: also now secretly depends on the bar position, and thus the delegate. This imposes a not-entirely-obvious ordering dependency between calling sizeThatFits: and setting the delegate.
* The implementation of MDCTabBar is a bit more complex due to the new behaviors for default properties.

Please take another look.

2017-05-08 21:26 UTC, ianegordon approved these changes

2017-05-08 21:27 UTC, ianegordon commented
With the changes in your second branch, LGTM.

2017-05-31 21:38 UTC, closed without merging