[AppBar] Updated accessibility label on back button
material-components/material-components-ios pull request #1334
Opened 2017-04-20 17:38 UTC by ShepJGoogle

Change accessibility label on AppBar back button

2017-04-20 21:42 UTC, Arcank commented on components/AppBar/src/MDCAppBar.m
> +  backBarButtonItem.accessibilityLabel = NSLocalizedString(@"Back", @"Back");
Won’t you need a strings file in the AppBar component? Otherwise this will never be localized.

2017-04-20 21:51 UTC, ShepJGoogle commented on components/AppBar/src/MDCAppBar.m
> +  backBarButtonItem.accessibilityLabel = NSLocalizedString(@"Back", @"Back");
Yep I only published this as it is a blocker for a project that needed a temporary fix and this was a way for me to display the fix. I've marked it with a "isPlanningChanges" label so nobody merged it or reviewed it.

2017-04-20 23:12 UTC, samnm approved these changes

2017-04-21 15:50 UTC, ianegordon approved these changes

2017-04-21 15:52 UTC, ianegordon reviewed
Travis is missing a AppBarStrings.h file which seems like an actual issue.  Otherwise LGTM.
Can you take a look before submit?

2017-04-21 16:18 UTC, ShepJGoogle commented
@ianegordon Checked in update to pod spec

2017-04-21 16:38 UTC, ianegordon requested changes
Waiting for Travis.

2017-04-21 16:48 UTC, ShepJGoogle commented
@ianegordon The podspec was updated

2017-04-21 16:50 UTC, ianegordon commented
I think that was a stale page issue. disregard.

2017-04-21 16:52 UTC, ianegordon approved these changes

2017-04-21 17:04 UTC, ianegordon commented
Verified on an iPhone 6 - 10.1.1.

2017-04-21 17:04 UTC, merged