[contributing] Recommend static C functions for common initialization
material-components/material-components-ios pull request #1346
Opened 2017-04-29 01:17 UTC by stephanemoore

Recommend static C functions for common initialization instead of private instance methods with collision-resistant names.

2017-05-01 15:17 UTC, randallli approved these changes
LGTM.
I added some others who may have stronger opinions.

originally came up in cl/147566240.

2017-05-01 15:27 UTC, ajsecord approved these changes
👍  Please file a bug to change the current usage in MDC-iOS.

2017-05-01 15:51 UTC, ianegordon commented
I'm in favor of the static scoping of the function, but I'm concerned this might be surprising to clients.
I don't know that I've seen a C function take self as a parameter.
Let me do some digging.

2017-05-01 15:52 UTC, ianegordon requested changes
Looking for best / common practices.

2017-05-01 15:53 UTC, willlarche commented
That was the same concern I had. It's a little avant-garde for something so
mundane.

On Mon, May 1, 2017 at 11:51 AM ianegordon <notifications@github.com> wrote:

> I'm in favor of the static scoping of the function, but I'm concerned this
> might be surprising to clients.
> I don't know that I've seen a C function take self as a parameter.
> Let me do some digging.
>
> —
> You are receiving this because you were assigned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/material-components/material-components-ios/pull/1346#issuecomment-298359670>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABNm5RR2LLmNSMWPHAwFf2KlwSZepCeQks5r1f-agaJpZM4NMGyP>
> .
>

2017-05-02 16:16 UTC, ianegordon commented
Initial thinking is to decline based on preferring Objective-C methods to C functions.
Discussing offline.

2017-05-02 22:30 UTC, stephanemoore commented
Regarding C functions with parameters named self: it's not that uncommon. Essentially all Objective-C methods are functions with two hidden parameters "self" and "_cmd". Naming a C function with a similar structure helps identify the function as an operation on an Objective-C object.

You can see examples of this in Apple open source code and documentation:
https://developer.apple.com/reference/objectivec/1456712-objc_msgsend?language=objc
https://opensource.apple.com/source/objc4/objc4-709/runtime/objc-runtime-new.mm.auto.html

You can also see examples in Google open source code:
https://github.com/google/protobuf/blob/master/objectivec/GPBMessage.m

2017-05-02 22:57 UTC, stephanemoore commented
Regarding the preference for Objective-C methods: are you worried that contributors will find static C functions unfamiliar or alienating?

If you look through the UIKit symbol table you will find many examples indicative of C functions used to consolidate initialization logic. With Xcode 8.3 I ran the following command on UIKit:
```
$ nm /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit -s __TEXT __text | grep -i -e "common.*init"
```
You will observe C function symbols including UIViewCommonInitWithFrame, UILabelCommonInit, and _UISwitchCommonInit. These all seem like clear examples of C functions used to consolidate initialization logic.

An important observation from above is that said command only reveals the common initialization C functions that have external linkage. Any common initialization C functions with internal linkage are more difficult to detect.

2017-05-03 17:55 UTC, ianegordon commented
As you noted, I am concerned contributors would find static C functions unfamiliar or alienating.

self->_titleLabel.text = @"Default Title"; // Seems a bit unfamiliar to have the self->

The symbol table is pretty interesting.

UILabel appears to have both a commonInit method and function:
00000000002aa1d6 t -[UILabel _commonInit]
00000000002aa396 t _UILabelCommonInit

Many classes have _commonInit methods, while others are named with the class, such as [UISegment _commonSegmentInit].

Let me do a bit more digging.

2017-05-05 20:47 UTC, closed without merging

2017-05-05 21:40 UTC, ianegordon commented
To close the loop.  We agreed to move forward with the specifically-named class methods of commonMDCComponentInit.

Many Thanks for the PR and the nm | grep fu.