[Tabs] Bottom navigation support
material-components/material-components-ios pull request #1411
Opened 2017-05-09 20:40 UTC by brianjmoore

This PR adds bottom navigation support to MDCTabBar by extending the UIBarPositioningDelegate protocol. Delegates which implement `positionForBar:` and return UIBarPositionBottom will cause the tab bar to be rendered as a bottom navigation bar.

2017-05-10 13:32 UTC, ianegordon requested changes

2017-05-10 13:32 UTC, ianegordon commented on components/Tabs/src/MDCTabBar.h
>  + (CGFloat)defaultHeightForItemAppearance:(MDCTabBarItemAppearance)appearance;
Can we make this an instance method and use self.barPosition?
I'm a big fan of class methods when we don't need state, but in this case it seems like we need it.

2017-05-10 13:32 UTC, ianegordon commented on components/Tabs/src/MDCTabBar.h
> + selection changes in the tab bar or to change the bar's position-based appearance.
Consider:
or return the bar's position.
(There is only one method in UIBarPositioningDelegate)

2017-05-10 13:32 UTC, ianegordon commented on components/Tabs/src/MDCTabBar.m
> +  // Flags tracking if properties are unset and using default values.
I think we can implement this using UIAppearance proxy.
Can we catch up offline and discuss?

2017-05-22 22:38 UTC, ianegordon requested changes

2017-05-22 22:38 UTC, ianegordon commented on components/Tabs/src/MDCTabBar.m
> +const CGFloat kBottomNavigationBarHeight = 56;
nit: Add static.

2017-05-22 22:38 UTC, ianegordon commented on components/Tabs/src/MDCTabBar.m
> +const CGFloat kBottomNavigationMaximumItemWidth = 168;
nit: Add static.

2017-05-22 22:38 UTC, ianegordon commented on components/Tabs/src/MDCTabBar.m
> +const CGFloat kBottomNavigationTitleImagePadding = 3;
nit: Add static.

2017-05-23 21:18 UTC, ianegordon requested changes
Add IB_Designable to NON-UI_APPEARANCE properties.

2017-05-24 13:05 UTC, brianjmoore commented
Added IBInspectable to displaysUppercaseByDefault. The alignment and item appearance unfortunately are unsupported due to being enums so I opted to leave IBInspectable off to reduce confusion.

2017-05-24 13:05 UTC, brianjmoore commented on components/Tabs/src/MDCTabBar.m
> +const CGFloat kBottomNavigationTitleImagePadding = 3;
Done

2017-05-24 13:05 UTC, brianjmoore commented on components/Tabs/src/MDCTabBar.m
> +const CGFloat kBottomNavigationMaximumItemWidth = 168;
Done

2017-05-24 13:05 UTC, brianjmoore commented on components/Tabs/src/MDCTabBar.m
> +const CGFloat kBottomNavigationBarHeight = 56;
Done

2017-05-24 13:05 UTC, brianjmoore commented on components/Tabs/src/MDCTabBar.m
> +  // Flags tracking if properties are unset and using default values.
Acknowledged. Discussed yesterday and determined that UIAppearance wouldn't be the right solution in this case.

2017-05-24 13:05 UTC, brianjmoore commented on components/Tabs/src/MDCTabBar.h
> + selection changes in the tab bar or to change the bar's position-based appearance.
Done

2017-05-24 13:05 UTC, brianjmoore commented on components/Tabs/src/MDCTabBar.h
>  + (CGFloat)defaultHeightForItemAppearance:(MDCTabBarItemAppearance)appearance;
Made private for now

2017-05-30 21:28 UTC, ianegordon approved these changes
Thank you for your patience!
LGTM.

2017-05-31 15:18 UTC, ianegordon commented
Tested Locally.

2017-05-31 15:19 UTC, merged