DO NOT SUBMIT - Doc Test
material-components/material-components-ios pull request #1417
Opened 2017-05-10 16:45 UTC by ianegordon

Do not merge.

2017-05-10 16:46 UTC, ianegordon commented on docs/donotsubmit.md
> +## Preperation
s/Preperation/Preparation/

2017-05-11 15:32 UTC, jverkoey requested changes

2017-05-11 15:32 UTC, jverkoey commented on docs/donotsubmit.md
> +* Add oil and combine into a roux
What kind of oil?

2017-05-11 15:54 UTC, ianegordon commented on docs/donotsubmit.md
> +## Preperation
Done.

2017-05-11 15:55 UTC, ianegordon commented on docs/donotsubmit.md
> +* Add oil and combine into a roux
Updated ingredient list above.

2017-05-11 15:57 UTC, jverkoey approved these changes

2017-05-12 13:38 UTC, ianegordon commented
Final thoughts:

PROs:
Open
Changes are tracked as commit w/ history
Design Doc could live in the same PR as the API review
Docs would be in markdown from the start

CONs:
Switching to the edit interface hides comments
The 'threading' of comments isn't quite there yet, making discussions difficult.

2017-05-12 13:38 UTC, closed without merging