Initial API proposal for the masked transition component.
material-components/material-components-ios pull request #1448
Opened 2017-05-19 18:16 UTC by jverkoey

This component implements support for masked reveal transitions.

The primary use case for this initial API proposal is for floating action button (FAB) transitions. This use case assumes that the source view is a circle.

This API makes use of the Material Motion Transitioning API, which will be a standalone Objective-C library. The relevant Material Motion APIs are included in the `MDMTransition.h` header. Please note that we are not adding a dependency to Material Motion as a whole - just the Transitioning API. The Transitioning API standardizes the mechanisms by which one configures view controller transitions.

## Example usage

```objc
// Full-screen transition
viewController.transitionController.transition = [[MDCMaskedTransition alloc] initWithSourceView: fabView];
[self presentViewController:viewController animated:true completion:nil];

// Bottom-sheet transition
MDCMaskedTransition *transition = [[MDCMaskedTransition alloc] initWithSourceView: fabView];
transition.calculateFrameOfPresentedView = ^(id<MDMPresentationInfo> info) {
return CGRectMake(0,
                  info.containerView.bounds.size.height - 200,
                  info.containerView.bounds.size.width,
                  200);
};
viewController.transitionController.transition = transition;
[self presentViewController:viewController animated:true completion:nil];
```

2017-05-19 18:28 UTC, ianegordon commented
Do we have a video /URL of a masked transition we can attach to this PR?

2017-05-19 18:30 UTC, jverkoey commented
Working on it :)

2017-05-19 18:36 UTC, jverkoey commented
The design spec videos are available here: https://material.io/guidelines/components/buttons-floating-action-button.html#buttons-floating-action-button-transitions

Videos of a prototype implementation built with Material Motion are included inline:

![masked-centered-sheet](https://cloud.githubusercontent.com/assets/45670/26261620/e238c654-3c9f-11e7-803b-f659da6db709.gif)
![fab-full-screen](https://cloud.githubusercontent.com/assets/45670/26261629/ed1c13f0-3c9f-11e7-9191-9a4b72858ed9.gif)
![fab-left-card](https://cloud.githubusercontent.com/assets/45670/26261640/01fcf208-3ca0-11e7-8c91-3b808058420b.gif)
![fab-right-card](https://cloud.githubusercontent.com/assets/45670/26261744/6167792a-3ca0-11e7-9f40-b7e1a98da69b.gif)
![fab-toolbar](https://cloud.githubusercontent.com/assets/45670/26261746/62dfbe3e-3ca0-11e7-9e9d-defba16499fd.gif)

2017-05-19 19:30 UTC, ajsecord requested changes
I'm a little concerned about depending on MDM in the _API_, but I'm out of time for this review...

2017-05-19 19:30 UTC, ajsecord commented on components/MaskedTransition/src/MDMTransition.h
> +@protocol MDMTransition <NSObject>
What's this protocol for? It doesn't seem to be used.

2017-05-19 19:30 UTC, ajsecord commented on components/MaskedTransition/src/MDMTransition.h
> +typedef CGRect (^MDMCalculateFrameOfPresentedView)(_Nonnull id<MDMPresentationInfo> info);
MDC for both of these?

2017-05-19 19:34 UTC, jverkoey commented on components/MaskedTransition/src/MDMTransition.h
> +@protocol MDMTransition <NSObject>
The intent with this file is to show the minimal Material Motion APIs required to build this transition. In specific details, there will be an Objective-C library called MaterialMotionTransitions with the APIs included in this header. As discussed in the PR text, this library will not be the entirety of Material Motion.

2017-05-19 19:34 UTC, jverkoey commented on components/MaskedTransition/src/MDMTransition.h
> +@protocol MDMTransition <NSObject>
To answer your question directly: this protocol is being used on this line:

```objc
@interface MDCMaskedTransition: NSObject <MDMTransition>
```

2017-05-25 13:54 UTC, ajsecord requested changes

2017-05-25 13:54 UTC, ajsecord commented on components/MaskedTransition/src/MDMTransition.h
> +@protocol MDMTransition <NSObject>
Yep, that's all I needed. Where can I see the API for this transition library (since it's in the public API of this library)?

2017-05-25 14:02 UTC, jverkoey commented on components/MaskedTransition/src/MDMTransition.h
> +@protocol MDMTransition <NSObject>
The library is being reviewed here: https://github.com/material-motion/transitioning-objc/pull/1

2017-05-25 14:21 UTC, ajsecord commented on components/MaskedTransition/src/MDMTransition.h
> +@protocol MDMTransition <NSObject>
Let's land Transitioning and then come back here.

2017-05-25 17:36 UTC, jverkoey commented on components/MaskedTransition/src/MDMTransition.h
> +@protocol MDMTransition <NSObject>
Couple PRs to land and then I'll cut the release:

https://github.com/material-motion/transitioning-objc/pull/4
https://github.com/material-motion/transitioning-objc/pull/5

2017-05-25 18:08 UTC, jverkoey commented on components/MaskedTransition/src/MDMTransition.h
> +typedef CGRect (^MDMCalculateFrameOfPresentedView)(_Nonnull id<MDMPresentationInfo> info);
Removed these APIs.

2017-05-25 19:08 UTC, samnm commented on components/MaskedTransition/src/MDCMaskedTransition.h
> +#import <Transitioning/Transitioning.h>
Is this the correct import?

2017-05-25 19:11 UTC, jverkoey commented on components/MaskedTransition/src/MDCMaskedTransition.h
> +#import <Transitioning/Transitioning.h>
This'll be a pod dependency on the library...so I think this is how it'll be imported? Will eventually verify once the pod's available.

2017-05-25 19:21 UTC, jverkoey commented on components/MaskedTransition/src/MDCMaskedTransition.h
> +#import <Transitioning/Transitioning.h>
Confirmed that this header import is correct.

2017-05-26 20:08 UTC, samnm approved these changes

2017-06-05 15:10 UTC, ajsecord approved these changes

2017-06-13 19:12 UTC, jverkoey commented
#1513 introduces the complete component.

2017-06-13 19:12 UTC, closed without merging