More tests for test_all
material-components/material-components-ios pull request #1464
Opened 2017-05-26 15:37 UTC by randallli

so the release does not get hiccups like this past release.

2017-05-26 15:42 UTC, ianegordon commented
test_all is currently used by Travis CI.
These tests are not compatible with Travis CI.
That said, our CI isn't as solid as it could be.

Are we okay with this?

2017-05-26 15:43 UTC, randallli commented
oh didn't realize that it was run there. I want something for the release cop to run.

2017-05-26 15:48 UTC, ianegordon requested changes
I'm very pro-test but lets discuss in person before we merge.

2017-05-26 18:53 UTC, ianegordon commented
super-nit: Consider avoiding two scripts with the same name. (Chances of me invoking the wrong one or getting the two confused are non-zero) 
test_release, check_release,  or verify_cocoapods perhaps?  

LGTM.

2017-05-26 18:53 UTC, ianegordon approved these changes

2017-05-30 15:27 UTC, ianegordon requested changes

2017-05-30 15:27 UTC, ianegordon commented on contributing/releasing.md
> -    scripts/test_all
We will still need scripts/test_all
Here and below.

2017-05-30 15:27 UTC, ianegordon commented on scripts/release/test_all
> +("$SCRIPTS_DIR"/../test_all)
I would keep these scripts independent.

2017-06-05 15:00 UTC, ajsecord requested changes
I don't think this change is the right one. `scripts/test_all` is supposed to do just that—run all the tests. It should be useable by developers, Travis CI, release cops, whoever. It's not release-specific.

2017-06-05 15:08 UTC, ajsecord requested changes

2017-06-05 15:08 UTC, ajsecord commented on scripts/release/test_all
> +("$SCRIPTS_DIR"/../test_all)
Name this script something descriptive, like `test_cocoapods_release`.

2017-06-05 15:08 UTC, ajsecord commented on scripts/release/test_all
> +echo checking pod push authorization ...
Sentence case for everything.

2017-06-05 15:08 UTC, ajsecord commented on scripts/release/test_all
> +    guess_failure "$log_file"
Is `guess_failure` defined here? How was this tested?

2017-06-05 15:08 UTC, ajsecord commented on scripts/release/test_all
> +echo lint podspec ...
You might want to break this into two scripts: `test_pod_push` and `test_pod_format` or something. If I were making changes to the pod files I could see wanting to lint things even if I wasn't authorized to do a push.

2017-06-20 16:50 UTC, ajsecord commented
Let's drop this PR or push it through.

2017-06-29 15:55 UTC, randallli commented on contributing/releasing.md
> -    scripts/test_all
Done.

2017-06-29 15:55 UTC, randallli commented on scripts/release/test_all
> +echo checking pod push authorization ...
ack. Dropped echo.

2017-06-29 15:55 UTC, randallli commented on scripts/release/test_all
> +("$SCRIPTS_DIR"/../test_all)
ack. Dropped umbrella test.

2017-06-29 15:55 UTC, randallli commented on scripts/release/test_all
> +echo lint podspec ...
Broke up into two as suggested. One ended up just being a subcommand so I put that back into the releaseing.md

2017-06-29 15:55 UTC, randallli commented on scripts/release/test_all
> +    guess_failure "$log_file"
ack. Deleted these lines.

2017-06-29 18:42 UTC, ajsecord requested changes

2017-06-29 18:42 UTC, ajsecord commented on contributing/releasing.md
> +    scripts/release/test_pod_push
Can we move this to some "setup"-type place? Every engineer doing releases should do this, but only once per machine, I believe. Having it here to be read and skipped over every time isn't great. If you can't find a better place, at the top in the "Before you start" section is fine.

2017-06-29 18:42 UTC, ajsecord commented on scripts/test_all
>  readonly DESTINATION="platform=iOS Simulator,name=iPhone 7,OS=10.1"
I think you need to sync, this line changed recently.

2017-06-29 19:28 UTC, randallli commented on contributing/releasing.md
> +    scripts/release/test_pod_push
Done.

2017-06-29 19:28 UTC, randallli commented on scripts/test_all
>  readonly DESTINATION="platform=iOS Simulator,name=iPhone 7,OS=10.1"
Done.

2017-07-12 16:35 UTC, ajsecord commented
This seems to be dead, dropping it.

2017-07-12 16:35 UTC, closed without merging