Add ability to change catalog theme
material-components/material-components-ios pull request #1477
Opened 2017-06-02 16:42 UTC by jgunaratne

Exploration of how to potentially theme catalog.

![simulator screen shot jun 2 2017 12 15 25 pm](https://cloud.githubusercontent.com/assets/760941/26735670/da547dc4-4790-11e7-97e5-1fa4452f7089.png)
![simulator screen shot jun 2 2017 12 15 43 pm](https://cloud.githubusercontent.com/assets/760941/26735669/da47c1ec-4790-11e7-85d4-db5f138328e8.png)

2017-06-05 22:18 UTC, ianegordon requested changes
Works as expected locally, but Travis is throwing up some suspicious errors.  (Not the typical timeout)

I've kicked off Travis again to see how it goes.  If Travis is happy, LGTM.  Otherwise let me take another look tomorrow morning and figure out where things are falling down.

2017-06-08 16:51 UTC, ianegordon commented
We need to address the default color issue with internal clients before we land this PR.

2017-06-08 20:56 UTC, randallli submitted a review, later dismissed

2017-06-08 20:56 UTC, randallli commented on catalog/MDCCatalog.xcodeproj/project.pbxproj
> +		664524B71C6BA62A001ADBF8 /* MDCAppDelegate.swift in Sources */ = {isa = PBXBuildFile; fileRef = 664524B61C6BA62A001ADBF8 /* MDCAppDelegate.swift */; };
revert rename of appdelegate

2017-06-08 20:56 UTC, randallli commented on components/ActivityIndicator/examples/ActivityIndicatorExample.m
> +#import "MDCActivityIndicatorColorThemer.h"
lets not make the examples depend on the themer. (it doesn't look like this is needed anyways)

2017-06-08 20:56 UTC, randallli commented on components/ActivityIndicator/examples/supplemental/ActivityIndicatorExampleSupplemental.h
> +#import "MaterialThemes.h"
delete

2017-06-08 20:56 UTC, randallli commented on components/AppBar/examples/AppBarTypicalUseExample.m
> +#import "MaterialThemes.h"
delete all the imports of materialThemes.

2017-06-08 20:56 UTC, randallli commented on components/Buttons/examples/ButtonsTypicalUse.m
> +#import "MDCButtonColorThemer.h"
delete

2017-06-23 15:31 UTC, ianegordon commented
Unable to repro locally.
Please merge, but keep an eye out for smoke / fire.

2017-06-23 15:31 UTC, ianegordon approved these changes

2017-06-23 15:36 UTC, merged