[NavigationBar] - Update handling of center-aligned titles
material-components/material-components-ios pull request #1479
Opened 2017-06-02 19:45 UTC by ShepJGoogle

Update handling of center-aligned titles to follow Apple’s implementation of shifting title over if leading buttons encroach.

Rule -

If MDCNavigationBarTitleAlignmentCenter:
- If leading button bar's maximum x coordinate is less than centered titleFrame's x origin, no change (title stays center aligned)
- else, use leading title alignment

Apple's UINavigation Bar Alignment Rules:
![screen shot 2017-06-02 at 3 32 25 pm](https://cloud.githubusercontent.com/assets/19916772/26742097/42ca9f0a-47aa-11e7-8dae-d5f9bf09795b.png)

![screen shot 2017-06-02 at 3 32 57 pm](https://cloud.githubusercontent.com/assets/19916772/26742102/49ff6fc6-47aa-11e7-83a8-f5206f2e433a.png)

![screen shot 2017-06-02 at 3 33 21 pm](https://cloud.githubusercontent.com/assets/19916772/26742107/5000a28c-47aa-11e7-98cc-545fce38ec18.png)

![screen shot 2017-06-02 at 3 33 42 pm](https://cloud.githubusercontent.com/assets/19916772/26742111/544e2a62-47aa-11e7-9d32-4bfa9244901e.png)

After Change:
![screen shot 2017-06-02 at 3 27 31 pm](https://cloud.githubusercontent.com/assets/19916772/26742128/65256c10-47aa-11e7-9fdd-d7841de4db6d.png)

![screen shot 2017-06-02 at 3 28 01 pm](https://cloud.githubusercontent.com/assets/19916772/26742130/6adc741e-47aa-11e7-8ad3-b9270553560c.png)

![screen shot 2017-06-02 at 3 28 23 pm](https://cloud.githubusercontent.com/assets/19916772/26742142/751c9058-47aa-11e7-93aa-4c88c53593d0.png)

![screen shot 2017-06-02 at 3 29 06 pm](https://cloud.githubusercontent.com/assets/19916772/26742147/7b0f23d6-47aa-11e7-903c-ba2e4265d93e.png)

2017-06-05 15:03 UTC, ajsecord requested changes

2017-06-05 15:03 UTC, ajsecord commented on components/NavigationBar/src/MDCNavigationBar.m
> +    }
Are you deliberately falling through to the next case here? Intentional falling through [needs a comment](https://engdoc.corp.google.com/eng/doc/objcguide.xml?external=y&showone=Conditionals#Conditionals).

2017-06-05 15:32 UTC, ShepJGoogle commented on components/NavigationBar/src/MDCNavigationBar.m
> +    }
Done

2017-06-05 15:37 UTC, ajsecord requested changes

2017-06-05 15:37 UTC, ajsecord commented on components/NavigationBar/src/MDCNavigationBar.m
> +    case MDCNavigationBarTitleAlignmentCenter: {
Add comment like "Align title to the center, except if X, Y, or Z." This isn't clear enough to just parse.

2017-06-05 16:38 UTC, ShepJGoogle commented on components/NavigationBar/src/MDCNavigationBar.m
> +    case MDCNavigationBarTitleAlignmentCenter: {
Done

2017-06-05 19:54 UTC, ianegordon requested changes

2017-06-05 19:54 UTC, ianegordon commented on components/NavigationBar/src/MDCNavigationBar.m
> +      CGFloat xOrigin = CGRectGetMaxX(self.bounds) / 2 - frame.size.width / 2;
Avoid frame.size or frame.origin unless you are positive the frame has been standardized.  (And in that case, document that it is).
s/frame.size.width/CGRectGetWidth(frame)/
(for height as well)

2017-06-05 19:54 UTC, ianegordon commented
Strange that clang didn't through a warning on the switch fallthrough :/

2017-06-05 20:46 UTC, ajsecord approved these changes

2017-06-05 22:13 UTC, ianegordon commented
rect.origin -> CGRectGetMin()

Consider simplifying the next line to just return frame.

2017-06-06 21:26 UTC, ajsecord approved these changes

2017-06-06 21:30 UTC, merged