[Feature Highlight] Expose title and body color properties
material-components/material-components-ios pull request #1496
Opened 2017-06-08 20:43 UTC by samnm

This PR exposes the title and body color to be user configurable.

In order to make this not introduce changes for current clients of Feature Highlight, if the properties are not set when the Feature Highlight is presented the title and body colors will be automatically chosen as before, using MDFTextAccessibility.

2017-06-09 18:38 UTC, jgunaratne approved these changes

2017-06-09 18:38 UTC, jgunaratne commented on components/FeatureHighlight/src/MDCFeatureHighlightViewController.m
> +      options |= MDFTextAccessibilityOptionsLargeFont;
Are we eventually moving the a11y color contrast checks into an a11y mutator?

2017-06-09 18:39 UTC, samnm commented on components/FeatureHighlight/src/MDCFeatureHighlightViewController.m
> +      options |= MDFTextAccessibilityOptionsLargeFont;
Ideally but that will require a deprecation.

2017-06-12 14:46 UTC, ianegordon requested changes

2017-06-12 14:46 UTC, ianegordon commented on components/FeatureHighlight/src/MDCFeatureHighlightView.h
> +@property(nonatomic, strong) UIColor *titleColor UI_APPEARANCE_SELECTOR;
Add nullability notations.

2017-06-12 18:24 UTC, ianegordon approved these changes

2017-06-12 19:06 UTC, ianegordon commented
TravisCI seems to be struggling with this PR.
Testing locally.

2017-06-12 21:11 UTC, ianegordon commented
Unit tests work as expected.
Integration fail for an unrelated reason.

2017-06-12 21:11 UTC, merged