[Feature Highlight] Rotation fixes and animation improvement
material-components/material-components-ios pull request #1505
Opened 2017-06-09 20:44 UTC by samnm

This PR replaces the mechanism for how feature highlights were reoriented upon rotation. Instead of using KVO on the frame of the highlighted view we now update on size class transition.

This change also makes the rotation animation look correct throughout the entire rotation.

2017-06-12 21:47 UTC, ianegordon approved these changes
Please address comment before submit.

2017-06-12 21:47 UTC, ianegordon commented on components/FeatureHighlight/src/private/MDCFeatureHighlightView+Private.m
> +//  [self layoutIfNeeded];
Remove?

2017-06-12 21:51 UTC, ianegordon requested changes
There appear to be some issues with rotation of the main sample in catalog.

2017-06-19 19:51 UTC, randallli approved these changes

2017-06-19 21:53 UTC, ianegordon approved these changes
Rotation now works as expected.

2017-06-19 21:53 UTC, merged