[CollectionCells] Move ink view behind cell contents
material-components/material-components-ios pull request #1564
Opened 2017-06-23 19:52 UTC by romoore

Move the ink view to be above the background views but below the
contents so that it doesn't hide the cell contents when ink is present.

Closes #1560

2017-06-23 20:17 UTC, ajsecord approved these changes

2017-06-23 21:19 UTC, ianegordon requested changes
Do we want to be the bottom view in the contentView hierarchy?
[self.contentView addSubview:_inkView];
[self.contentVIew sendSubviewToBack:_inkView];

Alternatively,
What happens if self.backgroundView is nil?
If self.selectedBackgroundView, don't we want to be just in front of that?

2017-06-26 14:24 UTC, romoore commented
What about placing the InkView just behind the contentView? That allows the selectedBackgroundView and backgroundView to be behind the ink, but lets the content remain visible during ink effects.

2017-06-26 16:34 UTC, ianegordon commented
contentView is nonnull, so no need to check for existence.
It is also readonly so we *should* be decently safe.

2017-06-26 18:19 UTC, ianegordon commented
Discussed offline.
Consider adding Ink as the lowest view in contentView.
@jgunaratne may have insight.

2017-06-27 21:59 UTC, ianegordon commented
@romoore - we had discussed some possible options for where to add the ink layer.  Let me know when you've made your choice and we'll merge.

2017-06-29 14:53 UTC, romoore commented
Not merging this, ink will remain above other layers.  

Related: #1584.

2017-06-29 14:53 UTC, closed without merging