[Buttons] Elevation clean up
material-components/material-components-ios pull request #1574
Opened 2017-06-26 22:57 UTC by samnm

This PR pulls in the elevation-related changes from #1555.

Changes:
* Removes [MDCButton resetElevationForState]
* Moves MDCButton (and subclasses) elevation initialization to UIAppearance calls in +initialize
* Changes elevation assignment from touchesBegan/Moved/Ended to state observation
* Removes defaultElevationForState from MDCButton+Subclassing.h
* MDCFlatButton no longer depends on shouldRaiseOnTouch

2017-06-26 23:22 UTC, samnm commented
I will add some tests to this before merging.

2017-06-27 15:52 UTC, randallli approved these changes
lets pull in some of those tests.

2017-06-27 15:52 UTC, randallli commented on components/Buttons/src/MDCButton.m
>  - (CGFloat)elevationForState:(UIControlState)state {
There were some tests checking elevation was getting set. can we bring those into this PR?

2017-06-27 15:52 UTC, randallli commented on components/Buttons/src/MDCButton.m
> -    [self animateButtonToHeightForState:UIControlStateNormal];
does this need to be called to initialize the button to the correct starting height? or will the proxying do it.

2017-06-27 19:07 UTC, samnm commented on components/Buttons/src/MDCButton.m
>  - (CGFloat)elevationForState:(UIControlState)state {
Done.

2017-06-27 19:30 UTC, samnm commented on components/Buttons/src/MDCButton.m
> -    [self animateButtonToHeightForState:UIControlStateNormal];
We call shadowLayer.elevation = [self elevationForState:self.state]; in the commonInit which correctly configures the shadow layer.

2017-06-27 20:33 UTC, randallli requested changes

2017-06-27 20:33 UTC, randallli commented on components/Buttons/tests/unit/ButtonsTests.m
> +  if (UIControlStateNormal) {
lets copy the function from the mutator tests:
https://github.com/material-components/material-components-ios/blob/develop/components/Buttons/tests/unit/ButtonTitleColorAccessibilityMutatorTests.m#L116

2017-06-27 20:33 UTC, randallli commented on components/Buttons/src/MDCFlatButton.m
> ++ (void)initialize {
lets move the logic into the common init.

If we need to override the setters in the subclass as you showed me in your experiment lets do that too.

we should also confirm the default values with a unit test.

2017-06-29 14:58 UTC, randallli approved these changes

2017-06-29 14:58 UTC, randallli commented on components/Buttons/src/MDCFlatButton.m
> ++ (void)initialize {
I think this is ok now.
We have now done an experiment with calling super setters and that seems to clobber appearance set values.

2017-06-29 19:01 UTC, randallli commented
We need to make sure that our clients know that they need to set the highlighted state for "pressed" state colors.

2017-07-05 18:33 UTC, merged