[NavigationBar] Update MDCNavigationBar titleVerticalAlignment to Center
material-components/material-components-ios pull request #1576
Opened 2017-06-27 08:14 UTC by thkeen

Since MDCNavigationBar is now using the iOS back button style, it doesn't look right to top align the title label. Update this -layoutSubviews implementation to use UIControlContentVerticalAlignmentCenter instead.

### Thanks for starting a pull request on Material Components!

#### Don't forget:
- [ ] Identify the component the PR relates to in brackets in the title. ```[Buttons] Updated documentation```
- [ ] Link to GitHub issues it solves. ```closes #1234```
- [ ] Sign the CLA bot. You can do this once the pull request is submitted.

[Contributing](./contributing/README.md#pull-requests) has more information and tips for a great
pull request.

2017-06-27 13:12 UTC, ianegordon commented
Need to verify with design.
Need to verify behavior with flexible header views.

2017-06-27 14:27 UTC, ajsecord commented
Thanks for the PR! What happens when you have a flexible header that is (much) taller than a single line of text? I think that's one of the issues.

2017-06-27 16:06 UTC, thkeen commented
Got it. I'll update the PR so it aligns vertically centered with the back button and still sticks to the top if the the flexible header is larger than 56.

2017-07-03 09:05 UTC, thkeen commented
I've updated the changes accordingly.

2017-07-04 03:09 UTC, thkeen commented
CI complains "Unable to compare commits because the base of the compare did not upload a coverage report."

Can anyone guide how to generate a coverage report? Thanks.

2017-07-11 09:40 UTC, thkeen commented
Ping?

2017-07-12 17:44 UTC, ianegordon commented
Hi @thkeen.  I'm looking at this now.  I've kicked off a new Travis Build which will hopefully get us a coverage report.

2017-07-12 18:15 UTC, ianegordon requested changes
LGTM, just please add a comment clarifying what we are doing.

2017-07-12 18:15 UTC, ianegordon commented on components/NavigationBar/src/MDCNavigationBar.m
> +      navigationBarCenteredY = MAX(0, navigationBarCenteredY);
This seems surprising.  Why am I using centerY is I'm AlignmentTop.  Can you add a comment to clarify?  Something along the lines:
The title frame is vertically centered with the back button but will stick to the top of the header regardless of the header's height.

2017-07-13 00:05 UTC, thkeen reviewed
I've added the comments.

2017-07-13 00:05 UTC, thkeen commented on components/NavigationBar/src/MDCNavigationBar.m
> +      navigationBarCenteredY = MAX(0, navigationBarCenteredY);
Done.

2017-07-13 13:57 UTC, ianegordon approved these changes

2017-07-13 13:58 UTC, ianegordon commented
The code coverage issue is unrelated to the PR.
Thank you @thkeen !

2017-07-13 13:58 UTC, merged