Clean up code using GNU extensions
material-components/material-components-ios pull request #1601
Opened 2017-07-06 17:00 UTC by romoore

Make the code base more portable by replacing some GNU extension code
(macros, syntactic sugar) with C99-compatible versions.

* Create new `CGFloat`-based `MIN`/`MAX` functions in *MDCMath.h*
* Remove all other use of `MIN`/`MAX` for non-`CGFloat` operands
* Replace shortcut `?:` operator with explicit middle (*true*) terms
* Remove pointer inequality checks in conditionals
* (Cleanup) Change to `#include` for `<tgmath.h>` based on style guide

Closes #846

2017-07-06 17:30 UTC, ianegordon requested changes
MIN and MAX are defined in NSObjCRuntime.h which is in Foundation.
I'm not sure we should be re-implementing it.
Let's discuss offline.

2017-07-06 17:30 UTC, ianegordon commented on components/FlexibleHeader/src/MDCFlexibleHeaderView.m
> +      shadowIntensity = MDCFMax(0,
If you add a linebreak after shadowIntensity will everything fit on the next line?

2017-07-06 17:30 UTC, ianegordon commented on components/PageControl/src/MDCPageControl.m
> +static inline NSInteger snapToRange(NSInteger min, NSInteger max, NSInteger value) {
Functions are typically capitalized.
For minimal surprise, consider naming Clamp(value, min, max) to match other implementations.

2017-07-06 17:30 UTC, ianegordon commented on components/TextFields/src/MDCTextInputControllerFullWidth.m
> +    if (self.textInput.text) {
Was this originally intended to be:
if (self.textInput.text.length > 0)

2017-07-06 18:29 UTC, romoore commented on components/FlexibleHeader/src/MDCFlexibleHeaderView.m
> +      shadowIntensity = MDCFMax(0,
Yep, will change.

2017-07-06 18:30 UTC, romoore commented on components/PageControl/src/MDCPageControl.m
> +static inline NSInteger snapToRange(NSInteger min, NSInteger max, NSInteger value) {
Done.

2017-07-06 19:34 UTC, ianegordon commented
Discussed offline.
TODO: Investigate if it is simple to enable the extension warning on our code without tripping up on the system code.
Move back to MIN / MAX.

2017-07-06 22:11 UTC, ianegordon requested changes
I find ternary operators split across lines very hard to parse.  Can we discuss this offline?

2017-07-06 22:11 UTC, ianegordon commented on components/TextFields/src/MDCTextField.m
> +                     ? fundament : [[MDCTextInputCommonFundament alloc] initWithTextInput:self];
Consider a linebreak after the "lvar =" to keep the ternary expression on a single line.

2017-07-06 22:11 UTC, ianegordon commented on components/TextFields/src/MDCTextField.m
> +              MDCCeil(self.trailingUnderlineLabel.font.lineHeight * 2.f) / 2.f);
Not sure about this indenting.  +4 spaces after continuing a line.  This looks like +8.

2017-07-06 22:11 UTC, ianegordon commented on components/ButtonBar/src/private/MDCAppBarButtonBarBuilder.m
> +  UIView *customView = buttonItem.mdc_customView ? buttonItem.mdc_customView : buttonItem.customView;
101 characters :/
Linebreak after "customView ="

2017-07-06 22:11 UTC, ianegordon commented on components/Slider/src/MDCSlider.m
> +  _thumbTrack.trackOffColor = trackBackgroundColor ? trackBackgroundColor : [[self class] defaultTrackOffColor];
Linebreak after ".trackOffColor =".

2017-07-06 22:11 UTC, ianegordon commented on components/TextFields/src/MDCTextInputControllerDefault.m
> +            ? self.previousPlaceholderColor : self.inlinePlaceholderColor;
I'm beginning to question the utility of the ternary operator without an implicit second argument.  Once you end up on multiple lines it gets hard to parse.

Consider:
if (self.previousPlaceholderColor) {
  self.textInput.placeholderLabel.textColor = self.previousPlaceholderColor;
} else {
  self.textInput.placeholderLabel.textColor = self.inlinePlaceholderColor;
}

2017-07-06 22:11 UTC, ianegordon commented on components/TextFields/src/MDCTextInputControllerDefault.m
> +    if (self.textInput.text) {
Was the original intention (self.textInput.text.length > 0) ?

2017-07-07 13:30 UTC, romoore commented on components/TextFields/src/MDCTextField.m
> +                     ? fundament : [[MDCTextInputCommonFundament alloc] initWithTextInput:self];
Done

2017-07-07 13:30 UTC, romoore commented on components/TextFields/src/MDCTextField.m
> +              MDCCeil(self.trailingUnderlineLabel.font.lineHeight * 2.f) / 2.f);
Done

2017-07-07 13:49 UTC, romoore commented on components/TextFields/src/MDCTextInputControllerDefault.m
> +            ? self.previousPlaceholderColor : self.inlinePlaceholderColor;
Done

2017-07-07 13:49 UTC, romoore commented on components/Slider/src/MDCSlider.m
> +  _thumbTrack.trackOffColor = trackBackgroundColor ? trackBackgroundColor : [[self class] defaultTrackOffColor];
Done

2017-07-07 13:49 UTC, romoore commented on components/ButtonBar/src/private/MDCAppBarButtonBarBuilder.m
> +  UIView *customView = buttonItem.mdc_customView ? buttonItem.mdc_customView : buttonItem.customView;
Done

2017-07-07 14:06 UTC, willlarche commented on components/TextFields/src/MDCTextInputControllerDefault.m
> +    if (self.textInput.text) {
Typo. Should be .length

2017-07-07 14:53 UTC, willlarche commented on components/TextFields/src/MDCTextInputControllerFullWidth.m
> +    if (self.textInput.text) {
yesy

2017-07-07 14:56 UTC, willlarche approved these changes

2017-07-11 21:39 UTC, ianegordon approved these changes

2017-07-11 21:39 UTC, merged