[Tabs] Restore initial tab selection behavior
material-components/material-components-ios pull request #1605
Opened 2017-07-06 21:14 UTC by brianjmoore

Recent changes to the tab bar unintentionally changed the initial selection behavior of MDCTabBar such that creating a tab bar and setting its items array no longer automatically selected the first item. This broke all of our examples and made the API more onerous to use for the 99% case.

This change preserves the ability to set an empty selection while fixing the common case and keeping the API simple. To help solidify this behavior it adds some unit tests and new capabilities to the example.

2017-07-06 22:48 UTC, ianegordon requested changes
Perhaps I'm missing some requirement, but can we simplify _lastSelectedIndexPath to an NSInteger and use NSNotFound to indicate an unselected state?
(As we broke our initial selection behavior, I'm looking for ways to simplify.  It may be out of scope for this change)

2017-07-06 22:48 UTC, ianegordon commented on components/Tabs/src/private/MDCItemBar.m
> +    UITabBarItem *newSelectedItem = nil;
nit: nil is redundant.

2017-07-06 22:48 UTC, ianegordon commented on components/Tabs/src/private/MDCItemBar.m
> +    if (_selectedItem) {
I think these nested ifs could be simplified to:
if (_selectedItem && [_items containsObject:_selectedItem]) {
  newSelectedItem = _selectedItem;
} else {
  newSelectedItem = _items.firstObject;
}

2017-07-06 22:48 UTC, ianegordon commented on components/Tabs/src/private/MDCItemBar.m
> +                   animated:NO];
Do you want animated:animated instead of animated:NO?

2017-07-06 22:48 UTC, ianegordon commented on components/Tabs/src/private/MDCItemBar.m
> +  NSIndexPath *selectedItemIndexPath = nil;
nit: nil is redundant.

2017-07-07 13:33 UTC, brianjmoore commented on components/Tabs/src/private/MDCItemBar.m
> +                   animated:NO];
Yep, good catch

2017-07-07 13:36 UTC, brianjmoore commented on components/Tabs/src/private/MDCItemBar.m
> +    UITabBarItem *newSelectedItem = nil;
It is redundant under ARC, but I would argue that being explicit with default values improves readability by removing a mental step for readers. Regardless, there was a better way to write this that avoids the issue.

2017-07-07 13:36 UTC, brianjmoore commented on components/Tabs/src/private/MDCItemBar.m
> +    if (_selectedItem) {
Done, even simpler too

2017-07-07 13:36 UTC, brianjmoore commented on components/Tabs/src/private/MDCItemBar.m
> +  NSIndexPath *selectedItemIndexPath = nil;
Removed

2017-07-07 13:38 UTC, brianjmoore commented
PTAL. I removed _lastSelectedIndexPath entirely so _selectedItem is now the sole source of truth. That variable was there from a much older implementation where we didn't have an explicit array of items to work with or concrete objects representing each tab. Good call on rethinking it.

2017-07-07 15:50 UTC, ianegordon approved these changes
LGTM.

2017-07-07 15:50 UTC, merged