[TextField] Update demo alert title to be variable.
material-components/material-components-ios pull request #1612
Opened 2017-07-10 06:10 UTC by DonnaLea

Update demo alert title to display based on whether the text fields are floating or not.

Closes #1611

2017-07-10 13:46 UTC, willlarche commented
Thanks @DonnaLea for contributing! What was intended here was to explain what you are toggling which is "Whether floating is enabled" but it seems like that wasn't clear. Could you make this that the title is "Floating Labels" and there is a ✓ next to the one that is currently selected?

2017-07-10 13:50 UTC, willlarche requested changes
What was intended here was to explain what you are toggling which is "Whether floating is enabled" but it seems like that wasn't clear. Could you make this that the title is "Floating Labels" and there is a ✓ next to the one that is currently selected?

2017-07-10 15:49 UTC, DonnaLea commented
Yep, that makes more sense! And yes, the problem was that it wasn't clear what the current state that was being represented was. Thanks for the suggestion, update coming.

2017-07-10 16:02 UTC, willlarche commented
Thank you!!

On Mon, Jul 10, 2017 at 11:49 AM Donna McCulloch <notifications@github.com>
wrote:

> Yep, that makes more sense! And yes, the problem was that it wasn't clear
> what the current state that was being represented was. Thanks for the
> suggestion, update coming.
>
> —
> You are receiving this because your review was requested.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/material-components/material-components-ios/pull/1612#issuecomment-314148441>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABNm5S97Mkeos9teM-CUhhQcE2QIvOM0ks5sMkgJgaJpZM4OSZRy>
> .
>

2017-07-10 16:58 UTC, DonnaLea commented
Updated with an amended commit. Ready for review. (can't see how to re-assign back)

2017-07-10 17:16 UTC, willlarche requested changes
Little change to title and it's ready.

2017-07-10 17:16 UTC, willlarche commented on components/TextFields/examples/TextFieldExample.swift
>      let alert = UIAlertController(title: "Floating Enabled",
Let's make the title "Enable Placeholder Floating" and I'd say it's done!

2017-07-10 17:16 UTC, willlarche commented on components/TextFields/examples/TextFieldExample.swift
>      let alert = UIAlertController(title: "Floating Enabled",
Or "Floating Labels". Whichever you think is clearer.

2017-07-10 17:18 UTC, willlarche approved these changes

2017-07-10 17:19 UTC, DonnaLea commented
My bad, that got lost in my edits. Fixed!

2017-07-10 17:19 UTC, willlarche commented
Awaiting Travis CI, approval (which is a formality. There is no work in the framework.)

2017-07-11 13:56 UTC, willlarche commented
Between when this was started and today, conflicts emerged. Correct them at your convenience and we'll try submitting again.

2017-07-12 14:22 UTC, ajsecord commented
Will, GitHub claims this is ok to merge. Merge now?

2017-07-12 14:35 UTC, merged