[TextFields] Appearance defaults
material-components/material-components-ios pull request #1620
Opened 2017-07-10 23:39 UTC by willlarche

UIAppearance can't work on classes that inherit from something other than UIView. Class properties can be used to replace a lot of that functionality.

2017-07-11 20:04 UTC, jgunaratne requested changes
Minor issues with spacing/wrapping.

2017-07-11 20:04 UTC, jgunaratne commented on components/TextFields/src/MDCTextInputControllerDefault.m
>                              ? (CGFloat)self.floatingPlaceholderScale.floatValue
This spacing/alignment seems a bit odd. Shouldn't it be 4 spaces in from the prior line with CGFloat? Also below.

2017-07-11 20:04 UTC, jgunaratne commented on components/TextFields/src/MDCTextInputControllerDefault.m
> +                                   : [[self class] floatingPlaceholderColorDefault];
Spacing issue?

2017-07-11 20:04 UTC, jgunaratne commented on components/TextFields/src/MDCTextInputControllerDefault.m
> +                                         ? floatingPlaceholderColorDefault
Spacing

2017-07-11 20:04 UTC, jgunaratne commented on components/TextFields/src/MDCTextInputControllerDefault.m
> +  return _inlinePlaceholderColor ? _inlinePlaceholderColor
Spacing

2017-07-11 20:04 UTC, jgunaratne commented on components/TextFields/src/MDCTextInputControllerDefault.m
> +                                       ? inlinePlaceholderColorDefault
Spacing

2017-07-11 20:04 UTC, jgunaratne commented on components/TextFields/src/MDCTextInputControllerDefault.m
> +                                     ? underlineColorActiveDefault
Spacing

2017-07-11 20:04 UTC, jgunaratne commented on components/TextFields/src/MDCTextInputControllerDefault.m
> +                                     ? underlineColorNormalDefault
Spacing

2017-07-11 20:04 UTC, jgunaratne commented on components/TextFields/src/MDCTextInputControllerDefault.m
> +        (BOOL)mdc_adjustsFontForContentSizeCategoryDefault {
Spacing

2017-07-11 20:04 UTC, jgunaratne commented on components/TextFields/src/MDCTextInputControllerFullWidth.m
>  @property(nonatomic, copy, readwrite) NSString *errorText;
Properties should be alphabetized by class name, then variable name.

2017-07-11 20:04 UTC, jgunaratne commented on components/TextFields/src/MDCTextInputControllerFullWidth.m
> +                                 : [[self class] inlinePlaceholderColorDefault];
Spacing

2017-07-11 20:04 UTC, jgunaratne commented on components/TextFields/src/MDCTextInputControllerFullWidth.m
> +                                       ? inlinePlaceholderColorDefault
Spacing

2017-07-11 20:04 UTC, jgunaratne commented on components/TextFields/src/MDCTextInputControllerFullWidth.m
> +        (BOOL)mdc_adjustsFontForContentSizeCategoryDefault {
Spacing

2017-07-11 20:04 UTC, jgunaratne commented on components/TextFields/tests/unit/TextFieldControllerClassPropertiesTests.swift
> +    XCTAssertEqual(controller.mdc_adjustsFontForContentSizeCategory, MDCTextInputControllerDefault.mdc_adjustsFontForContentSizeCategoryDefault)
Fix spacing/wrap

2017-07-11 20:04 UTC, jgunaratne commented on components/TextFields/tests/unit/TextFieldControllerClassPropertiesTests.swift
> +    XCTAssertEqual(controller.mdc_adjustsFontForContentSizeCategory, MDCTextInputControllerDefault.mdc_adjustsFontForContentSizeCategoryDefault)
Fix spacing/wrap

2017-07-11 20:04 UTC, jgunaratne commented on components/TextFields/tests/unit/TextFieldControllerClassPropertiesTests.swift
> +    XCTAssertEqual(controller.mdc_adjustsFontForContentSizeCategory, MDCTextInputControllerFullWidth.mdc_adjustsFontForContentSizeCategoryDefault)
Fix spacing/wrap

2017-07-11 20:04 UTC, jgunaratne commented on components/TextFields/tests/unit/TextFieldControllerClassPropertiesTests.swift
> +    XCTAssertEqual(controller.mdc_adjustsFontForContentSizeCategory, MDCTextInputControllerFullWidth.mdc_adjustsFontForContentSizeCategoryDefault)
Fix spacing/wrap

2017-07-11 20:04 UTC, jgunaratne commented on components/TextFields/src/MDCTextInputControllerDefault.m
> +static UIColor *_errorColorDefault;
Sort by class, then var name

2017-07-11 20:04 UTC, jgunaratne commented on components/TextFields/src/MDCTextInputControllerDefault.m
>            ? self.errorColor
Spacing

2017-07-12 13:16 UTC, jgunaratne approved these changes
Discussed offline with team. Formatting is ok.

2017-07-12 14:18 UTC, willlarche commented
All swift formatting notes done.

2017-07-12 14:30 UTC, willlarche commented
Properties alphabetized by class.

2017-07-12 15:08 UTC, ajsecord requested changes
Please make sure all the properties with defaults follow what I've suggested for `errorColor`.

2017-07-12 15:08 UTC, ajsecord commented on components/TextFields/src/MDCTextInputControllerDefault.m
> +MDCTextInputDefaultFloatingPlaceholderScaleDefault;
+4

2017-07-12 15:08 UTC, ajsecord commented on components/TextFields/src/MDCTextInputController.h
> +@property(nonatomic, nullable, strong) UIColor *errorColor;
null_resettable

2017-07-12 15:08 UTC, ajsecord commented on components/TextFields/src/MDCTextInputController.h
>   Default is red.
"Default is `errorColorDefault`."

2017-07-12 15:08 UTC, ajsecord commented on components/TextFields/src/MDCTextInputController.h
> +@property(class, nonatomic, null_resettable, strong) UIColor *errorColorDefault;
"Default value for `errorColor`.

Default is red."

Omit discussion of implementation (class property) or side discussions (UIAppearance).

2017-07-12 15:45 UTC, willlarche commented on components/TextFields/src/MDCTextInputControllerDefault.m
> +MDCTextInputDefaultFloatingPlaceholderScaleDefault;
Done

2017-07-12 15:45 UTC, willlarche commented on components/TextFields/src/MDCTextInputController.h
>   Default is red.
Done.

2017-07-12 15:45 UTC, willlarche commented on components/TextFields/src/MDCTextInputController.h
> +@property(nonatomic, nullable, strong) UIColor *errorColor;
Done.

2017-07-12 15:46 UTC, willlarche commented on components/TextFields/src/MDCTextInputController.h
> +@property(class, nonatomic, null_resettable, strong) UIColor *errorColorDefault;
Done.

2017-07-12 16:02 UTC, ajsecord requested changes
:)

2017-07-12 16:02 UTC, ajsecord commented on components/TextFields/src/MDCTextInputController.h
> + Default is primary color or blue.
https://giphy.com/gifs/name-trivia-potup-vg1ewVKZkCwFy

It's just blue.

2017-07-12 16:02 UTC, ajsecord commented on components/TextFields/src/MDCTextInputController.h
> + Default is same as inlinePlaceholderColorDefault.
Maybe just state the default without making the reader jump around to find the inlinePlaceholder one?

2017-07-12 16:02 UTC, ajsecord commented on components/TextFields/src/MDCTextInputControllerDefault.h
>  @property(nonatomic, nullable, strong) NSNumber *floatingPlaceholderScale;
That's effectively null_resettable, then, right? Mark as such.

2017-07-12 16:07 UTC, willlarche commented on components/TextFields/src/MDCTextInputController.h
> + Default is primary color or blue.
Ha. It's GOING to be primary color when we have support for that. I won't write documentation that takes place in the future.

2017-07-12 16:10 UTC, willlarche commented on components/TextFields/src/MDCTextInputController.h
> + Default is same as inlinePlaceholderColorDefault.
Done.

2017-07-12 16:10 UTC, willlarche commented on components/TextFields/src/MDCTextInputController.h
> + Default is primary color or blue.
Done.

2017-07-12 16:14 UTC, ajsecord approved these changes

2017-07-12 16:32 UTC, willlarche commented on components/TextFields/src/MDCTextInputControllerDefault.h
>  @property(nonatomic, nullable, strong) NSNumber *floatingPlaceholderScale;
Done.

2017-07-12 17:20 UTC, ianegordon requested changes

2017-07-12 17:20 UTC, ianegordon commented on components/TextFields/src/MDCTextInputController.h
> +@property(class, nonatomic, null_resettable, strong) UIColor *errorColorDefault;
Naming is hard, but wouldn't this be defaultErrorColor?  Type usually comes last, and this is a color.
(Here and below)

2017-07-12 17:23 UTC, ianegordon commented on components/TextFields/src/MDCTextInputController.h
> +@property(class, nonatomic, null_resettable, strong) UIColor *errorColorDefault;
Discussed offline, postfix seems like a better choice than prefix.

Naming is hard.

2017-07-12 17:25 UTC, ianegordon approved these changes

2017-07-12 21:31 UTC, willlarche commented
Travis is acting up but I've gotten 2 greens from this repo and 1 from my branch. Also passes local tests.

2017-07-12 21:31 UTC, merged