[ShadowLayer] Support layer copying
material-components/material-components-ios pull request #1625
Opened 2017-07-11 18:46 UTC by romoore

Implementing -initWithLayer: for Shadow layers

Closes #248

2017-07-11 18:50 UTC, ajsecord requested changes

2017-07-11 18:50 UTC, ajsecord commented on components/ShadowLayer/src/MDCShadowLayer.m
>  // TODO(#993): Implement missing initWithLayer:
Remove comment?

2017-07-11 18:52 UTC, romoore commented on components/ShadowLayer/src/MDCShadowLayer.m
>  // TODO(#993): Implement missing initWithLayer:
Done.

2017-07-11 19:18 UTC, ajsecord approved these changes

2017-07-11 21:19 UTC, ianegordon requested changes
commonMDCXYZInit is typically intended to be called from all init functions.  Adding commonMDCXYZConfig is new / different.  Do we really need to add this additional method?  Can we modify the other init methods so we only ever call commonMDCXYZInit?

2017-07-12 16:50 UTC, ajsecord approved these changes

2017-07-12 16:51 UTC, ajsecord commented
@ianegordon your concerns were handled by Rob's latest commit.

2017-07-12 17:50 UTC, ianegordon approved these changes
Waiting for Travis, but LGTM.

2017-07-12 18:36 UTC, ianegordon commented
Successfully tested locally on 8.x, 9.x, 10.x Simulators.

2017-07-12 18:37 UTC, merged