[Feature Highlight] Swipe to dismiss
material-components/material-components-ios pull request #1636
Opened 2017-07-12 19:06 UTC by samnm

2017-07-12 19:18 UTC, ianegordon requested changes

2017-07-12 19:18 UTC, ianegordon commented on components/FeatureHighlight/src/private/MDCFeatureHighlightView+Private.m
> +  return sqrt(pow(a.x - b.x, 2) + pow(a.y - b.y, 2));
MDCHypot(a.x - b.x, a.y - b.y)

2017-07-12 19:18 UTC, ianegordon commented on components/FeatureHighlight/src/private/MDCFeatureHighlightDismissGestureRecognizer.m
> +  assert([self.view isKindOfClass:[MDCFeatureHighlightView class]]);
s/assert/NSCAssert/

2017-07-12 19:33 UTC, samnm commented on components/FeatureHighlight/src/private/MDCFeatureHighlightView+Private.m
> +  return sqrt(pow(a.x - b.x, 2) + pow(a.y - b.y, 2));
Done.

2017-07-12 19:33 UTC, samnm commented on components/FeatureHighlight/src/private/MDCFeatureHighlightDismissGestureRecognizer.m
> +  assert([self.view isKindOfClass:[MDCFeatureHighlightView class]]);
Done.

2017-07-13 17:23 UTC, ianegordon commented
The Travis failures are caused by floating point conversion errors.
Please investigate.

2017-07-17 21:46 UTC, ianegordon commented
Verified VO Back gesture works as expected on iPhone 5 w/ iOS 8.3.

2017-07-17 21:58 UTC, ianegordon approved these changes

2017-07-17 21:59 UTC, ianegordon commented
Tested Locally.

2017-07-17 21:59 UTC, merged