[Buttons] Reset Ink when moved to new superview
material-components/material-components-ios pull request #1656
Opened 2017-07-18 14:55 UTC by romoore

MDCButton will now reset all Ink effects before it is added to a new
superview. This prevents retaining Ripple objects indefinitely if the
button is moved between superviews while a touch is held down.

Closes #1655

2017-07-18 14:57 UTC, jgunaratne approved these changes

2017-07-18 15:38 UTC, ianegordon requested changes
Let's wait on Chat for an update on Speeddial since this affects rendering.

2017-07-18 15:38 UTC, ianegordon commented on components/Buttons/src/MDCButton.m
> +  if (newSuperview) {
Is there a reason we are checking for newSuperview != nil?

2017-07-18 15:38 UTC, romoore commented
Marking this blocked pending discussion with @chatura-atapattu  regarding the FAB Action Menu.

2017-07-18 16:45 UTC, chatura-atapattu commented
Taking aside the impact on the Speeddial, what would be the expected behavior for MDCButton if it was removed from one view and added to another mid-touch and ripple effect.  I think that instead of the ripple effect being immediately ended, we'd expect it to continue and end naturally, right? Would triggering the end animation achieve that behavior?

2017-07-20 19:41 UTC, romoore commented
I like where you're going with this, and I wonder if we might "clear" the ink either way when the view moves out of its parent, but differently depending on where it's going:
* Animated ink dissipation when a view is directly moved between parent views (`newSuperview != nil`)
* Unanimated ink removal when a view is removed from its parent view (`newSuperview == nil`)

What do you think of this approach?

2017-07-21 11:10 UTC, chatura-atapattu commented
Yeah, I think thats the way to go.

2017-07-21 15:14 UTC, ianegordon approved these changes

2017-07-21 15:54 UTC, romoore commented
Pulling in the latest changes and a dirty test with ActionMenu, it seems performing the animation when the view is moved will cause the ink to ripple twice when the menu is dismissed.

![fab-dismiss-animatedink](https://user-images.githubusercontent.com/1753199/28471255-85ee2af0-6e0a-11e7-9de4-3d80bf6d515c.gif)

It looks a little better if there is no animated dismissal of the ink, the result is basically the fade-out being cut short.

![fab-dismiss-inanimateink](https://user-images.githubusercontent.com/1753199/28471269-96a4fd9c-6e0a-11e7-97c1-cac71c033679.gif)

2017-07-21 17:01 UTC, romoore commented
A quick offline conversation with @ianegordon and I think we'll just have to dismiss the Ink in an unanimated way whenever it's removed from its superview (regardless of whether it's immediately added to another superview).  The visual artifact that results (see gif in my previous comment) is an acceptably-small side effect in exchange for removing the memory leak.  

I will trawl the remaining components in the MDC Catalog app to look for any other surprises, but I think the Action Menu/Speed Dial will need to be refactored slightly if we want to eliminate the ink dissipation artifact when the menu is dismissed.

2017-07-21 18:48 UTC, merged