[Snackbar] Notify MDCOverlayObservers of bottom offset changes
material-components/material-components-ios pull request #1659
Opened 2017-07-18 21:58 UTC by samnm

Notify MDCOverlayObservers of `MDCSnackbarManager.bottomOffset` changes and update an example to showcase this.

2017-07-19 21:55 UTC, ShepJGoogle submitted a review, later dismissed

2017-07-19 21:55 UTC, ShepJGoogle commented on components/Snackbar/examples/supplemental/SnackbarExampleSupplemental.h
Should we include documentation?

2017-07-19 21:55 UTC, ShepJGoogle commented on components/Snackbar/examples/supplemental/SnackbarExampleSupplemental.h
> +
Same as above

2017-07-20 22:32 UTC, ianegordon requested changes

2017-07-20 22:32 UTC, ianegordon commented on components/Snackbar/src/private/MDCSnackbarOverlayView.m
> +                         CGRectGetMaxX(self.frame),
I would expect this to be CGRectGetWidth(self.frame).
If this isn't GetWidth, consider documenting.

2017-07-24 16:43 UTC, samnm commented on components/Snackbar/src/private/MDCSnackbarOverlayView.m
> +                         CGRectGetMaxX(self.frame),
Good catch. Fixed.

2017-07-24 16:44 UTC, samnm commented on components/Snackbar/examples/supplemental/SnackbarExampleSupplemental.h
It isn't really necessary here... I just removed the comment from the floatingButton property.

2017-07-24 20:09 UTC, ajsecord approved these changes

2017-07-26 13:30 UTC, ajsecord commented
@ianegordon is out sick, I can confirm that @samnm made the change requested.

@ShepJGoogle Can you please review your requested changes?

2017-07-26 17:30 UTC, ianegordon requested changes
This appears to break on rotation.

From Snackbar Overlay View in portrait.
Toggle bottom bar
Show Snackbar
Rotate to landscape (button disappears behind snackbar and bottombar)
Rotate back to portrait (button jump to the upper right corner)

![screen shot 2017-07-26 at 13 28 10](https://user-images.githubusercontent.com/1121006/28634842-834376fc-7206-11e7-94be-6617c5e18c15.png)

2017-07-26 17:30 UTC, ianegordon commented on components/Snackbar/examples/SnackbarOverlayViewExample.m
> +                                                            CGRectGetMaxX(self.view.bounds),
Do we want CGRectGetWidth() here?
If self.bottomBar is a subview of self.view I would expect to use the Height / Width of self.view.bounds.
I wouldn't typically expect to use anything other than GetHeight and GetWidth with bounds.
GetMaxX and GetMaxY would be more common with self.frame.

2017-07-26 17:30 UTC, ianegordon commented on components/Snackbar/src/private/MDCSnackbarOverlayView.m
> +                         CGRectGetMaxY(self.frame) - self.bottomOffset,
Consider adding a comment along the lines of:
// We use the MaxY(self.frame) instead of the Height(self.frame) since we are dealing with screen coordinates.

2017-07-26 19:03 UTC, samnm commented on components/Snackbar/examples/SnackbarOverlayViewExample.m
> +                                                            CGRectGetMaxX(self.view.bounds),
Fixed.

2017-07-26 19:04 UTC, samnm commented on components/Snackbar/src/private/MDCSnackbarOverlayView.m
> +                         CGRectGetMaxY(self.frame) - self.bottomOffset,
Fixed.

2017-07-26 19:06 UTC, samnm commented
That rotation bug appears to have existed before this change. I can't find a fix for it right now so I'd rather not block this PR on that fix.

2017-07-26 19:19 UTC, ianegordon approved these changes

2017-07-26 19:21 UTC, ianegordon commented
Will solve rotation issue in another PR.
#1701 created.

2017-07-26 19:21 UTC, merged