[Buttons] Unbounded ink aligns to content insets
material-components/material-components-ios pull request #1670
Opened 2017-07-20 18:47 UTC by romoore

Unbounded ink should be centered on the content of buttons, but bounded
ink should remain aligned with the bounds of the button.

* Changing Ink behavior for unbounded ink
* Modified Content Rect Insets example in the Catalog

Closes #1669

2017-07-20 19:42 UTC, ajsecord commented
I think that the _initial_ center of ink needs to be the user's touch point, especially in the unbounded ink. Let's chat?

2017-07-20 19:43 UTC, ajsecord requested changes
Concerns about the ink center (in comment)

2017-07-21 13:34 UTC, romoore commented
For reference, here are similar unbounded Ink + button examples from 1fd43a55:

![inkunbound-buttonraised-1fd43a55](https://user-images.githubusercontent.com/1753199/28465579-42f3b7b4-6df7-11e7-9930-7cdf69df6a48.gif)

![inkunbound-buttonflat-1fd43a55](https://user-images.githubusercontent.com/1753199/28465720-c49c90e2-6df7-11e7-8d6d-a2ba7355c80f.gif)

![inkunbound-buttonfloating-1fd43a55](https://user-images.githubusercontent.com/1753199/28465588-472445d8-6df7-11e7-9048-537c7cff84ec.gif)

2017-07-21 17:54 UTC, ajsecord approved these changes
Reviewed in person.

2017-07-21 17:54 UTC, merged