Change TravisCI Destination
material-components/material-components-ios pull request #1672
Opened 2017-07-21 16:12 UTC by ianegordon

2017-07-21 16:13 UTC, willlarche approved these changes

2017-07-21 17:53 UTC, ajsecord requested changes

2017-07-21 17:53 UTC, ajsecord commented on .travis.yml
> +#  - travis_wait scripts/test_all catalog/MDCCatalog.xcworkspace:MDCUnitTests
Err.. why aren't we building everything? And no more unit tests?

2017-07-24 14:43 UTC, willlarche requested changes

2017-07-24 14:43 UTC, willlarche commented on .travis.yml
> -    - DESTINATION="platform=iOS Simulator,name=iPhone 5,OS=8.1" SDK="iphonesimulator8.1"
We really need this one still. It's 32-bit and iOS 8. Removing it lowers our coverage by .3%.

2017-07-24 14:44 UTC, romoore commented on .travis.yml
> -    - DESTINATION="platform=iOS Simulator,name=iPhone 5,OS=8.1" SDK="iphonesimulator8.1"
If we have 32-bit specific code, that's probably more important than the percentage.

2017-07-26 01:57 UTC, ianegordon commented on .travis.yml
> +#  - travis_wait scripts/test_all catalog/MDCCatalog.xcworkspace:MDCUnitTests
"xcodebuild build test" does build MDCCatalog, and runs the unit and UI tests.
I'm trying to determine if we can put all of our workspaces in a matrix.
This PR may not turn out to be something we merge.  (Description updated above)

2017-07-26 01:59 UTC, ianegordon commented
As a point of reference, I was able to get MDFInternationalization building and testing on all three devices.

See:
https://github.com/material-foundation/material-internationalization-ios

Config file:
https://github.com/material-foundation/material-internationalization-ios/blob/develop/.travis.yml

2017-07-26 16:05 UTC, ianegordon commented
To be continued,.....

2017-07-26 16:05 UTC, closed without merging