[TextFields] Reorganizing and internal clean up
material-components/material-components-ios pull request #1677
Opened 2017-07-24 17:06 UTC by willlarche

In preparation for multiple text input classes, non-shared logic has been moved into text field and out of the fundament and text insets have been renamed.

2017-07-24 18:14 UTC, romoore requested changes
I think the height estimation can be turned into a method/function. I'm also concerned about direct comparison of floating point values.

2017-07-24 18:14 UTC, romoore commented on components/TextFields/src/MDCTextField.m
> +@property(nonatomic, strong) NSLayoutConstraint *underlineY;
Comment to document this property?

2017-07-24 18:14 UTC, romoore commented on components/TextFields/src/MDCTextField.m
> +  CGFloat estimatedTextHeight = MDCCeil(self.font.lineHeight * 2.f) / 2.f;
Does this estimation work for CJK fonts?

2017-07-24 18:14 UTC, romoore commented on components/TextFields/src/MDCTextField.m
> +  CGFloat estimatedTextHeight = MDCCeil(self.font.lineHeight * 2.f) / 2.f;
This same estimation is in intrinsicContentSize and above in setupUnderlineConstraints. Consider turning it into a method.

2017-07-24 18:14 UTC, romoore commented on components/TextFields/src/MDCTextField.m
> +  return self.underlineY.constant != [self underlineYConstant];
Better to compare these floats to within some delta rather than exactly the same?

2017-07-24 18:19 UTC, willlarche commented on components/TextFields/src/MDCTextField.m
> +  CGFloat estimatedTextHeight = MDCCeil(self.font.lineHeight * 2.f) / 2.f;
CJK support will be added later. Right now it's guaranteed on latin, arabic and hebrew.

2017-07-24 18:23 UTC, willlarche commented on components/TextFields/src/MDCTextField.m
> +@property(nonatomic, strong) NSLayoutConstraint *underlineY;
Done

2017-07-24 18:31 UTC, willlarche commented on components/TextFields/src/MDCTextField.m
> +  CGFloat estimatedTextHeight = MDCCeil(self.font.lineHeight * 2.f) / 2.f;
Good idea. Done.

2017-07-24 18:31 UTC, willlarche commented on components/TextFields/src/MDCTextField.m
> +  return self.underlineY.constant != [self underlineYConstant];
So true. Done.

2017-07-24 19:37 UTC, romoore approved these changes

2017-07-24 20:24 UTC, ajsecord requested changes

2017-07-24 20:24 UTC, ajsecord commented on components/TextFields/src/MDCTextField.m
> + This constraint controls the default center Y of the underline view.
Delete the leading empty line. Probably just "Constraint for the default center y-coordinate of the underline view."

2017-07-24 20:24 UTC, ajsecord commented on components/TextFields/src/MDCTextField.m
> + half padding.
Too complicated to understand in a single go. Maybe add ", e.g. below the text field at a distance of one-half of the padding"?

2017-07-24 20:24 UTC, ajsecord commented on components/TextFields/src/MDCTextField.m
> +  [NSLayoutConstraint constraintWithItem:self.underline
+4

2017-07-24 20:24 UTC, ajsecord commented on components/TextFields/src/MDCTextField.m
> +}
This logic is weird. Was 1000 just chosen at random?

2017-07-24 20:24 UTC, ajsecord commented on components/TextFields/src/MDCTextInputControllerFullWidth.m
> -  UIEdgeInsets textContainerInset = UIEdgeInsetsZero;
In the future, this kind of search-and-replace is a nice candidate for a single, trivially-reviewed, PR.

2017-07-24 22:45 UTC, willlarche commented on components/TextFields/src/MDCTextField.m
> +}
Yeah this one. @romoore correctly pointed out that I was doing floating point comparison which is bad. So I need to convert these. I chose 1000 to be conservative. I believe the most decimal places It'll ever be is actually 1 which would be 10. Should I change to 10?

2017-07-24 23:00 UTC, willlarche commented on components/TextFields/src/MDCTextField.m
> + half padding.
Took another stab at clarity.

2017-07-24 23:00 UTC, willlarche commented on components/TextFields/src/MDCTextField.m
> +  [NSLayoutConstraint constraintWithItem:self.underline
Done.

2017-07-24 23:00 UTC, willlarche commented on components/TextFields/src/MDCTextField.m
> + This constraint controls the default center Y of the underline view.
Done.

2017-07-25 01:06 UTC, romoore commented on components/TextFields/src/MDCTextField.m
> +}
How about MDCCGFloatEqual ?

2017-07-25 02:17 UTC, willlarche commented on components/TextFields/src/MDCTextField.m
> +}
Perfect! Done.

2017-07-25 18:35 UTC, ajsecord approved these changes

2017-07-25 18:35 UTC, merged