[Collections] Reuse label frames in applyMetrics
material-components/material-components-ios pull request #1688
Opened 2017-07-25 14:41 UTC by romoore

`applyMetrics` currently computes the UILabel frames both to determine
the size of the frames and again to determine their origin. Reusing the
frames results in a lower CPU utilization while rendering the cells.

### Original code
![frame-28 0 0](https://user-images.githubusercontent.com/1753199/28577770-afa84808-7125-11e7-8b1c-d9fb978dede9.png)

### Reused frames
![frame-28 0 0-reuse](https://user-images.githubusercontent.com/1753199/28577787-b8f225fa-7125-11e7-8a9a-91100f7cbdef.png)

2017-07-25 14:41 UTC, romoore commented
The names are terrible, would appreciate help in naming.

2017-07-25 22:13 UTC, ShepJGoogle requested changes

2017-07-25 22:13 UTC, ShepJGoogle commented on components/CollectionCells/src/MDCCollectionViewTextCell.m
> +  NSInteger numberOfAllVisibleTextLines = [self numberOfAllVisibleTextLinesForLabelSize:textFrame.size detailSize:detailFrame.size];
Break into new line

2017-07-25 22:13 UTC, ShepJGoogle commented on components/CollectionCells/src/MDCCollectionViewTextCell.m
> +  return [self numberOfLinesForLabel:_textLabel withSize:labelSize] + [self numberOfLinesForLabel:_detailTextLabel withSize:detailSize];
Break into new line

2017-07-26 13:26 UTC, ajsecord requested changes
Thanks for including measurements! Most optimization PRs are aspirational.

What's the motivation for this? Do we have an issue that I can look at about collection view performance?

2017-07-26 14:04 UTC, romoore commented
@ajsecord  On Monday, an internal client contacted us about a potential performance decrease scrolling collection views, which kicked-off an investigation by me to find out if I had made a problematic change.  This was among the improvements that I could quickly identify to improve performance.

2017-07-26 14:06 UTC, ajsecord requested changes
Looking good, but please document the original issue and link to this PR.

2017-07-26 14:21 UTC, romoore commented
Opened an Issue for the multiple calls and linked in the summary of this issue.

2017-07-26 19:56 UTC, romoore commented
Rebased from develop

2017-07-26 21:07 UTC, ianegordon commented
TODO: Discuss further after looking at #1705.

2017-07-26 21:37 UTC, romoore commented
Abandon in favor of #1705

2017-07-26 21:37 UTC, closed without merging