[TextFields] Fundament implementation of trailingViewMode.
material-components/material-components-ios pull request #1702
Opened 2017-07-26 19:35 UTC by willlarche

2017-07-26 21:23 UTC, ianegordon requested changes

2017-07-26 21:23 UTC, ianegordon commented on components/TextFields/src/private/MDCTextInputCommonFundament.m
> +    _trailingViewMode = (UITextFieldViewMode)[aDecoder decodeIntegerForKey:MDCTextInputFundamentTrailingViewKey];
Do we need to check for the existence of these keys before we decode them?
```
if ([aDecoder containsValueForKey:MDCTrailingViewKey]) {
  _trailingViewMode = (UITextFieldViewMode)[aDecoder decoderIntergerForKey:MDCTrailingViewKey];
}
```
And the other ivars? (Happy to have that in another PR if we do need to do so)

2017-07-26 23:54 UTC, willlarche commented on components/TextFields/src/private/MDCTextInputCommonFundament.m
> +    _trailingViewMode = (UITextFieldViewMode)[aDecoder decodeIntegerForKey:MDCTextInputFundamentTrailingViewKey];
Spoke with you offline. I do indeed need these checks. Let's do that in another PR for there are more than just this one.

2017-07-27 15:31 UTC, ianegordon commented
SGTM.
#1709 opened.

2017-07-27 15:31 UTC, ianegordon approved these changes

2017-07-27 15:32 UTC, merged