Align frames to pixel boundaries
material-components/material-components-ios pull request #1730
Opened 2017-08-03 18:02 UTC by romoore

Adding a new function to realign a CGRect (frame) to pixel boundaries
based on the screen scale. After a review of the catalog, I'm updating
the areas where I found misaligned frames.

Closes #1723

2017-08-03 18:07 UTC, ajsecord requested changes

2017-08-03 18:07 UTC, ajsecord commented on components/Slider/examples/SliderCompareExampleViewController.m
> +#import "MaterialMath.h"
Sort imports...

2017-08-03 18:07 UTC, ajsecord commented on components/private/Math/src/MDCMath.h
> +static inline CGRect MDCRectIntegral(CGRect rect) {
This isn't as obvious as just `MDCSqrt` or whatever, please document.

2017-08-03 18:22 UTC, ajsecord requested changes

2017-08-03 18:22 UTC, ajsecord commented on components/private/Math/src/MDCMath.h
> + size.
Not really true. Can you please document the `scale` functionality? I'm assuming that this is meant to round to pixel boundaries?

2017-08-03 18:23 UTC, romoore commented on components/Slider/examples/SliderCompareExampleViewController.m
> +#import "MaterialMath.h"
Done

2017-08-03 18:24 UTC, romoore commented on components/private/Math/src/MDCMath.h
> + size.
Done.

2017-08-03 20:31 UTC, romoore commented
While adding unit tests, I found the current approach does not match CGRectIntegral.

2017-08-07 15:27 UTC, willlarche requested changes

2017-08-07 15:27 UTC, willlarche commented on components/Buttons/examples/supplemental/ButtonsTypicalUseSupplemental.m
> +                                      [[UIScreen mainScreen] scale]);
scale is a property. Best to access with .

2017-08-07 15:27 UTC, willlarche commented on components/Buttons/src/MDCButton.m
> +  self.titleLabel.frame = MDCRectAlignToScale(self.titleLabel.frame, [[UIScreen mainScreen] scale]);
Same about scale, tho I know it's inconsistent in the codebase. We can correct them as we go along or feel free to do a PR with a batch change. Same for bounds.

2017-08-07 15:27 UTC, willlarche commented on components/FeatureHighlight/examples/supplemental/FeatureHighlightExampleSupplemental.m
> +                CGRectMake(self.view.frame.size.width / 2 - labelSize.width / 2, 20, labelSize.width, labelSize.height), [[UIScreen mainScreen] scale]);
Verify that this is the correct spacing with format_all

2017-08-07 15:27 UTC, willlarche commented on components/FeatureHighlight/src/private/MDCFeatureHighlightView+Private.m
> +  CGRect titleFrame = MDCRectAlignToScale((CGRect){titlePos, titleSize}, [[UIScreen mainScreen] scale]);
.scale

2017-08-07 15:29 UTC, willlarche requested changes

2017-08-07 15:29 UTC, willlarche commented on components/private/ThumbTrack/src/MDCThumbTrack.m
> +        _valueLabel.frame = MDCRectAlignToScale(_valueLabel.frame, [[UIScreen mainScreen] scale]);
.scale

2017-08-07 15:29 UTC, willlarche commented on components/private/Math/src/MDCMath.h
> +                                         rect.origin.y - newOrigin.y);
alignment

2017-08-07 15:47 UTC, romoore commented on components/Buttons/examples/supplemental/ButtonsTypicalUseSupplemental.m
> +                                      [[UIScreen mainScreen] scale]);
Done

2017-08-07 15:47 UTC, romoore commented on components/Buttons/src/MDCButton.m
> +  self.titleLabel.frame = MDCRectAlignToScale(self.titleLabel.frame, [[UIScreen mainScreen] scale]);
Done

2017-08-07 15:47 UTC, romoore commented on components/FeatureHighlight/src/private/MDCFeatureHighlightView+Private.m
> +  CGRect titleFrame = MDCRectAlignToScale((CGRect){titlePos, titleSize}, [[UIScreen mainScreen] scale]);
Done

2017-08-07 15:47 UTC, romoore commented on components/FeatureHighlight/examples/supplemental/FeatureHighlightExampleSupplemental.m
> +                CGRectMake(self.view.frame.size.width / 2 - labelSize.width / 2, 20, labelSize.width, labelSize.height), [[UIScreen mainScreen] scale]);
Done

2017-08-07 15:47 UTC, romoore commented on components/private/Math/src/MDCMath.h
> +                                         rect.origin.y - newOrigin.y);
Done

2017-08-07 15:47 UTC, romoore commented on components/private/ThumbTrack/src/MDCThumbTrack.m
> +        _valueLabel.frame = MDCRectAlignToScale(_valueLabel.frame, [[UIScreen mainScreen] scale]);
Done

2017-08-07 15:51 UTC, willlarche approved these changes

2017-08-07 17:17 UTC, ianegordon requested changes

2017-08-07 17:17 UTC, ianegordon commented on components/Buttons/examples/supplemental/ButtonsTypicalUseSupplemental.m
> +                                      [UIScreen mainScreen].scale);
Note: [UIScreen mainScreen] is now a class property and could be accessed by UIScreen.mainScreen.
We should probably discuss whether we want to adopt class properties at our next weekly.

2017-08-07 17:17 UTC, ianegordon commented on components/FeatureHighlight/src/private/MDCFeatureHighlightView+Private.m
> +                           kMDCFeatureHighlightTextPadding;
nit: alignment.  I would expect a 4 character indent.

2017-08-07 17:17 UTC, ianegordon commented on components/private/Math/src/MDCMath.h
> +      CGPointMake(MDCFloor(rect.origin.x * scale) / scale, MDCFloor(rect.origin.y * scale) / scale);
This currently only works with standardized rects.
We likely want
CGFloat xOffset = MDCFloor(CGRectGetXOffset(rect) * scale) / scale;
CGFloat yOffset = MDCFloor(CGRectGetYOffset(rect) * scale) / scale;

There is some additional logic around widths.

Prefer CGRect accessor macros over rect.origin or rect.size unless you have explicitly called CGRectStandardize()

2017-08-07 17:19 UTC, ianegordon commented on components/private/Math/tests/unit/MDCMathTests.m
> +  CGRect alignedScale3Rect = CGRectMake(1.0 / 3.0, 2.0 / 3.0, 4.0 / 3.0, 19.0 / 3.0);
Consider adding a test on a non-standardized CGRect.

CGRect nonstandardRect = CGRectMake (100.0, 100.0, -40, -20)

Ensure we are still fully enclosing the original rect, even if the height and/or width is negative.

2017-08-07 18:41 UTC, romoore commented on components/Buttons/examples/supplemental/ButtonsTypicalUseSupplemental.m
> +                                      [UIScreen mainScreen].scale);
We may also want to consider avoiding `mainScreen` altogether and using [UIView.window.screen](https://developer.apple.com/documentation/uikit/uiwindow/1621597-screen) instead.

2017-08-07 18:41 UTC, romoore commented on components/FeatureHighlight/src/private/MDCFeatureHighlightView+Private.m
> +                           kMDCFeatureHighlightTextPadding;
Done

2017-08-07 18:41 UTC, romoore commented on components/private/Math/src/MDCMath.h
> +      CGPointMake(MDCFloor(rect.origin.x * scale) / scale, MDCFloor(rect.origin.y * scale) / scale);
Done

2017-08-07 18:58 UTC, romoore commented on components/private/Math/tests/unit/MDCMathTests.m
> +  CGRect alignedScale3Rect = CGRectMake(1.0 / 3.0, 2.0 / 3.0, 4.0 / 3.0, 19.0 / 3.0);
Done

2017-08-07 20:22 UTC, ianegordon approved these changes

2017-08-07 20:23 UTC, ianegordon commented
LGTM.  Please merge once Travis gives the OK.

2017-08-07 20:46 UTC, merged