[Collections] Allow selection of cells with hidden ink
material-components/material-components-ios pull request #1739
Opened 2017-08-04 19:17 UTC by romoore

MDCCollectionViewController does not receive messages for
`-collectionView:didSelectItemAtIndexPath:` if it responds `NO` to
`-collectionView:shouldHighlightCellAtIndexPath:`. It seems by allowing
highlight, but not performing a highlight animation on the cell, the delegate
will receive *didSelect* messages for cells with hidden ink.

Closes #1446

2017-08-04 20:32 UTC, romoore commented
Need to fix the header.

2017-08-18 14:35 UTC, gambard commented
Thanks for doing this!
Overall it looks good, however, I am not sure about calling startTouchEndedAnimationAtPoint:completion: on the inkView if you did not start the ink animation. From my understanding of the code, it should be fine.

2017-08-18 14:44 UTC, romoore commented
@gambard  Awesome, thanks for the review!  If ink is disabled for that indexPath, then the method exits early and the ink animation should not behavior.  There should not be a change in behavior for inked cells, only that those without ink will have selection actions passed to the delegate.

2017-08-18 17:20 UTC, ianegordon commented
Hi @romoore.  I believe you were investigating this a bit.  Are you ready for me to review / merge?

2017-08-18 17:21 UTC, romoore commented
Yep, whenever you have time. 👍

2017-08-18 17:23 UTC, ianegordon requested changes

2017-08-18 17:23 UTC, ianegordon commented on components/Collections/src/MDCCollectionViewController.h
> -- (BOOL)collectionView:(nonnull UICollectionView *)collectionView
This is in the public API.  If we want to remove it, we should go through the deprecation process.  I could see people subclassing MDCCollectionViewController just to overwrite methods like this.

2017-08-18 17:23 UTC, ianegordon commented on components/Collections/src/MDCCollectionViewController.m
> -  }
Can we ignore the styler and just return YES to fix the functionality?

2017-08-18 17:41 UTC, romoore commented on components/Collections/src/MDCCollectionViewController.m
> -  }
Are you suggesting keeping the shouldHighlight... and returning YES each time, but then in didHighlight keeping the proposed changes?

2017-08-18 17:43 UTC, romoore commented on components/Collections/src/MDCCollectionViewController.h
> -- (BOOL)collectionView:(nonnull UICollectionView *)collectionView
The [default implementation is to return YES](https://developer.apple.com/documentation/uikit/uicollectionviewdelegate/1618070-collectionview?language=objc). Do you see an advantage in us explicitly returning YES as well?

2017-08-23 19:24 UTC, ianegordon commented
Discussed offline.
We will keep shouldHighlight: but the implementation will just return YES.  The new handling will allow Ink and Selection to co-exist.

2017-08-23 21:28 UTC, ianegordon approved these changes

2017-08-23 21:29 UTC, ianegordon commented
LGTM.  Please merge when Travis is happy.

2017-08-24 02:38 UTC, merged