[TextFields] Multiline examples.
material-components/material-components-ios pull request #1743
Opened 2017-08-04 22:42 UTC by willlarche

Dependent on #1740 and #1742

2017-08-07 00:06 UTC, willlarche commented
Errors are codecov. Build is safe.

2017-08-08 16:50 UTC, ajsecord approved these changes

2017-08-08 18:21 UTC, ianegordon requested changes
Please verify date, otherwise LGTM.

2017-08-08 18:21 UTC, ianegordon commented on components/TextFields/examples/MultilineTextFieldExample.m
> + Copyright 2016-present the Material Components for iOS authors. All Rights Reserved.
s/2016/2017/ ?

2017-08-08 18:21 UTC, ianegordon approved these changes

2017-08-08 22:18 UTC, merged