[PageControl] Send UIControlEventChanges Event on setCurrentPage
material-components/material-components-ios pull request #1746
Opened 2017-08-07 16:40 UTC by ianegordon

Author:    Eccelor <social@eccelor.com>
Date:      Wed Aug 2 18:02:34 2017 +0530

Call sendActions:UIControlerEventValueChanged when setCurrentPage is called.

2017-08-07 16:49 UTC, ianegordon commented
googlebot seems confused by this PR.  Possibly because it was generated from a cherry-pick from another PR.  @Eccelor has signed the cla.

2017-08-07 20:30 UTC, romoore requested changes

2017-08-07 20:30 UTC, romoore commented on components/PageControl/src/MDCPageControl.m
> +    [self sendActionsForControlEvents:UIControlEventValueChanged];
I believe the CATransaction is asynchronously dispatched into the main run loop. I think we should place the `sendActionsForControlEvents:` into the completion block of the transaction to ensure that it's only invoked once the changes are actually made.

```objectivec
    dispatch_async(dispatch_get_main_queue(), ^{
      NSLog(@"Dispatched before");
    });
    [CATransaction begin];
    [CATransaction setDisableActions:YES];
    [_indicators[previousPage] setHidden:NO];
    [CATransaction setCompletionBlock:^{
      NSLog(@"Completion block");
    }];
    [CATransaction commit];
    dispatch_async(dispatch_get_main_queue(), ^{
      NSLog(@"Dispatched after");
    });

    NSLog(@"Subsequent code");
```

```
2017-08-07 16:29:03.806 MDCCatalog[61661:7937194] Subsequent code
2017-08-07 16:29:03.807 MDCCatalog[61661:7937194] Dispatched before
2017-08-07 16:29:03.807 MDCCatalog[61661:7937194] Completion block
2017-08-07 16:29:03.807 MDCCatalog[61661:7937194] Dispatched after
```

2017-08-08 16:59 UTC, ajsecord commented on components/PageControl/src/MDCPageControl.m
> +    [self sendActionsForControlEvents:UIControlEventValueChanged];
Hrm. Does UIButton dispatch when the user lifts their finger or after the animation completes?

2017-08-08 20:07 UTC, ianegordon commented
Hi @Eccelor.  After looking into it, we likely do not want to send an action on programmatic changes.  

From Apple's UIControl documentation:
"Action methods are called when the user interacts with the control in specific ways."

The specific bit is the "user interacts".  It specifically does not mention programmatic changes.

You can see this for yourself if you create a UIPageControl and wire up the valueChanged action.

I'm going to close this, but feel free to re-open if you have questions.  And even though we aren't planning on landing the PR, many thanks for sending it our direction!

👍

2017-08-08 20:07 UTC, closed without merging