[Collections] Limit the drag needed to dismiss an item
material-components/material-components-ios pull request #1811
Opened 2017-08-16 15:33 UTC by gambard

When using the swipe-to-dimiss gesture on large screens, the distance on which the user has to move the item can be big.
This commit limits the distance by using the width of the item instead of the width of the collection.

Closes #1780

2017-08-16 15:35 UTC, romoore requested changes

2017-08-16 15:35 UTC, romoore commented on components/Collections/src/private/MDCCollectionViewEditor.m
> +    return _cellSnapshot.bounds.size.width / 2;
Please use CGRectGetWidth(_cellSnapshot.bounds)

2017-08-17 07:08 UTC, gambard commented on components/Collections/src/private/MDCCollectionViewEditor.m
> +    return _cellSnapshot.bounds.size.width / 2;
Done.

2017-08-17 12:49 UTC, romoore approved these changes

2017-08-17 14:02 UTC, merged