[TextFields] Renaming old default to legacy default.
material-components/material-components-ios pull request #1815
Opened 2017-08-16 20:51 UTC by willlarche

Rename of files and opting out of new functionality.

No new functionality.

2017-08-17 23:16 UTC, ianegordon requested changes
This is the first pass.  I'll take another when we've landed the PR this depends on so I can step through.

2017-08-17 23:16 UTC, ianegordon commented on components/TextFields/src/MDCTextInputControllerLegacyDefault.m
> +    _activeColor =
If the decoder doesn't have a value for ActiveColorKey, won't this overwrite the default value we just set for _activeColor to nil?
Check for existence of keys?

2017-08-17 23:16 UTC, ianegordon commented on components/TextFields/src/MDCTextInputControllerLegacyDefault.m
> +  [self setupInput];
Consider moving inside if (self) block?
Usually I don't expect to see anything expect return self; after the if block.

2017-08-17 23:16 UTC, ianegordon commented on components/TextFields/src/MDCTextInputControllerLegacyDefault.m
> +@synthesize errorColor = _errorColor;
If you explicitly define setErrorColor and errorColor below do you need to @synthesize?
(Here and above / below)

2017-08-17 23:16 UTC, ianegordon commented on components/TextFields/src/MDCTextInputControllerLegacyDefault.m
> +  _internalCharacterCounter = [MDCTextInputAllCharactersCounter new];
Internally, we prefer [[MDCClass alloc] init] over new.

2017-08-17 23:16 UTC, ianegordon commented on components/TextFields/src/MDCTextInputControllerLegacyDefault.m
> +    if (!announcementString.length) {
announcementString was just created / set to nil on the line above.
Will announcementString.length ever not be 0?
Do we mean to test another string here?

2017-08-19 19:13 UTC, willlarche commented on components/TextFields/src/MDCTextInputControllerLegacyDefault.m
> +@synthesize errorColor = _errorColor;
So true! There were a few others too.

2017-08-19 19:15 UTC, willlarche commented on components/TextFields/src/MDCTextInputControllerLegacyDefault.m
> +    _activeColor =
.activeColor actually handles nil in its setter and getting. It uses the default!

2017-08-19 19:15 UTC, willlarche commented on components/TextFields/src/MDCTextInputControllerLegacyDefault.m
> +  [self setupInput];
Done!

2017-08-19 19:17 UTC, willlarche commented on components/TextFields/src/MDCTextInputControllerLegacyDefault.m
> +  _internalCharacterCounter = [MDCTextInputAllCharactersCounter new];
Done!

2017-08-19 19:21 UTC, willlarche commented on components/TextFields/src/MDCTextInputControllerLegacyDefault.m
> +    if (!announcementString.length) {
Good catch. This is from copying code where the state is different. Done.

2017-08-19 19:40 UTC, willlarche commented
Ready for re-review.

2017-08-21 15:16 UTC, ianegordon approved these changes

2017-08-21 15:16 UTC, merged