[Buttons] Default hitAreaInsets for FAB
material-components/material-components-ios pull request #1866
Opened 2017-08-21 20:12 UTC by romoore

The Floating Action Button should have default hitAreaInsets so that it
adheres the minimum touch target in the Material Design guidelines.
This commit introduces a set of default hitAreaInsets for the different
FAB styles as well as a warning if a button's touch target is smaller
than the 48-point minimum.

Closes #223

2017-08-21 20:13 UTC, romoore commented
Marking "author will merge" to ensure I get feedback from senior team members.

2017-08-22 13:22 UTC, ianegordon requested changes
There is concern about unexpected behavior on adjacent buttons.  I believe the current plan is to expand the hitAreaInsets only for the small FAB?

2017-08-22 15:05 UTC, romoore commented
Added examples:

### ButtonBar
![simulator screen shot - iphone 4s - 2017-08-22 at 11 00 52](https://user-images.githubusercontent.com/1753199/29572237-bd15cf78-8729-11e7-9e75-a545db19db78.png)

### NavigationBar
![simulator screen shot - iphone 4s - 2017-08-22 at 11 01 07](https://user-images.githubusercontent.com/1753199/29572247-c56cc988-8729-11e7-9930-6ee79470db86.png)

![simulator screen shot - iphone 4s - 2017-08-22 at 11 00 41](https://user-images.githubusercontent.com/1753199/29572255-ca7a8988-8729-11e7-9e7f-4e4d031ea50d.png)

2017-08-22 21:23 UTC, ianegordon approved these changes

2017-08-22 21:41 UTC, ianegordon requested changes

2017-08-22 21:41 UTC, ianegordon commented on components/Buttons/src/MDCButton.m
> +      NSLog(@"Button touch target is too small. Button: %@, Touch Target: %@", [self description],
Indicate target size.
Button: [self description] touch target (24 x 34) is smaller than the recommended (48 x 48).

2017-08-22 21:41 UTC, ianegordon commented on components/Buttons/src/MDCButton.m
> +    return CGRectContainsPoint(UIEdgeInsetsInsetRect(self.bounds, self.hitAreaInsets), point);
Do you need to CGRectStandardized(self.bounds)?

2017-08-22 21:41 UTC, ianegordon commented on components/Buttons/src/MDCFloatingButton.m
> +      return UIEdgeInsetsMake(-4, -4, -4, -4);
Consider adding a comment to lend some context to why -4s were chosen:
// Set EdgeInsets to ensure that the hit target of the Mini meets the minimum recommendation of 48 x 48.

2017-08-22 21:41 UTC, ianegordon commented on components/Buttons/tests/unit/ButtonsTests.m
> +  XCTAssertEqualWithAccuracy([button elevationForState:button.state], normalElevation,
Per our style guide, if we line-break on one parameter, each parameter should get its own line.

2017-08-23 00:57 UTC, romoore commented on components/Buttons/src/MDCButton.m
> +    return CGRectContainsPoint(UIEdgeInsetsInsetRect(self.bounds, self.hitAreaInsets), point);
Yes, it appears that UIEdgeInsetsInsetRect performs a literal manipulation as defined in the docs and does not standardize the rect first.

2017-08-23 01:15 UTC, romoore commented on components/Buttons/src/MDCButton.m
> +    return CGRectContainsPoint(UIEdgeInsetsInsetRect(self.bounds, self.hitAreaInsets), point);
After writing the unit test, it seems that setting either the frame or the bounds property of a UIView standardizes the rect in the setter.  I will add the call to CGRectStandardize, but I'm having difficulty coming up with a unit test.

2017-08-23 01:23 UTC, romoore commented on components/Buttons/tests/unit/ButtonsTests.m
> +  XCTAssertEqualWithAccuracy([button elevationForState:button.state], normalElevation,
Done

2017-08-23 01:23 UTC, romoore commented on components/Buttons/src/MDCFloatingButton.m
> +      return UIEdgeInsetsMake(-4, -4, -4, -4);
Done

2017-08-23 01:23 UTC, romoore commented on components/Buttons/src/MDCButton.m
> +      NSLog(@"Button touch target is too small. Button: %@, Touch Target: %@", [self description],
Done

2017-08-24 15:59 UTC, ianegordon commented on components/Buttons/src/MDCButton.m
> +      NSLog(@"Button touch target does not meet minimum size guidlines of (48, 48). Button: %@, "
Super-nit: consider using MDCButtonMinimumTouchTargetWidth / Height instead of hard-coding 48 x 48.

2017-08-24 16:11 UTC, ianegordon requested changes

2017-08-24 16:11 UTC, ianegordon commented on components/Buttons/src/MDCButton.m
> +  return [super pointInside:point withEvent:event];
If we are switching to [super pointInside:withEvent:] here, do we also want to in our implementation if we have custom hitAreaInsets above?

Alternatively, should this return CGRectContainsPoint()?

If there is cause for these two cases to be different, we should document why.

2017-08-24 16:11 UTC, ianegordon commented on components/NavigationBar/examples/NavigationBarLayoutExample.m
> -
I appreciate this cleanup, but changes to license clauses can draw extra scrutiny.
Consider pulling the changes to this file into a separate PR.

2017-08-24 16:59 UTC, romoore commented on components/Buttons/src/MDCButton.m
> +  return [super pointInside:point withEvent:event];
If we have hitAreaInsets, then we should use those along with our bounds to compute the touch target. If we don't, then we leave it up to our superclass to determine.  I think that's a bit better in terms of class hierarchies since here we won't assume how the default touch target should be calculated.

2017-08-24 17:00 UTC, romoore commented on components/NavigationBar/examples/NavigationBarLayoutExample.m
> -
ok

2017-08-24 17:58 UTC, romoore commented on components/NavigationBar/examples/NavigationBarLayoutExample.m
> -
Done

2017-08-24 17:58 UTC, romoore commented on components/Buttons/src/MDCButton.m
> +      NSLog(@"Button touch target does not meet minimum size guidlines of (48, 48). Button: %@, "
Done

2017-08-24 18:33 UTC, ianegordon approved these changes

2017-08-24 18:34 UTC, ianegordon commented
LGTM. Please merge when Travis is happy.

2017-08-24 22:06 UTC, merged