[FeatureHighlight] Improve text layout
material-components/material-components-ios pull request #1867
Opened 2017-08-21 20:16 UTC by samnm

Added some padding between title and body and increased the line spacing by 1pt.

[Before](https://user-images.githubusercontent.com/1251373/29536462-ea823cec-868b-11e7-8503-12726ac1ee40.png) | [After](https://user-images.githubusercontent.com/1251373/29536468-f0c98402-868b-11e7-9cf7-9beb8d42407d.png)

2017-08-21 20:19 UTC, ajsecord approved these changes

2017-08-22 13:24 UTC, ianegordon requested changes
1pt may be insufficient if Dynamic Type is set to a larger preferred font size.  Talk offline?

2017-08-22 15:16 UTC, samnm commented
Ian, it behaves as expected with Dynamic Type. This adds one extra point of line spacing, it doesn't set line spacing to one point.

2017-08-22 21:06 UTC, ianegordon approved these changes
Acknowledged.

2017-08-22 21:06 UTC, merged