[Themes] New example for custom themes
material-components/material-components-ios pull request #1891
Opened 2017-08-24 02:37 UTC by romoore

Supports Primary and Secondary colors using MDCBasicColorScheme.

![simulator screen shot aug 23 2017 10 33 39 pm](https://user-images.githubusercontent.com/1753199/29646808-97c053f8-8853-11e7-8438-12364db99f5b.png)

2017-08-24 13:45 UTC, ajsecord requested changes
Let's use MDCTextField for this.

2017-08-24 20:11 UTC, willlarche requested changes
@romoore , The issue with the text fields is the space they require. This version of text fields requires 63.5 points for non-floating and 84.5 points for floating heights. 

The simplest solution is to increase the square's width and height to 64 and keep it non-floating.

Though I would implement a tap gesture recognizer and / or textFieldShouldReturn to resign first responder. It's a little maddening at the moment if you want to get the keyboard off the screen.

2017-08-24 22:14 UTC, romoore commented
Awesome, @willlarche,  thanks for investigating!

2017-08-24 23:42 UTC, romoore commented
Added minimum height constraint for both text fields (64pt, keeping non-floating). Added gesture recognizer to resign first responder on both text fields.

2017-08-25 21:27 UTC, willlarche approved these changes

2017-08-25 21:27 UTC, willlarche commented on components/Themes/examples/resources/ThemerCustomSchemePicker.storyboard
> +                                            <constraint firstAttribute="height" relation="greaterThanOrEqual" constant="64" id="VQR-Rf-sMK"/>
Much better. Best would be no height constraint at all.

2017-08-25 21:42 UTC, willlarche approved these changes

2017-08-26 00:09 UTC, merged