[Mutliple components] Update components that use colors to use MDCPalette.
material-components/material-components-ios pull request #2129
Opened 2017-10-07 19:11 UTC by codeman7

All components that use colors now use MDCPalette

Closes #1546

2017-10-08 19:13 UTC, willlarche approved these changes
Thank you!

2017-10-09 00:22 UTC, willlarche commented
Spoke in Discord with you. tl;dr

> You have to add palettes as a dependency in the pod spec too.
> MaterialComponents.podspec
> this section:   s.subspec "CollectionCells" do |ss|

2017-10-09 00:25 UTC, willlarche requested changes
See last comment.

2017-10-09 16:53 UTC, willlarche approved these changes

2017-10-09 16:53 UTC, merged

2017-10-09 21:20 UTC, randallli commented on MaterialComponents.podspec
> +    ss.dependency "MaterialComponents/Palettes"
needs to be added to Activity indicator too.