[Slider]Create default light and dark color schemes for MDCSlider
material-components/material-components-ios pull request #2362
Opened 2017-11-06 18:31 UTC by jmdetloff

2017-11-06 18:39 UTC, randallli requested changes

2017-11-06 18:39 UTC, randallli commented on components/Slider/src/MDCSlider.m
> +- (void)setDisabledColor:(UIColor *)disabledColor {
lets write a unit test for this.

2017-11-06 18:39 UTC, randallli commented on components/Slider/src/MDCSlider.h
> ++ (nonnull MDCBasicColorScheme *)defaultSliderLightColorScheme;
Can we move these into the color themer so the base component doesn't depend on the NDCBasicColorScheme?

2017-11-06 21:27 UTC, jmdetloff commented on components/Slider/src/MDCSlider.m
> +- (void)setDisabledColor:(UIColor *)disabledColor {
Done

2017-11-07 16:36 UTC, randallli approved these changes

2017-11-07 16:36 UTC, randallli commented on components/Slider/src/ColorThemer/MDCSliderColorThemer.m
> +#import "MaterialPalettes.h"
do we need to add a cocoapod dep?

2017-11-07 18:10 UTC, jmdetloff commented on components/Slider/src/ColorThemer/MDCSliderColorThemer.m
> +#import "MaterialPalettes.h"
Added!

2017-11-07 18:12 UTC, merged