[Tabs] Use bottom position when determining the bottom tab bar's height
material-components/material-components-ios pull request #2375
Opened 2017-11-08 17:16 UTC by brianjmoore

Fix for https://github.com/material-components/material-components-ios/issues/2350.

This PR adds missing API that allows clients to determine the preferred height for a tab bar given a position and style, then updates MDCTabBarViewController to use it.

This also fixes a small bug triggered by this change where MDCTabBar wouldn't update its layout at the right times and could leave the item bar with the wrong height.

2017-11-08 17:18 UTC, chuga approved these changes

2017-11-08 17:48 UTC, ianegordon requested changes
Thanks @brianjmoore .  We are waiting for a response from Design on how we should handle this in BottomNavBar.  I expect we want to do the same here.  I'll update as soon as we hear back.

2017-11-08 17:49 UTC, brianjmoore commented
I'm not sure Design should need to get involved. This was 100% a bug in our implementation.

2017-11-08 17:56 UTC, ianegordon approved these changes

2017-11-08 17:57 UTC, ianegordon commented
Caught up offline.  This is unrelated to the portrait -vs- landscape sizing question on BottomAppBar.
Please merge when Travis is happy!

2017-11-09 17:35 UTC, chuga commented
I just re-started the build now that https://github.com/material-components/material-components-ios/pull/2385 has been merged in.

2017-11-09 20:27 UTC, chuga commented
Travis is happy. Merging.

2017-11-09 20:28 UTC, merged