Correct colors for slider default light color scheme
material-components/material-components-ios pull request #2409
Opened 2017-11-13 16:36 UTC by jmdetloff

2017-11-13 21:36 UTC, ianegordon requested changes
Could you drop in a Before / After screenshot?
This will likely break a lot of internal tests, so we want to make sure we have the right rendering.

2017-11-13 21:38 UTC, randallli approved these changes

2017-11-13 21:38 UTC, randallli commented
This only landed in the previous release with the incorrect values.

2017-11-14 23:30 UTC, ianegordon approved these changes

2017-11-14 23:46 UTC, merged

2017-11-14 23:47 UTC, ianegordon commented
Fix for original import.