[kokoro] Add two different simulator runs.
material-components/material-components-ios pull request #2470
Opened 2017-11-17 16:47 UTC by jverkoey

We may eventually want to turn this into a parallelized matrix of jobs, but for now our build times are fast enough that we may be able to get away with a sequence of jobs.

2017-11-17 17:11 UTC, romoore approved these changes
Does it make sense to build for both 32-bit and 64-bit architectures for a 32-bit simulator (iPhone 5)?  Same question goes for the IPad pro, I guess.

2017-11-17 17:11 UTC, romoore commented on .kokoro
> +  # 9.3 was chosen to round out the range of iOS versions we are testing on.
Leave a TODO to update once iOS 10 (11?) support is available?

2017-11-17 17:16 UTC, romoore commented
Looks like an issue parsing the iPad Pro target?

    ./.kokoro-ios-runner/bazel.sh test //components/... --min-xcode-version 8.2.0 -v --ios_minimum_os=8.0 --ios_multi_cpus=i386,x86_64 '--ios_simulator_device=iPad Pro (12.9-inch)' --ios_simulator_version=9.3
    ERROR: no such target '//:Pro': target 'Pro' not declared in package '' 

We may need to wrap it in additional quotes.

2017-11-17 17:27 UTC, jverkoey commented
Yep - there's a bug in the kokoro bazel script as well. Will send out a patch now.

2017-11-17 17:37 UTC, willlarche commented
I'm a little confused. Does this not give us all 4 of the configurations we have in Travis?

2017-11-17 17:38 UTC, jverkoey commented
Xcode 9 still hasn't been deployed to kokoro unfortunately (b/67373848), so we can't add the Xcode 9 targets that we presently have in Travis.

2017-11-17 19:26 UTC, jverkoey commented
This PR is unfortunately blocked for the foreseeable future because it appears that bazel doesn't make use of the `--ios_simulator_device` argument. I believe this is the case because `--ios_simulator_device='iPhjksdfljadslkfasone 5bsdf'` results in a successful test run.

2017-11-17 19:27 UTC, willlarche commented
Since we can't do Xcode 9, let's do ios 8, 9, 10 on xcode 8 with:

smallest 32-bit iphone
largest 64-bit iphone
largest iPad.

2017-11-17 19:29 UTC, willlarche requested changes
See note about 3 requested simulator configs.

2017-12-14 15:21 UTC, romoore commented
Can we close this PR for now and just track it in an issue/feature request for Bazel?

2017-12-14 15:23 UTC, jverkoey commented
Yeah I think that's reasonable.

2017-12-14 15:23 UTC, closed without merging