Add an api to MDCActivityIndicator to allow custom animations
material-components/material-components-ios pull request #2766
Opened 2017-12-22 20:39 UTC by jmdetloff

Allows clients to specify animations that should seamlessly blend into the standard rotation cycle of the MDCActivityIndicator

2017-12-22 20:40 UTC, jmdetloff commented
Hey @ianegordon @randallli Thoughts on this approach? Its a little out there but it does keep from exposing the MDCActivityIndicator internals

2017-12-22 20:50 UTC, ianegordon requested changes
Can you point me at the spec / requirement for this?

I suspect if clients want a custom animation they will want it across all of their Activity Indicators.
@property startAnimation UI_APPEARANCE;
@property stopAnimation UI_APPEARANCE;

Add NSCopying to MDCActivityIndicatorAnimation and add to initWithCoder / encodeWithCoder ?

2017-12-22 21:10 UTC, jmdetloff commented
This is primarily to enable the refresh control, which animates a refresh arrow spinning and then transforming into the indicator stroke, then back into the refresh icon. I'm not sure this api would usually be appropriate app wide, at least for the usage Im imagining. I figure in most places the normal loading spinner would be what people want. Its only in select cases when clients would want a custom animation, ex a pull to refresh spinner, or maybe a transaction spinner that becomes a checkmark after the transaction completes, ect.

2017-12-22 21:40 UTC, randallli approved these changes
lets add an example.

2017-12-22 21:40 UTC, randallli commented on components/ActivityIndicator/src/MDCActivityIndicator.h
> +@property(nonatomic, copy, nonnull) void (^animation)(CGFloat strokeStart, CGFloat strokeEnd);
make a type def for this block def.

2017-12-22 21:40 UTC, randallli commented on components/ActivityIndicator/src/MDCActivityIndicator.m
> +	if (_animating) {
indent

2017-12-22 21:50 UTC, ianegordon commented
Got it.
LGTM.

2017-12-22 21:50 UTC, ianegordon approved these changes

2017-12-22 21:52 UTC, ianegordon commented
Please address Randall's comments and cast the floating point error from Kokoro before merge.

2018-01-03 22:10 UTC, jmdetloff commented
Added an example. Any thoughts before merge @randallli?

2018-01-05 17:05 UTC, merged