[MDCPageControl][MDCBottomAppBarView] Strong/Weak Self references inside block.
material-components/material-components-ios pull request #2942
Opened 2018-02-15 16:06 UTC by mohammadcazig

change strong references to weak references so we don't hold on to the components more than we need too.
#2934

2018-02-15 16:15 UTC, romoore requested changes

2018-02-15 16:15 UTC, romoore commented on components/BottomAppBar/src/MDCBottomAppBarView.m
> +                     [weakSelf insertSubview:weakSelf.floatingButton atIndex:subViewIndex];
I think you would want to strongify here.  Calling `-insertSubview:atIndex:` cannot accept a `nil` view.  Even though I believe the right hand side is evaluated first (leaving the receiver `nil`), it still feels like a risk.

2018-02-15 16:15 UTC, romoore commented on components/PageControl/src/MDCPageControl.m
> +      __weak typeof(self) weakSelf = self;
Can you write a unit test to cover this behavior before/after?

2018-02-15 16:15 UTC, romoore commented on components/PageControl/src/MDCPageControl.m
> +    __weak typeof(self) weakSelf = self;
Please add a unit test for this code as well.

2018-02-16 16:12 UTC, mohammadcazig commented
I feel like this change does not give us a lot of benefits and it might includes some possible risks. So we decided not to make the change.

2018-02-16 16:12 UTC, closed without merging