[Snackbar] custom font and dynamic type support, UI_APPEARANCE support for color theming
material-components/material-components-ios pull request #3090
Opened 2018-03-13 21:35 UTC by yarneo

* Moved `buttonTextColor` and `highlightedTextColor` to `MDCSnackbarMessageView` so they can be set using `UI_APPEARANCE`.
* Renamed and deprecated `snackbarMessageViewTextColor` to `messageTextColor` to better fit naming conventions.
* Added dynamic type support for `buttonFont` and `messageFont` for Snackbars.
* Exposed `mdc_adjustsFontForContentSizeCategory` for dynamic type toggling
* Added DT on/off toggle in the Snackbar simple example.
* Removed redundant code and small bug fixes.

2018-03-13 21:37 UTC, yarneo commented
Screenshots of example using Dynamic Type off/on with Legacy Snackbar off/on
![screen shot 2018-03-13 at 5 37 09 pm](https://user-images.githubusercontent.com/4066863/37371272-327456f8-26e5-11e8-9b12-cd3232a3c2cb.png)
![screen shot 2018-03-13 at 5 37 03 pm](https://user-images.githubusercontent.com/4066863/37371273-327f3ba4-26e5-11e8-9744-422c7c9ea20c.png)
![screen shot 2018-03-13 at 5 36 52 pm](https://user-images.githubusercontent.com/4066863/37371274-3288b8f0-26e5-11e8-8db5-cf7dde780d79.png)
![screen shot 2018-03-13 at 5 36 46 pm](https://user-images.githubusercontent.com/4066863/37371275-329289fc-26e5-11e8-8623-c2f57534f1e6.png)

2018-03-14 16:12 UTC, ianegordon requested changes

2018-03-14 16:12 UTC, ianegordon commented on components/Snackbar/src/MDCSnackbarMessageView.h
> +@property(nonatomic, strong, nullable) UIColor *buttonTextColor UI_APPEARANCE_SELECTOR;
buttonTitleForState:

If you strongly prefer two separate methods, please rename to match UIButton,
buttonTitleColor
highlightedTitleColor

2018-03-14 16:14 UTC, ianegordon commented
Would you add a screenshoot of the example where you change the color of the message and button?

2018-03-14 17:41 UTC, yarneo commented
![fefwefwf](https://user-images.githubusercontent.com/4066863/37420555-6c8fb622-278d-11e8-96d3-6a21b3c68ea2.png)
![screen shot 2018-03-14 at 1 40 36 pm](https://user-images.githubusercontent.com/4066863/37420556-6c9e50a6-278d-11e8-9604-6d78711637be.png)

2018-03-14 17:47 UTC, ianegordon approved these changes

2018-03-15 00:41 UTC, merged