[Buttons] Implement a color themer for an MDCRaisedButton
material-components/material-components-ios pull request #3309
Opened 2018-04-10 13:16 UTC by yarneo

Addition of a unit test, and updated example to use the new themer.

Pivotal: https://www.pivotaltracker.com/story/show/156640797

![simulator screen shot - iphone 8 - 2018-04-10 at 16 13 40](https://user-images.githubusercontent.com/4066863/38558964-6e3534ae-3cda-11e8-9a60-c2b89ce7889b.png)

2018-04-10 13:22 UTC, jverkoey commented on components/Buttons/src/ColorThemer/MDCButtonColorThemer.m
> +                        toRaisedButton:(nonnull MDCRaisedButton *)raisedButton {
minor nit: indentation

2018-04-10 13:22 UTC, romoore requested changes

2018-04-10 13:22 UTC, romoore commented on components/Buttons/src/ColorThemer/MDCButtonColorThemer.h
> + Applies a color scheme to theme to a MDCRaisedButton.
Super-nit: Should be "...an MDCRaisedButton."

2018-04-10 13:22 UTC, romoore commented on components/Buttons/src/ColorThemer/MDCButtonColorThemer.h
> + @param colorScheme The color scheme to apply to MDCRaisedButton.
LINT: Missing `@param` for `raisedButton`
Nit: This comment should be, "...apply to @c raisedButton."

2018-04-10 13:22 UTC, romoore commented on components/Buttons/src/ColorThemer/MDCButtonColorThemer.m
> ++ (void)applySemanticColorScheme:(nonnull id<MDCColorScheming>)colorScheme
Why do we have a specific method for `toRaisedButton:` if there is no such class and it just calls the general themer?

2018-04-10 13:22 UTC, romoore commented on components/Buttons/tests/unit/ButtonsColorThemerTests.m
> +- (void)testMDCRaisedButtonColorThemer {
Nit: The name should probably be something like `-testApplySemanticColorSchemeToRaisedButton`. There is no `MDCRaisedButtonColorThemer` class.

2018-04-10 13:22 UTC, romoore commented on components/Buttons/tests/unit/ButtonsColorThemerTests.m
> +
Please add a few more states and verify that they remain unaffected by the tests.  For example, `UIControlStateSelected | UIControlStateHighlighted`

2018-04-10 13:22 UTC, romoore commented on components/Buttons/tests/unit/ButtonsColorThemerTests.m
> +  XCTAssert(
I believe XCTAssertEqualObjects works with colors just fine as long as the alpha is the same precision (single/double) in both initializer invocations.

2018-04-10 13:25 UTC, romoore commented on components/Buttons/tests/unit/ButtonsColorThemerTests.m
> +  XCTAssertEqual(button.disabledAlpha, 1.f);
Please use XCTAssertEqualWithAccuracy for floating point comparison.

2018-04-11 18:50 UTC, ianegordon commented
Please rebase / fix merge conflicts when addressing @romoore comments.

2018-04-12 08:57 UTC, yarneo commented
some rebase issues, will reopen once ready.

2018-04-12 08:57 UTC, closed without merging