Update MDCTabBar color themer
material-components/material-components-ios pull request #3361
Opened 2018-04-13 20:34 UTC by jmdetloff

https://www.pivotaltracker.com/story/show/156171753

Also fixes crasher within TabBarViewControllerInterfaceBuilderExample

Before:
<img width="376" alt="screen shot 2018-04-13 at 4 29 51 pm" src="https://user-images.githubusercontent.com/1418389/38756680-56e300aa-3f38-11e8-8ab3-c4cae293c689.png">
<img width="376" alt="screen shot 2018-04-13 at 4 29 43 pm" src="https://user-images.githubusercontent.com/1418389/38756681-574887e0-3f38-11e8-99bf-e4993d093a8a.png">
<img width="382" alt="screen shot 2018-04-13 at 4 29 37 pm" src="https://user-images.githubusercontent.com/1418389/38756682-575790aa-3f38-11e8-858e-a44fe1312875.png">
<img width="382" alt="screen shot 2018-04-13 at 4 29 31 pm" src="https://user-images.githubusercontent.com/1418389/38756683-576b5b94-3f38-11e8-9cb6-3f0b7bf49b55.png">
<img width="381" alt="screen shot 2018-04-13 at 4 29 24 pm" src="https://user-images.githubusercontent.com/1418389/38756684-577a85ce-3f38-11e8-96f7-2b5d6a600ff8.png">
<img width="376" alt="screen shot 2018-04-13 at 4 29 06 pm" src="https://user-images.githubusercontent.com/1418389/38756685-57854748-3f38-11e8-9fb9-2ba5c7c9142b.png">
<img width="391" alt="screen shot 2018-04-13 at 4 29 00 pm" src="https://user-images.githubusercontent.com/1418389/38756686-57902276-3f38-11e8-91a6-d34bf054553f.png">
<img width="383" alt="screen shot 2018-04-13 at 4 28 55 pm" src="https://user-images.githubusercontent.com/1418389/38756687-579e0684-3f38-11e8-9f3a-7b335aa0b9c7.png">

After:
<img width="385" alt="screen shot 2018-04-13 at 4 26 52 pm" src="https://user-images.githubusercontent.com/1418389/38756708-6825c8c0-3f38-11e8-9f00-bc5a871cc26b.png">
<img width="389" alt="screen shot 2018-04-13 at 4 26 38 pm" src="https://user-images.githubusercontent.com/1418389/38756709-68338faa-3f38-11e8-89c5-588cba6711f6.png">
<img width="382" alt="screen shot 2018-04-12 at 5 14 06 pm" src="https://user-images.githubusercontent.com/1418389/38756710-68443d46-3f38-11e8-8894-8d11096e0650.png">
<img width="395" alt="screen shot 2018-04-12 at 5 13 47 pm" src="https://user-images.githubusercontent.com/1418389/38756711-68502836-3f38-11e8-8cba-2f492c25042a.png">
<img width="386" alt="screen shot 2018-04-12 at 5 13 37 pm" src="https://user-images.githubusercontent.com/1418389/38756713-685fa5d6-3f38-11e8-868a-5481e1a8d5f1.png">
<img width="385" alt="screen shot 2018-04-12 at 5 13 29 pm" src="https://user-images.githubusercontent.com/1418389/38756714-686a62b4-3f38-11e8-8a36-b4fd948ea00b.png">
<img width="390" alt="screen shot 2018-04-12 at 5 13 22 pm" src="https://user-images.githubusercontent.com/1418389/38756715-6875927e-3f38-11e8-9a9a-5371514156a5.png">
<img width="386" alt="screen shot 2018-04-12 at 5 13 14 pm" src="https://user-images.githubusercontent.com/1418389/38756716-68817f26-3f38-11e8-8d2b-162dda9a6780.png">

2018-04-13 21:05 UTC, jverkoey requested changes
Can you break the crash fix out to a separate PR?

2018-04-13 21:08 UTC, jverkoey submitted a review, later dismissed

2018-04-13 21:08 UTC, jverkoey commented on components/Tabs/examples/BottomNavigationBarExample.m
>    _bottomNavigationBar.inkColor = [UIColor colorWithRed:0 green:0.5f blue:0 alpha:0.15f];
This should go after the themer is applied in case the theme some day sets this value.

2018-04-13 21:08 UTC, jverkoey commented on components/Tabs/examples/TabBarIconExample.m
>    tabBar.inkColor = [[UIColor whiteColor] colorWithAlphaComponent:0.1f];
Move after themer application.

2018-04-13 21:08 UTC, jverkoey commented on components/Tabs/examples/TabBarIconExample.swift
>      tabBar.inkColor = blue
Same here and throughout.

2018-04-16 19:44 UTC, jverkoey approved these changes
Just to confirm: has the crash fix been pulled out to a separate PR?

2018-04-17 18:21 UTC, jmdetloff commented
Yep! Crash fixer landed in #3370

2018-04-17 18:23 UTC, merged