Update README.md
material-components/material-components-ios pull request #3520
Opened 2018-04-26 18:09 UTC by mohammadcazig

Bottom App Bar currently does not support color or typography theming, only FAB and background color is exposed.

2018-04-26 18:16 UTC, romoore requested changes
Can you please add a section about how to theme?

2018-04-27 14:46 UTC, mohammadcazig commented
@jverkoey Can you double check if this description is enough? Also should I mark the current color themer as deprecated ? since it doesn't really match our new scheme mapping.

2018-04-27 14:47 UTC, jverkoey commented
I added a note to the themer with a link to the pivotal story tracking the work to update the themer. You may want to link to the story here as well.

2018-04-27 14:48 UTC, jverkoey commented on components/BottomAppBar/README.md
> +### How to theme
```
### Theming
```

2018-04-27 14:48 UTC, jverkoey commented on components/BottomAppBar/README.md
> +Currently BottomAppBar does not provide sufficient API to theme it properly. Supporting API will be provided soon.
```
BottomAppBar does not support Material Theming yet. Please follow this [tracking issue](https://www.pivotaltracker.com/story/show/157095394) to track progress.
```

2018-04-27 20:55 UTC, jverkoey commented
This was automated by https://github.com/material-components/material-components-ios/pull/3562.

2018-04-27 20:55 UTC, closed without merging