Changing all Raised Button -> Contained Button
material-components/material-components-ios pull request #3564
Opened 2018-04-27 18:27 UTC by mohammadcazig

Pivotal: https://www.pivotaltracker.com/story/show/156403107

Note: I didn't touch the examples that are using MDCRaisedButton. 
We need to update the examples accordingly (pivotal :https://www.pivotaltracker.com/story/show/157119329).

2018-04-27 18:42 UTC, mohammadcazig commented
Randell, could you please verify if this is okay? I was not sure what to do with MDCRaisedButton example.

2018-04-27 20:58 UTC, jverkoey requested changes

2018-04-27 20:58 UTC, jverkoey commented on components/Buttons/README.md
> +let containedButton = MDCRaisedButton()
Need to replace the references to MDCRaisedButton here and throughout.

2018-04-30 17:41 UTC, randallli commented
this may be obsolete with https://github.com/material-components/material-components-ios/pull/3587#pullrequestreview-116371949

2018-04-30 17:42 UTC, randallli requested changes
double check this is still needed with other pr.

2018-04-30 17:44 UTC, closed without merging