[BottomSheet] [3/3] Fix layout issues with bottom sheets containing scroll views
material-components/material-components-ios pull request #4266
Opened 2018-05-24 17:25 UTC by jverkoey

This PR was forked from https://github.com/material-components/material-components-ios/pull/3413. This PR removes the UI tests that were originally included in that PR because the UI tests do not run on our infrastructure without increasing flakiness (this is due to bazel problems, not the PR).

> MDCBottomSheetController had a few subtle issues when the content view controller contained a scroll view.
>
> Contained scroll views always had their height set to the maximum height of the `MDCSheetContainerView`, which might be larger than the contained scroll view's content size.
>
> With this PR, we ensure we make the contained scroll view height the larger of the content height and the preferred height (if we don't set the frame at all, it has whatever random size UIKit assigned to it).

2018-05-24 17:59 UTC, yarneo approved these changes
For future PRs it would be great to have a Dragon in place to see that the bug fix produces the intended behavior, and then also provide screenshots of the before and after to present the fix in action.

2018-05-24 18:03 UTC, jverkoey commented
I can't actually reproduce what this PR is intended to fix. @bhamiltoncx do you have an example that was failing before this PR and is fixed by this PR?

2018-05-24 18:49 UTC, jverkoey commented
Closing this pending more context on the bug that this PR is intended to resolve.

2018-05-24 19:33 UTC, bhamiltoncx commented
@jverkoey: The test case I provided included a repro which fails before the fix and passes after the fix, and the PR description described the scenario in detail.

In particular, `UIScrollViews` were having their height overridden incorrectly when they provided a `contentSize`.

2018-05-29 22:23 UTC, ianegordon requested changes
Can we pull over the test cases from the parent PR?
Assuming everything works as expected LGTM.

2018-05-30 01:01 UTC, jverkoey commented
This PR is blocked pending an updated repro case from @bhamiltoncx re: our offline discussion.

2018-06-06 11:11 UTC, jverkoey commented
Closing pending a repro case.

2018-06-06 11:11 UTC, closed without merging