[Cards] Accessibility - updated interactable example
material-components/material-components-ios pull request #4472
Opened 2018-07-03 14:17 UTC by galiak11

Updating the "Interactable Cards Collection" Dragon example (previously known as: "Collection Card Tinting") to match new Accessibility guidelines detailed in this PR: [`[Cards] Add accessibility documentation`](https://github.com/material-components/material-components-ios/pull/4454/files).

2018-07-03 16:59 UTC, romoore requested changes

2018-07-03 16:59 UTC, romoore commented on components/Cards/examples/CardsCollectionTintingExample.m
> +                                            initWithTitle:@"Interactable"
Formatting/indentation: Colon alignment looks off.

2018-07-03 16:59 UTC, romoore commented on components/Cards/examples/CardsCollectionTintingExample.m
> +  NSString *buttonTitle = _interactable ? @"DEFAULT" : @"INTERACTABLE";
Maybe "static" and "interactive" are better? I feel like "default" and "interactive" are not clear opposites. What do you think?

2018-07-03 16:59 UTC, romoore commented on components/Cards/examples/CardsCollectionTintingExample.m
> +  BOOL _interactable;
Please switch to a property or [mark this as a `@private` iVar](http://google.github.io/styleguide/objcguide.html#instance-variables-in-headers-should-be-protected-or-private)

2018-07-03 16:59 UTC, romoore commented on components/Cards/examples/supplemental/CardTintExampleCell.h
> +- (void)customAccessibilityActionToggleSwitch;
Consider shortening this to something like, `toggleSwitch`?

2018-07-03 16:59 UTC, romoore commented on components/Cards/examples/CardsCollectionTintingExample.m
> +      [[UIAccessibilityCustomAction alloc] initWithName:@"Toggle Switch"
Nit: This should be indented 2 more spaces ([total 4](http://go/objc-style#Spacing_and_Formatting)) for a statement continuation.

2018-07-03 16:59 UTC, romoore commented on components/Cards/examples/CardsCollectionTintingExample.m
> +          target:cell selector:@selector(customAccessibilityActionToggleSwitch)],
Nit: Colons must be aligned, [different lines cannot have different numbers of arguments on them](http://google.github.io/styleguide/objcguide.html#spacing-and-formatting).

2018-07-03 16:59 UTC, romoore commented on components/Cards/examples/CardsCollectionTintingExample.m
> +  return @[ @"Cards", @"Interactable Cards Collection" ];
Let's stick with "interactive" in prose since "interactable" isn't a word.

2018-07-03 16:59 UTC, romoore commented on components/Cards/examples/supplemental/CardTintExampleCell.m
> +    _switchView.accessibilityLabel = @"A switch";
Can we make the switch do something? Same for the slider?

2018-07-03 16:59 UTC, romoore commented on components/Cards/examples/supplemental/CardTintExampleCell.m
> +  return [NSString stringWithFormat:@"%@ cell. Switch is: %@.",
Accessibility label should be a single short label and should not end with a period. Maybe something like, "Selected and switched on" or "Off".  I think `UIAccessibilityTraitSelected` is preferred over a custom label.

2018-07-09 19:48 UTC, closed without merging

2018-07-09 19:49 UTC, galiak11 commented
PR no longer relevant. Replaced by: https://github.com/material-components/material-components-ios/pull/4454/files and https://github.com/material-components/material-components-ios/pull/4488