[TextFields] Update placeholder and outline border color when enabling/disabling text fields with outline controllers
material-components/material-components-ios pull request #4779
Opened 2018-08-13 21:14 UTC by andrewoverton

Closes #4678.

It made sense to make the visual changes to the textfield desired by the client through the controller, because that's how it works with things like error text, through APIs on the controller like `-setErrorText:errorAccessibilityValue:`. However, `enabled` is a property on the TextField, not the controller, and there isn't _normally_ a line of communication _from_ the text field _to_ the controller. Occasionally there are delegates that allow for this, like `MDCTextFieldPositioningDelegate`. From what I could tell my options were either introduce another one or bring KVO of the text field into the controller. I chose the latter...

Also, there was another bug where the underline was visible when a text field with an outline controller was disabled. That's not in the spec. Hiding the underline and not calling `super` in `updateUnderline` was the easiest approach to fixing it. I'm of two minds about it. It feels kind of hacky but it's by far the smallest change.

This gif is of the TextFieldOutlinedExample with the following added to the setup code:
```Objective-C
  self.zipController.normalColor = [UIColor blueColor];
  self.zipController.disabledColor = [UIColor greenColor];
  
  textFieldZip.placeholder = @"placeholder";
  textFieldZip.text = @"text";
  
  dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(2 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
    textFieldZip.enabled = NO;
  });

  dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(4 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
    textFieldZip.enabled = YES;
  });
```

![aug-13-2018 17-11-41](https://user-images.githubusercontent.com/8020010/44058405-02bc0398-9f1c-11e8-8259-2d6ce3518556.gif)

2018-08-14 15:30 UTC, willlarche requested changes
KVO is a path of last resort and has to be discussed at length with TLs to justify. Luckily there's a built in way for the text inputs to report changes to the controller. In the fundament, `setEnabled:` is already overridden. Put in an `NSNotification` broadcast for `UITextFieldTextDidChangeNotification` and `UITextViewTextDidChangeNotification` just like in `clearButtonDidTouch`.

Considering this is the same logic as in `clearButtonDidTouch`, move it a method in the fundament and call it from `clearButtonDidTouch` and `setEnabled:`.

2018-08-14 18:18 UTC, andrewoverton commented
@willlarche I went looking for some kind of UITextField/UITextView notification that I thought might be appropriate but all I saw were TextDidBeginEditing, TextDidEndEditing, and TextDidChange. Since none of those described what was happening, and since our codebase as a whole is pretty KVO friendly compared to others I’ve worked on, I went with KVO. However, I’m happy to observe NSNotifications rather than key-value pairs. Would you be okay with a new NSNotificationName that more accurately describes what’s happening? Like `MDCTextFieldEnabledStateDidChange` or `MDCTextFieldDidToggleEnabled` or something like that?

2018-08-14 18:25 UTC, willlarche commented
Yeah I can buy having a dedicated NSNotification for that if you really don't like didChange for that.

2018-08-14 21:52 UTC, andrewoverton commented
Cool. Yep, I think it's better because the value of `text` isn't actually changing, the value of `enabled` is. But I'm also totally going off the assumption that Apple doesn't use `TextDidChange` to convey changes in things other than text haha, maybe they do?

2018-08-14 21:55 UTC, willlarche commented
I think you're right. I don't think they do.

2018-08-15 20:06 UTC, material-automation commented
## API diff detected the following changes

### TextFields

#### MDCTextInputDidToggleEnabled

*new* constant: `MDCTextInputDidToggleEnabled`

<!-- identifier: apidiff -->

2018-08-15 20:21 UTC, willlarche commented on components/TextFields/src/MDCTextField.h
> +extern NSString *_Nonnull const MDCTextInputDidToggleEnabled;
The other notifications end in `Notification`. Ask @ianegordon if he'd like to continue that paradigm.

2018-08-15 20:21 UTC, willlarche approved these changes
Approved with one comment on naming for the TL to answer.

2018-08-15 20:44 UTC, andrewoverton commented on components/TextFields/src/MDCTextField.h
> +extern NSString *_Nonnull const MDCTextInputDidToggleEnabled;
Ahhh he can chime in but honestly it should have `Notification` at the end, I'll add it. I might also change `TextInput` to `TextField`. That one was intentional but I don't know...

2018-08-15 20:46 UTC, willlarche commented on components/TextFields/src/MDCTextField.h
> +extern NSString *_Nonnull const MDCTextInputDidToggleEnabled;
I'd keep input because the `enabled` property comes from the `MDCTextInput` protocol. It's in the multiline version too.

2018-08-16 13:51 UTC, merged