[ShadowLayer] Setting the corner radius should recalculate shadowPath
material-components/material-components-ios pull request #4804
Opened 2018-08-15 15:26 UTC by ianegordon

2018-08-15 16:22 UTC, romoore requested changes
Could we add a dragon for this? Is the bug visible in any of our current examples?

2018-08-16 15:49 UTC, ianegordon commented
TODO to add a dragon #4813.
I'd like to land before release.

2018-08-16 15:51 UTC, randallli approved these changes

2018-08-16 15:53 UTC, merged

2018-08-16 16:10 UTC, romoore commented
Good to know we're allowed to merge with a blocking review.