[List, TextFields] Fix imports
material-components/material-components-ios pull request #5420
Opened 2018-10-15 16:50 UTC by galiak11

Internal imports were breaking because now that Chips depends on
internal TextFields code the include path was not finding the correct
Text Fields files. This would be made obsolete by #5360, but is
necessary for now.

Related to #5360, related to #5343

2018-10-15 16:52 UTC, material-automation commented on components/TextFields/src/private/MDCTextInputCommonFundament.m
>  #import "MDCTextInputCommonFundament.h"
clang-format suggested the following change:


```
-#import "MDCTextInputArt.h"
-#import "MDCTextInputCommonFundament.h"
```

<!-- identifier: clang-format -->
<!-- File: components/TextFields/src/private/MDCTextInputCommonFundament.m -->

2018-10-15 16:52 UTC, material-automation commented on components/TextFields/src/private/MDCTextInputCommonFundament.m
> +#import "../MDCTextField.h"
clang-format suggested the following change:


```
+#import "../MDCTextInput.h"
```

<!-- identifier: clang-format -->
<!-- File: components/TextFields/src/private/MDCTextInputCommonFundament.m -->

2018-10-15 16:52 UTC, material-automation commented on components/TextFields/src/private/MDCTextInputCommonFundament.m
> +#import "../MDCTextInput.h"
clang-format suggested the following change:


```
-#import "../MDCTextInput.h"
+#import "MDCTextInputArt.h"
+#import "MDCTextInputCommonFundament.h"
```

<!-- identifier: clang-format -->
<!-- File: components/TextFields/src/private/MDCTextInputCommonFundament.m -->

2018-10-15 16:52 UTC, material-automation commented on components/List/examples/MDCSelfSizingStereoCellExample.m
> +#import "MaterialList.h"
clang-format suggested the following change:


```
-#import "MaterialList.h"
```

<!-- identifier: clang-format -->
<!-- File: components/List/examples/MDCSelfSizingStereoCellExample.m -->

2018-10-15 16:52 UTC, material-automation commented on components/List/examples/MDCSelfSizingStereoCellExample.m
>  #import "MaterialList+ColorThemer.h"
clang-format suggested the following change:


```
+#import "MaterialList.h"
```

<!-- identifier: clang-format -->
<!-- File: components/List/examples/MDCSelfSizingStereoCellExample.m -->

2018-10-15 16:52 UTC, material-automation commented
clang-format recommended changes.

Consider installing [git-clang-format](https://github.com/llvm-mirror/clang/blob/master/tools/clang-format/git-clang-format) and running the following command:

```bash
git clang-format $(git merge-base origin/develop HEAD)
```

<!-- identifier: clang-format -->

2018-10-15 16:57 UTC, andrewoverton approved these changes
LGTM after clang format fixes

2018-10-16 15:21 UTC, romoore commented
This change should no longer be needed after #5425 and #5426.

2018-10-16 15:21 UTC, romoore requested changes
I believe this PR is now obsolete.

2018-11-05 14:44 UTC, jverkoey commented
Closing this PR. Please re-open if we still intend to pursue it.

2018-11-05 14:44 UTC, closed without merging