[ActionSheet] Allow changing action item accessibility labels.
material-components/material-components-ios pull request #5803
Opened 2018-11-20 17:57 UTC by lightboys22

i.e.: We need to show the title as "Resume". But the voice over message should be "Résumé" instead of "Rezoom".

### Thanks for starting a pull request on Material Components!

#### Don't forget:
- [ ] Identify the component the PR relates to in brackets in the title. ```[Buttons] Updated documentation```
- [ ] Link to GitHub issues it solves. ```closes #1234```
- [ ] Sign the CLA bot. You can do this once the pull request is opened.

[Contributing](./contributing/README.md#pull-requests) has more information and tips for a great
pull request.

2018-11-20 19:33 UTC, romoore requested changes
This change seems reasonable. Would you please add unit tests for these changes?

2018-11-20 23:06 UTC, lightboys22 commented
I signed it!

2018-11-26 21:47 UTC, lightboys22 commented
@romoore I added an unit test. Is there anything else I missed?

2018-11-27 15:19 UTC, romoore approved these changes
Looks good, minor bug fix (I think) on the test helper.

2018-11-27 15:19 UTC, romoore commented on components/ActionSheet/tests/unit/MDCActionSheetTestHelper.m
> +    NSIndexPath *indexPath = [NSIndexPath indexPathForRow:0 inSection:0];
Should this be `indexPathForRow:index` instead of `indexPathForRow:0`?

2018-11-27 15:19 UTC, romoore commented on components/ActionSheet/tests/unit/MDCActionSheetTableCellTest.m
> +  // Then
Nit: Please add a newline before the `// Then` comment.

2018-11-27 15:19 UTC, romoore commented
Sorry for the delay, @lightboys22 . I must have missed the email from cla-bot.

2018-11-28 14:41 UTC, romoore approved these changes

2018-11-28 14:41 UTC, romoore commented on components/ActionSheet/tests/unit/MDCActionSheetTableCellTest.m
> +  // Then
Done

2018-11-28 14:41 UTC, romoore commented on components/ActionSheet/tests/unit/MDCActionSheetTestHelper.m
> +    NSIndexPath *indexPath = [NSIndexPath indexPathForRow:0 inSection:0];
Done

2018-12-05 14:44 UTC, codeman7 commented
Hey @lightboys22 the team and I truly appreciate you helping out with this! So the failures are due to comparing a NSInteger and NSUInteger. I got it to pass if you do the following changes.
```diff
// Within MDCActionSheetTestHelper.h
- + (MDCActionSheetItemTableViewCell *)getCellFromActionSheet:(MDCActionSheetController *)actionSheet
                                                    atIndex:(NSInteger)index;
+ + (MDCActionSheetItemTableViewCell *)getCellFromActionSheet:(MDCActionSheetController *)actionSheet
                                                    atIndex:(NSUInteger)index;
```

```diff
// Within MDCActionSheetTestHelper.m
- + (MDCActionSheetItemTableViewCell *)getCellFromActionSheet:(MDCActionSheetController *)actionSheet
                                                    atIndex:(NSUInteger)index {
}

+ + (MDCActionSheetItemTableViewCell *)getCellFromActionSheet:(MDCActionSheetController *)actionSheet
                                                    atIndex:(NSUInteger)index {
}
```

That will pass our CI but the test will still fail. Additionally you will need to add:
```diff
// Within MDCActionSheetController.m
 (id)copyWithZone:(__unused NSZone *)zone {
  MDCActionSheetAction *action = [[self class] actionWithTitle:self.title
                                                         image:self.image
                                                       handler:self.completionHandler];
+  action.accessibilityIdentifier = self.accessibilityIdentifier;
  action.accessibilityLabel = self.accessibilityLabel;
  return action;
}
```
I believe with those changes we will be able to merge, again thank you for your contribution!

2018-12-05 14:44 UTC, codeman7 approved these changes

2018-12-06 17:52 UTC, merged