[Collections] Add delegate method to send updates on the swiping location during the swipe
material-components/material-components-ios pull request #6260
Opened 2019-01-09 16:42 UTC by randallli

[Collections] Add delegate method to send updates on the swiping location during the swipe

2019-01-09 16:49 UTC, material-automation commented on components/Collections/src/MDCCollectionViewEditingDelegate.h
> +    atLocation:(CGPoint)location;
clang-format suggested the following change:


```
-    atLocation:(CGPoint)location;
+                          atLocation:(CGPoint)location;
```

<!-- identifier: clang-format -->
<!-- File: components/Collections/src/MDCCollectionViewEditingDelegate.h -->

2019-01-09 16:49 UTC, material-automation commented on components/Collections/src/private/MDCCollectionViewEditor.m
> +                                 atLocation:location];
clang-format suggested the following change:


```
-                                 atLocation:location];
+                                  atLocation:location];
```

<!-- identifier: clang-format -->
<!-- File: components/Collections/src/private/MDCCollectionViewEditor.m -->

2019-01-09 16:49 UTC, material-automation commented
clang-format recommended changes.

Consider installing [git-clang-format](https://github.com/llvm-mirror/clang/blob/master/tools/clang-format/git-clang-format) and running the following command:

```bash
git clang-format $(git merge-base origin/develop HEAD)
```

<!-- identifier: clang-format -->

2019-01-09 16:51 UTC, material-automation commented
bazel detected changes to the following targets:

```
//components/Collections:unit_tests
//components/Collections:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/Collections:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/Collections:unit_tests_IPHONE_5_IN_8_1
//components/Collections:unit_tests_IPHONE_5_IN_8_1_test_bundle
//components/Collections:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/Collections:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/Collections:unit_tests_IPHONE_X_IN_11_0
//components/Collections:unit_tests_IPHONE_X_IN_11_0_test_bundle
```

<!-- identifier: affected-targets -->

2019-01-09 18:15 UTC, material-automation commented
## API diff detected the following changes

### Collections

#### MDCCollectionViewEditingDelegate

*new* method: `-collectionView:didSwipeToDismissItemAtIndexPath:atLocation:` in `MDCCollectionViewEditingDelegate`

<!-- identifier: apidiff -->

2019-01-14 15:29 UTC, romoore requested changes

2019-01-14 15:29 UTC, romoore commented on components/Collections/src/MDCCollectionViewEditingDelegate.h
> +    didSwipeToDismissItemAtIndexPath:(nonnull NSIndexPath *)indexPath
The name (`didSwipe...`) and the documentation ("is being swiped") doesn't seem to match.  I think the documentation or the method name should be fixed to be in agreement.  From the code, it looks like this is an ongoing action.  In that case, I would suggest two changes:

* Change the name to something like `swipeGestureWasContinued`
* Remark in the documentation that due to the frequent nature of this callback, any client code should either be *very* efficient or should be dispatched off of the main thread.

What do you think?

2019-02-27 20:16 UTC, jverkoey commented
Hi @randallli; are you still working on this PR? It hasn't had any activity in quite some time. Please close it if you are not intending to pursue it in the immediate future; you can re-open it if/when you work on it again.

2019-04-01 22:58 UTC, jverkoey commented
Closing this PR due to inactivity and unresolved comments. Please re-open it if you intend to pursue it.

2019-04-01 22:58 UTC, closed without merging