[Tabs] Add willDisplayItem/didEndDisplayingItem methods to MDCTabBar.
material-components/material-components-ios pull request #6276
Opened 2019-01-10 19:38 UTC by mrhappyasthma

This is useful for notifying the users of when near UITabBarItems will
be (or did stop being) displayed. Users can then take actions such as
logging impressions of new tabs.

### Thanks for starting a pull request on Material Components!

#### Don't forget:
- [ ] Identify the component the PR relates to in brackets in the title. ```[Buttons] Updated documentation```
- [] Link to GitHub issues it solves. ```closes #1234```
- [ ] Sign the CLA bot. You can do this once the pull request is opened.

[Contributing](./contributing/README.md#pull-requests) has more information and tips for a great
pull request.

2019-01-10 19:39 UTC, mrhappyasthma commented
closes #6275

2019-01-10 19:56 UTC, romoore commented
Thanks, for the PR. I feel like integrating this behavior so tightly into MDCTabBar is very implementation-specific.  

Is there a way to unblock you from writing your own subclass that has this behavior?  Does MDCTabBarController require some refactoring work to allow you to write this API in your client code?

2019-01-10 19:58 UTC, material-automation commented on components/Tabs/src/private/MDCItemBar.m
> +    forItemAtIndexPath:(NSIndexPath *)indexPath {
clang-format suggested the following change:


```
-  didEndDisplayingCell:(UICollectionViewCell *)cell
-    forItemAtIndexPath:(NSIndexPath *)indexPath {
+    didEndDisplayingCell:(UICollectionViewCell *)cell
+      forItemAtIndexPath:(NSIndexPath *)indexPath {
```

<!-- identifier: clang-format -->
<!-- File: components/Tabs/src/private/MDCItemBar.m -->

2019-01-10 19:58 UTC, material-automation commented
clang-format recommended changes.

Consider installing [git-clang-format](https://github.com/llvm-mirror/clang/blob/master/tools/clang-format/git-clang-format) and running the following command:

```bash
git clang-format $(git merge-base origin/develop HEAD)
```

<!-- identifier: clang-format -->

2019-01-10 20:03 UTC, material-automation commented
bazel detected changes to the following targets:

```
//components/Tabs:unit_tests
//components/Tabs:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/Tabs:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/Tabs:unit_tests_IPHONE_5_IN_8_1
//components/Tabs:unit_tests_IPHONE_5_IN_8_1_test_bundle
//components/Tabs:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/Tabs:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/Tabs:unit_tests_IPHONE_X_IN_11_0
//components/Tabs:unit_tests_IPHONE_X_IN_11_0_test_bundle
```

<!-- identifier: affected-targets -->

2019-01-10 20:03 UTC, material-automation commented
## API diff detected the following changes

### Tabs

#### MDCTabBarDelegate

*new* method: `-tabBar:didEndDisplayingItem:atIndex:` in `MDCTabBarDelegate`

*new* method: `-tabBar:willDisplayItem:atIndex:` in `MDCTabBarDelegate`

<!-- identifier: apidiff -->

2019-01-11 13:58 UTC, romoore commented
@mrhappyasthma and I will be having an offline discussion today to determine the best way to support this behavior within client code.

2019-01-30 14:07 UTC, jverkoey commented
@romoore What was the result of the offline discussion?

2019-01-30 14:13 UTC, romoore commented
@jverkoey The results of the conversation were included in [the related bug for this issue](https://github.com/material-components/material-components-ios/issues/6275).

2019-01-30 14:16 UTC, jverkoey commented
Awesome. Can/should we close this PR then until we're ready to push it forward again?

2019-01-30 14:54 UTC, jverkoey requested changes
Marking as changes requested so that this PR is removed from our review queue. Please dismiss my feedback if/when this PR is ready to pursue again.

2019-02-27 18:03 UTC, romoore commented
Closing this because the investigation work (see https://github.com/material-components/material-components-ios/issues/6275) needs to be done before we can decide on an API and implementation.

2019-02-27 18:03 UTC, closed without merging