Move the clipsToBounds behavior from MDCTabBar to MDCItemBar
material-components/material-components-ios pull request #6449
Opened 2019-01-23 01:50 UTC by mrhappyasthma

The primary benefit here is that it allows the user to add a shadow to the CALayer of MDCTabBar without it getting clipped to bounds. (Where as setting `.clipsToBounds=NO` on MDCTabBar then the underlying itemBar/collectionView will extend outside of the bounds of the parent.)

By moving this clipsToBounds up a layer, it allows both of these behaviors to work.

For example:

- Adding a shadow to tabs: https://i.imgur.com/2CY15ip.png

- Tabs extending out of bounds if attempting to set MDCTabBar clipsToBounds=NO as it exists today: https://i.imgur.com/YYfkIMq.png
- Tabs fixed when setting MDCTabBar clipsToBounds=NO with this change: https://i.imgur.com/7QJhFBx.png

### Thanks for starting a pull request on Material Components!

#### Don't forget:
- [ ] Identify the component the PR relates to in brackets in the title. ```[Buttons] Updated documentation```
- [ ] Link to GitHub issues it solves. ```closes #1234```
- [ ] Sign the CLA bot. You can do this once the pull request is opened.

[Contributing](./contributing/README.md#pull-requests) has more information and tips for a great
pull request.

2019-01-23 01:52 UTC, material-automation commented on components/Tabs/src/private/MDCItemBar.m
> +  self.clipsToBounds=YES;
clang-format suggested the following change:


```
-  self.clipsToBounds=YES;
+  self.clipsToBounds = YES;
```

<!-- identifier: clang-format -->
<!-- File: components/Tabs/src/private/MDCItemBar.m -->

2019-01-23 01:52 UTC, material-automation commented
clang-format recommended changes.

Consider installing [git-clang-format](https://github.com/llvm-mirror/clang/blob/master/tools/clang-format/git-clang-format) and running the following command:

```bash
git clang-format $(git merge-base origin/develop HEAD)
```

<!-- identifier: clang-format -->

2019-01-23 01:52 UTC, material-automation commented
bazel detected changes to the following targets:

```
//components/Tabs:unit_tests
//components/Tabs:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/Tabs:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/Tabs:unit_tests_IPHONE_5_IN_8_1
//components/Tabs:unit_tests_IPHONE_5_IN_8_1_test_bundle
//components/Tabs:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/Tabs:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/Tabs:unit_tests_IPHONE_X_IN_11_0
//components/Tabs:unit_tests_IPHONE_X_IN_11_0_test_bundle
```

<!-- identifier: affected-targets -->

2019-01-23 13:59 UTC, romoore commented
I'm a little concerned about this change. It looks like it's motivated by a desire to "nest" Tabs within one another and provide separation. This is already called-out in the [Material Guidelines article for Tabs](https://material.io/design/components/tabs.html#placement) as a "caution", so I'm wary of making support explicit.

My other concern is that you're adding a shadow below the Tabs themselves. From all of the design mocks I'm seeing in the article, it seems that providing an optional hairline/divider at the bottom edge of the Tabs might be acceptable, but the only shadows/elevation I see are from the AppBars containing the Tabs. Double-checking with a designer, only the "Primary variant" (where the Tabs surface is colored with the Theme's `primaryColor`) has elevation (4 dp). The example you're providing using `surfaceColor` has an elevation of 0.

Although I think shadow support should be added to Tabs, it should be added via an elevation API similar to our other components. Adding an `elevation` property of type `MDCShadowElevation` is probably the best way forward.

2019-01-30 15:04 UTC, jverkoey requested changes
Marking as changes requested due to @romoore's concerns.

2019-02-27 18:02 UTC, romoore commented
I'm closing this PR for now. Based on feedback from Design, I think we have a good reason to support a hairline separator between "layered" Tabs. My understanding is that Tabs shouldn't have shadows.

2019-02-27 18:02 UTC, closed without merging