[Shape] Add NSCopying to MDCShapeScheme
material-components/material-components-ios pull request #6507
Opened 2019-01-29 15:25 UTC by codeman7

## Related links
* Original PR: #5929 
* Original bug: #5880 
* Scheme: [`MDCShapeScheme`](https://github.com/material-components/material-components-ios/tree/develop/components/schemes/Shape)

## Introduction
This was originally done in #5929 but that was closed. This change adds `copy` to `MDCShapeScheme`. The original PR added this to `MDCShapeScheme` this is a proposal to add it to the protocol `MDCShapeScheming` so if a client implements `MDCShapeScheming` or `MDCContainerScheming` they can then `copy` it.

## The problem
NSCopy was never added to MDCShapeScheme and we may need to copy a shape scheme within a container scheme.

## The fix
Add `NSCopying` to `MDCShapeScheming`.

## Additional notes
I have attached everyone to review so this can be where we discuss this proposal.

2019-01-29 15:28 UTC, material-automation commented
bazel detected changes to the following targets:

```
//components/ActionSheet:unit_tests
//components/ActionSheet:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/ActionSheet:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/ActionSheet:unit_tests_IPHONE_5_IN_8_1
//components/ActionSheet:unit_tests_IPHONE_5_IN_8_1_test_bundle
//components/ActionSheet:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/ActionSheet:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/ActionSheet:unit_tests_IPHONE_X_IN_11_0
//components/ActionSheet:unit_tests_IPHONE_X_IN_11_0_test_bundle
//components/BottomSheet:unit_tests
//components/BottomSheet:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/BottomSheet:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/BottomSheet:unit_tests_IPHONE_5_IN_8_1
//components/BottomSheet:unit_tests_IPHONE_5_IN_8_1_test_bundle
//components/BottomSheet:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/BottomSheet:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/BottomSheet:unit_tests_IPHONE_X_IN_11_0
//components/BottomSheet:unit_tests_IPHONE_X_IN_11_0_test_bundle
//components/ButtonBar:unit_tests
//components/ButtonBar:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/ButtonBar:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/ButtonBar:unit_tests_IPHONE_5_IN_8_1
//components/ButtonBar:unit_tests_IPHONE_5_IN_8_1_test_bundle
//components/ButtonBar:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/ButtonBar:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/ButtonBar:unit_tests_IPHONE_X_IN_11_0
//components/ButtonBar:unit_tests_IPHONE_X_IN_11_0_test_bundle
//components/Buttons:unit_tests
//components/Buttons:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/Buttons:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/Buttons:unit_tests_IPHONE_5_IN_8_1
//components/Buttons:unit_tests_IPHONE_5_IN_8_1_test_bundle
//components/Buttons:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/Buttons:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/Buttons:unit_tests_IPHONE_X_IN_11_0
//components/Buttons:unit_tests_IPHONE_X_IN_11_0_test_bundle
//components/Cards:snapshot_tests
//components/Cards:snapshot_tests_test_bundle
//components/Cards:unit_tests
//components/Cards:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/Cards:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/Cards:unit_tests_IPHONE_5_IN_8_1
//components/Cards:unit_tests_IPHONE_5_IN_8_1_test_bundle
//components/Cards:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/Cards:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/Cards:unit_tests_IPHONE_X_IN_11_0
//components/Cards:unit_tests_IPHONE_X_IN_11_0_test_bundle
//components/Chips:snapshot_tests
//components/Chips:snapshot_tests_test_bundle
//components/Chips:unit_tests
//components/Chips:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/Chips:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/Chips:unit_tests_IPHONE_5_IN_8_1
//components/Chips:unit_tests_IPHONE_5_IN_8_1_test_bundle
//components/Chips:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/Chips:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/Chips:unit_tests_IPHONE_X_IN_11_0
//components/Chips:unit_tests_IPHONE_X_IN_11_0_test_bundle
//components/Dialogs:unit_tests
//components/Dialogs:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/Dialogs:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/Dialogs:unit_tests_IPHONE_5_IN_8_1
//components/Dialogs:unit_tests_IPHONE_5_IN_8_1_test_bundle
//components/Dialogs:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/Dialogs:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/Dialogs:unit_tests_IPHONE_X_IN_11_0
//components/Dialogs:unit_tests_IPHONE_X_IN_11_0_test_bundle
//components/schemes/Container:unit_tests
//components/schemes/Container:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/schemes/Container:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/schemes/Container:unit_tests_IPHONE_5_IN_8_1
//components/schemes/Container:unit_tests_IPHONE_5_IN_8_1_test_bundle
//components/schemes/Container:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/schemes/Container:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/schemes/Container:unit_tests_IPHONE_X_IN_11_0
//components/schemes/Container:unit_tests_IPHONE_X_IN_11_0_test_bundle
//components/schemes/Shape:unit_tests
//components/schemes/Shape:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/schemes/Shape:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/schemes/Shape:unit_tests_IPHONE_5_IN_8_1
//components/schemes/Shape:unit_tests_IPHONE_5_IN_8_1_test_bundle
//components/schemes/Shape:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/schemes/Shape:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/schemes/Shape:unit_tests_IPHONE_X_IN_11_0
//components/schemes/Shape:unit_tests_IPHONE_X_IN_11_0_test_bundle
```

<!-- identifier: affected-targets -->

2019-01-29 15:28 UTC, jverkoey commented on components/schemes/Shape/src/MDCShapeScheme.m
> +}
Do we need to add `hash` and `isEqual:`?

2019-01-29 15:31 UTC, romoore commented on components/schemes/Shape/src/MDCShapeScheme.m
> +}
+1 Let's move this to another PR and only once it's required.

2019-01-29 15:32 UTC, material-automation commented
## API diff detected the following changes

### ShapeScheme

#### MDCShapeScheming

*modified* protocol: `MDCShapeScheming`

| Type of change: | Swift declaration |
|---|---|
| From: | `protocol MDCShapeScheming` |
| To: | `protocol MDCShapeScheming : NSCopying` |

*modified* protocol: `MDCShapeScheming`

| Type of change: | Declaration |
|---|---|
| From: | `@protocol MDCShapeScheming` |
| To: | `@protocol MDCShapeScheming <NSCopying>` |

<!-- identifier: apidiff -->

2019-01-29 15:34 UTC, codeman7 commented on components/schemes/Shape/src/MDCShapeScheme.m
> +}
Sorry I forgot to push the latest commit. This has been updated.

2019-01-29 19:17 UTC, romoore approved these changes

2019-01-29 20:51 UTC, jverkoey approved these changes

2019-01-30 16:23 UTC, jverkoey requested changes
Conversation offline is revealing that there may not be a clear client need for this, so I'd like to place it on hold until it's clear we have a business use case for it.

2019-01-31 15:55 UTC, closed without merging