[ActionSheet] Add ActionSheet theming extension test targets to app schemes
material-components/material-components-ios pull request #6702
Opened 2019-02-22 16:05 UTC by andrewoverton

I noticed that several ActionSheet theming extension unit test targets weren't being included in the Dragons/Catalog schemes, and when i tried to add them it wouldn't compile, but i fixed it by using Rob's new MaterialComponentsTestingSupport podspec.

Closes #6701.

2019-02-22 16:06 UTC, romoore reviewed
Bazel?

2019-02-22 16:07 UTC, material-automation commented
The following files are not in any BUILD targets:

```
components/ActionSheet/tests/support/MDCActionSheetTestHelper.h
components/ActionSheet/tests/support/MDCActionSheetTestHelper.m
```


<!-- identifier: bazel-rule-coverage -->

2019-02-22 16:08 UTC, material-automation commented
bazel detected changes to the following targets:

```
//components/ActionSheet:unit_test_themer_sources
//components/ActionSheet:unit_test_theming_sources
```

<!-- identifier: affected-targets -->

2019-02-22 16:25 UTC, romoore requested changes
Please add the new target's umbrella header, `MaterialActionSheet+TestingSupport.h`

2019-02-22 16:25 UTC, romoore commented on components/ActionSheet/BUILD
> +    name = "unit_test_helpers",
Please name this "TestingSupport" so that our `.kokoro` rewrite scripts will work for it as well.

2019-02-22 16:25 UTC, romoore commented on components/ActionSheet/BUILD
> +        "UIKit",
Tip: Nit: UIKit isn't required for iOS targets.

2019-02-22 16:25 UTC, romoore commented on components/ActionSheet/tests/unit/ActionSheetThemer/MDCActionSheetThemeTest.m
> +#import "../../support/MDCActionSheetTestHelper.h"
Please use `#import <MaterialComponentsTestingSupport/MaterialActionSheet+TestingSupport.h>`

2019-02-22 17:06 UTC, material-automation commented
## API diff detected the following changes

### ActionSheet+TestingSupport

**New extension.**

<!-- identifier: apidiff -->

2019-02-22 17:13 UTC, jverkoey approved these changes

2019-02-22 17:45 UTC, romoore approved these changes

2019-02-22 17:48 UTC, codeman7 approved these changes

2019-02-22 21:44 UTC, material-automation commented on components/ActionSheet/tests/unit/MDCActionSheetTest.m
>  #import "MDCActionSheetTestHelper.h"
clang-format suggested the following change:


```
-#import "MDCActionSheetTestHelper.h"
```

<!-- identifier: clang-format -->
<!-- File: components/ActionSheet/tests/unit/MDCActionSheetTest.m -->

2019-02-22 21:44 UTC, material-automation commented on components/ActionSheet/tests/unit/MDCActionSheetTest.m
>  #import "MDCActionSheetTestHelper.h"
clang-format suggested the following change:


```
+#import "MDCActionSheetTestHelper.h"
```

<!-- identifier: clang-format -->
<!-- File: components/ActionSheet/tests/unit/MDCActionSheetTest.m -->

2019-02-22 21:44 UTC, material-automation commented on components/ActionSheet/tests/unit/ActionSheetThemer/MDCActionSheetThemeTest.m
> +#import "../../support/MDCActionSheetTestHelper.h"
clang-format suggested the following change:


```
-#import "../../support/MDCActionSheetTestHelper.h"
```

<!-- identifier: clang-format -->
<!-- File: components/ActionSheet/tests/unit/ActionSheetThemer/MDCActionSheetThemeTest.m -->

2019-02-22 21:44 UTC, material-automation commented on components/ActionSheet/tests/unit/ActionSheetThemer/MDCActionSheetThemeTest.m
>  #import "../../../src/private/MDCActionSheetHeaderView.h"
clang-format suggested the following change:


```
+#import "../../support/MDCActionSheetTestHelper.h"
```

<!-- identifier: clang-format -->
<!-- File: components/ActionSheet/tests/unit/ActionSheetThemer/MDCActionSheetThemeTest.m -->

2019-02-22 21:44 UTC, material-automation commented on components/ActionSheet/tests/unit/MDCActionSheetTableCellTest.m
> +#import "../support/MDCActionSheetTestHelper.h"
clang-format suggested the following change:


```
-#import "../support/MDCActionSheetTestHelper.h"
```

<!-- identifier: clang-format -->
<!-- File: components/ActionSheet/tests/unit/MDCActionSheetTableCellTest.m -->

2019-02-22 21:44 UTC, material-automation commented on components/ActionSheet/tests/unit/MDCActionSheetTableCellTest.m
> +#import "../support/MDCActionSheetTestHelper.h"
clang-format suggested the following change:


```
+#import "../support/MDCActionSheetTestHelper.h"
```

<!-- identifier: clang-format -->
<!-- File: components/ActionSheet/tests/unit/MDCActionSheetTableCellTest.m -->

2019-02-22 21:44 UTC, material-automation commented on components/ActionSheet/tests/unit/Theming/MDCActionSheetThemingTest.m
> +#import "../../support/MDCActionSheetTestHelper.h"
clang-format suggested the following change:


```
-#import "../../support/MDCActionSheetTestHelper.h"
```

<!-- identifier: clang-format -->
<!-- File: components/ActionSheet/tests/unit/Theming/MDCActionSheetThemingTest.m -->

2019-02-22 21:44 UTC, material-automation commented on components/ActionSheet/tests/unit/Theming/MDCActionSheetThemingTest.m
> +#import "../../../src/private/MDCActionSheetHeaderView.h"
clang-format suggested the following change:


```
+#import "../../support/MDCActionSheetTestHelper.h"
```

<!-- identifier: clang-format -->
<!-- File: components/ActionSheet/tests/unit/Theming/MDCActionSheetThemingTest.m -->

2019-02-22 21:44 UTC, material-automation commented
clang-format recommended changes.

Consider installing [git-clang-format](https://github.com/llvm-mirror/clang/blob/master/tools/clang-format/git-clang-format) and running the following command:

```bash
git clang-format $(git merge-base origin/develop HEAD)
```

<!-- identifier: clang-format -->

2019-02-26 20:16 UTC, andrewoverton commented
Closing this--will address after https://github.com/material-components/material-components-ios/issues/6712

2019-02-26 20:16 UTC, closed without merging