[States] New Color Resource class for the State System
material-components/material-components-ios pull request #6709
Opened 2019-02-25 20:07 UTC by galiak11

### Material State Scheme

This is an experimental implementation of a State System. 

This PR adds the ColorResource class (#4), which is one part of the following complete list of a State Scheme implementation (See PR: #6585 for a complete implementation).

1. Storing state related information outside of themers, in a dedicated data source (StateScheme). This will allow sharing state information across components/themers.
2. Storing state data in a dictionary, which can be serialized and/or shared with external systems (in the future).  The StateScheme exposes getters and setters to access the private state information that is in this dictionary.
3. Using a ColorResource class to represent colors in the State Scheme (more about this below).
4. Colors that don't pass contrast ratio can be overridden and customized by clients, who can pick  specific colors that work with their color schemes.  This concept is demonstrated in the StateScheme initializer. 

### Color Resources

The Color Resource class is a concept borrowed from Android's Resources, which are being used heavily in its theming implementation. In this implementation, Color Resources represent colors in different formats, including Material formats (semantic or palette colors) or platform formats (expressed as hex values).

The StateScheme, which manages all state-related data in a single (private) dictionary, uses ColorResources in its getters and setters to expose its private state-color information. ColorResources are useful for string data serialization. Colors, stored as strings in a dictionary are converted to a structured and validated color format that can be reliably converted to a concrete UIColor. The StateScheme's ColorResources based API allows independence of a specific Color Scheme implementation. Clients (mostly themers) can then use the ColorResources, together with a specific color scheme, to get a concrete UIColor that can be used to theme components.

### Issue

[b/123929971](b/123929971)

2019-02-25 20:12 UTC, material-automation commented
The following files are not in any BUILD targets:

```
components/schemes/State/examples/src/MDCColorResource.h
components/schemes/State/examples/src/MDCColorResource.m
```


<!-- identifier: bazel-rule-coverage -->

2019-02-26 19:48 UTC, romoore requested changes
It's not clear what problem this is solving within states/theming. Specifically, it seems to be a combination of reimplementing UIColor initializers (this looks like a collection of constructors) and serialization mechanics.

I'm also worried about the "hex" idea here combined with "dim". How does this handle the P3 color space vs. sRGB?  How is "darkness" (or lightness) defined here since it is inherently based on the color space used?

2019-02-26 19:48 UTC, romoore commented on components/schemes/State/examples/src/MDCColorResource.h
> +  MDCColorResourceSemanticNone,
Can you add comments to these types? Of note, I don't understand what a `.None` Semantic represents.

2019-02-26 19:48 UTC, romoore commented on components/schemes/State/examples/src/MDCColorResource.h
> +typedef NS_ENUM(NSInteger, MDCColorResourceSemantic) {
Nit/naming: What kind of "Semantic" is this?  Should it be `MDCColorSemanticResourceType`?   "Semantic" is an adjective and it feels odd ending a name with an adjective.

2019-02-26 19:48 UTC, romoore commented on components/schemes/State/examples/src/MDCColorResource.h
> +static const CGFloat MDCColorResourceDefaultOpacity = 1.0;
Nit: Constants should start with `k`

http://google.github.io/styleguide/objcguide.html#constants

2019-02-26 19:52 UTC, romoore commented
@galiak - If this is experimental, I would suggest working within a feature branch in this repo or on your own fork.  I don't think the main repository is going to be very productive for you to be doing rapid explorations/prototyping on new ideas.  The bar for PR submission is much higher than in a fork or feature branch.

2019-04-01 23:00 UTC, jverkoey commented
Closing this PR due to inactivity. Please re-open when you intend to pursue it.

2019-04-01 23:00 UTC, closed without merging