[FlexibleHeader] Fix incorrect insets during animated transitions
material-components/material-components-ios pull request #6752
Opened 2019-03-04 15:56 UTC by wenyuzhang666

Issue: https://github.com/material-components/material-components-ios/issues/6437

Change:
Allow flexible header to update insets when adjustedContentInset is changed on a tracking view when it is not the current tracking view.

Screenshot before change:
https://user-images.githubusercontent.com/395995/51554264-ddd66180-1e42-11e9-9b36-65da73dd069c.gif
Screenshot after change:
iPhone7+ (10.3.1)
![fv2](https://user-images.githubusercontent.com/8836258/53744858-dd7eac80-3e6b-11e9-8db8-ee4bdbe849a6.gif)

iPhoneX (12.0)
![fv1](https://user-images.githubusercontent.com/8836258/53744882-ef604f80-3e6b-11e9-967d-23e09fc42c43.gif)

2019-03-04 15:59 UTC, material-automation commented on components/FlexibleHeader/src/MDCFlexibleHeaderView.h
> + implementor.
clang-format suggested the following change:


```
- Must be called from the trackingScrollView delegate's UIScrollViewDelegate::scrollViewDidChangeAdjustedContentInset:
- implementor.
+ Must be called from the trackingScrollView delegate's
+ UIScrollViewDelegate::scrollViewDidChangeAdjustedContentInset: implementor.
```

<!-- identifier: clang-format -->
<!-- File: components/FlexibleHeader/src/MDCFlexibleHeaderView.h -->

2019-03-04 15:59 UTC, material-automation commented on components/FlexibleHeader/src/MDCFlexibleHeaderView.h
> +- (void)trackingScrollViewDidChangeAdjustedContentInset:(UIScrollView *)trackingScrollView API_AVAILABLE(ios(11.0), tvos(11.0));
clang-format suggested the following change:


```
-- (void)trackingScrollViewDidChangeAdjustedContentInset:(UIScrollView *)trackingScrollView API_AVAILABLE(ios(11.0), tvos(11.0));
+- (void)trackingScrollViewDidChangeAdjustedContentInset:(UIScrollView *)trackingScrollView
+    API_AVAILABLE(ios(11.0), tvos(11.0));
```

<!-- identifier: clang-format -->
<!-- File: components/FlexibleHeader/src/MDCFlexibleHeaderView.h -->

2019-03-04 15:59 UTC, material-automation commented on components/FlexibleHeader/src/MDCFlexibleHeaderView.m
> +- (void)fhv_setContentOffset:(CGPoint)contentOffset forTrackingScrollView:(UIScrollView *)trackingScrollView {
clang-format suggested the following change:


```
-- (void)fhv_setContentOffset:(CGPoint)contentOffset forTrackingScrollView:(UIScrollView *)trackingScrollView {
+- (void)fhv_setContentOffset:(CGPoint)contentOffset
+       forTrackingScrollView:(UIScrollView *)trackingScrollView {
```

<!-- identifier: clang-format -->
<!-- File: components/FlexibleHeader/src/MDCFlexibleHeaderView.m -->

2019-03-04 15:59 UTC, material-automation commented on components/FlexibleHeader/src/MDCFlexibleHeaderView.m
> +    [self fhv_setContentOffset:offsetPriorToInsetAdjustment forTrackingScrollView:trackingScrollView];
clang-format suggested the following change:


```
-    [self fhv_setContentOffset:offsetPriorToInsetAdjustment forTrackingScrollView:trackingScrollView];
+    [self fhv_setContentOffset:offsetPriorToInsetAdjustment
+         forTrackingScrollView:trackingScrollView];
```

<!-- identifier: clang-format -->
<!-- File: components/FlexibleHeader/src/MDCFlexibleHeaderView.m -->

2019-03-04 15:59 UTC, material-automation commented
clang-format recommended changes.

Consider installing [git-clang-format](https://github.com/llvm-mirror/clang/blob/master/tools/clang-format/git-clang-format) and running the following command:

```bash
git clang-format $(git merge-base origin/develop HEAD)
```

<!-- identifier: clang-format -->

2019-03-04 15:59 UTC, material-automation commented
bazel detected changes to the following targets:

```
//catalog:MDCCatalog
//catalog:MDCCatalog.apple_binary
//catalog:MDCCatalog.swift_runtime_linkopts
//catalog:MDCCatalogLib
//catalog:MDCDragons
//catalog:MDCDragons.apple_binary
//catalog:MDCDragons.swift_runtime_linkopts
//catalog:MDCDragonsLib
//components/AppBar:AppBar
//components/AppBar:ColorThemer
//components/AppBar:ObjcExamples
//components/AppBar:SwiftExamples
//components/AppBar:TypographyThemer
//components/AppBar:unit_test_swift_sources
//components/AppBar:unit_tests
//components/AppBar:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/AppBar:unit_tests_IPAD_PRO_12_9_IN_9_3.swift_runtime_linkopts
//components/AppBar:unit_tests_IPAD_PRO_12_9_IN_9_3_test_binary
//components/AppBar:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/AppBar:unit_tests_IPHONE_5_IN_8_1
//components/AppBar:unit_tests_IPHONE_5_IN_8_1.swift_runtime_linkopts
//components/AppBar:unit_tests_IPHONE_5_IN_8_1_test_binary
//components/AppBar:unit_tests_IPHONE_5_IN_8_1_test_bundle
//components/AppBar:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/AppBar:unit_tests_IPHONE_7_PLUS_IN_10_3.swift_runtime_linkopts
//components/AppBar:unit_tests_IPHONE_7_PLUS_IN_10_3_test_binary
//components/AppBar:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/AppBar:unit_tests_IPHONE_X_IN_11_0
//components/AppBar:unit_tests_IPHONE_X_IN_11_0.swift_runtime_linkopts
//components/AppBar:unit_tests_IPHONE_X_IN_11_0_test_binary
//components/AppBar:unit_tests_IPHONE_X_IN_11_0_test_bundle
//components/BottomAppBar:ObjcExamples
//components/BottomAppBar:SwiftExamples
//components/BottomNavigation:SwiftExamples
//components/BottomSheet:ObjcExamples
//components/FlexibleHeader:CanAlwaysExpandToMaximumHeight
//components/FlexibleHeader:ColorThemer
//components/FlexibleHeader:FlexibleHeader
//components/FlexibleHeader:ObjcExamples
//components/FlexibleHeader:unit_test_sources
//components/FlexibleHeader:unit_test_swift_sources
//components/FlexibleHeader:unit_tests
//components/FlexibleHeader:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/FlexibleHeader:unit_tests_IPAD_PRO_12_9_IN_9_3.swift_runtime_linkopts
//components/FlexibleHeader:unit_tests_IPAD_PRO_12_9_IN_9_3_test_binary
//components/FlexibleHeader:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/FlexibleHeader:unit_tests_IPHONE_5_IN_8_1
//components/FlexibleHeader:unit_tests_IPHONE_5_IN_8_1.swift_runtime_linkopts
//components/FlexibleHeader:unit_tests_IPHONE_5_IN_8_1_test_binary
//components/FlexibleHeader:unit_tests_IPHONE_5_IN_8_1_test_bundle
//components/FlexibleHeader:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/FlexibleHeader:unit_tests_IPHONE_7_PLUS_IN_10_3.swift_runtime_linkopts
//components/FlexibleHeader:unit_tests_IPHONE_7_PLUS_IN_10_3_test_binary
//components/FlexibleHeader:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/FlexibleHeader:unit_tests_IPHONE_X_IN_11_0
//components/FlexibleHeader:unit_tests_IPHONE_X_IN_11_0.swift_runtime_linkopts
//components/FlexibleHeader:unit_tests_IPHONE_X_IN_11_0_test_binary
//components/FlexibleHeader:unit_tests_IPHONE_X_IN_11_0_test_bundle
//components/ShadowElevations:SwiftExamples
//components/Tabs:ObjcExamples
//components/Tabs:SwiftExamples
//components/TextFields:ExperimentalExamples
//components/TextFields:SwiftExamples
//components/schemes/Shape:ObjcExamples
```

<!-- identifier: affected-targets -->

2019-03-04 16:03 UTC, material-automation commented
## API diff detected the following changes

### FlexibleHeader

#### MDCFlexibleHeaderView

*new* method: `-trackingScrollViewDidChangeAdjustedContentInset:` in `MDCFlexibleHeaderView`

#### MDCFlexibleHeaderView()

*new* category: `MDCFlexibleHeaderView()`

*removed* category: `MDCFlexibleHeaderView()`

*modified* property: `contentView` in `MDCFlexibleHeaderView()`

| Type of change: | parent.usr |
|---|---|
| From: | `c:objc(ext)MDCFlexibleHeaderView@MDCFlexibleHeaderView.h@14987` |
| To: | `c:objc(ext)MDCFlexibleHeaderView@MDCFlexibleHeaderView.h@15435` |

<!-- identifier: apidiff -->

2019-03-12 20:22 UTC, jverkoey requested changes
Due to the risk profile of behavioral changes to FHV can you break this PR out into a refactoring PR and then a fix? The more we can minimize the amount of behavioral changes the less likely we are to introduce a behavioral regression in the flexible header.

2019-03-13 14:37 UTC, wenyuzhang666 commented
https://github.com/material-components/material-components-ios/pull/6862 (refactor) and https://github.com/material-components/material-components-ios/pull/6863 (fix) have been created for this issue.

2019-03-13 14:59 UTC, closed without merging