Initial implementation of MDCTabBar and private MDCItemBar
material-components/material-components-ios pull request #711
Opened 2016-09-27 15:11 UTC by brianjmoore

This introduces the Tabs component and adds an initial implementation of MDCTabBar, a material tab bar component for top tabs. This also adds a private class called MDCItemBar, which serves as the underlying implementation of the tab bar. The MDCTabBar class is a wrapper with a focused API that drives an underlying item bar via a style object.

The in-progress bottom navigation bar will also be based on the item bar and will live in the Tabs component.

In progress next steps:
- Documentation
- Bottom navigation bar

2016-09-27 16:59 UTC, randallli requested changes

2016-09-28 14:15 UTC, ajsecord requested changes
Please add the copyright boilerplate on every .h, .m, and .swift file.

2016-09-28 14:28 UTC, ajsecord requested changes

2016-09-30 20:41 UTC, ajsecord approved these changes

2016-10-03 19:09 UTC, randallli approved these changes

2016-10-04 16:29 UTC, merged