[MDC Typography] Add a category of MDCFontScaler to facilitate mutation.
material-components/material-components-ios pull request #7308
Opened 2019-05-01 06:27 UTC by wenyuzhang666

The current MDCFontScaler implementation stops clients to add/modify custom curves.

This PR added `MDCFontScaler+Mutating` category to expose essential properties. 

It would help clients to modify the existing curves or adding more curves into a font scaler. It also helps clients if they want to subclass the MDCFontScaler to build their logic for factory class method.

2019-05-01 06:30 UTC, material-automation commented
bazel detected changes to the following targets:

```
//components/ActionSheet:snapshot_tests
//components/ActionSheet:snapshot_tests_test_bundle
//components/ActionSheet:unit_tests
//components/ActionSheet:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/ActionSheet:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/ActionSheet:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/ActionSheet:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/ActionSheet:unit_tests_IPHONE_X_IN_11_0
//components/ActionSheet:unit_tests_IPHONE_X_IN_11_0_test_bundle
//components/AppBar:snapshot_tests
//components/AppBar:snapshot_tests_test_bundle
//components/AppBar:unit_tests
//components/AppBar:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/AppBar:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/AppBar:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/AppBar:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/AppBar:unit_tests_IPHONE_X_IN_11_0
//components/AppBar:unit_tests_IPHONE_X_IN_11_0_test_bundle
//components/Banner:snapshot_tests
//components/Banner:snapshot_tests_test_bundle
//components/BottomAppBar:snapshot_tests
//components/BottomAppBar:snapshot_tests_test_bundle
//components/BottomAppBar:unit_tests
//components/BottomAppBar:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/BottomAppBar:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/BottomAppBar:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/BottomAppBar:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/BottomAppBar:unit_tests_IPHONE_X_IN_11_0
//components/BottomAppBar:unit_tests_IPHONE_X_IN_11_0_test_bundle
//components/BottomNavigation:snapshot_tests
//components/BottomNavigation:snapshot_tests_test_bundle
//components/BottomNavigation:unit_tests
//components/BottomNavigation:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/BottomNavigation:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/BottomNavigation:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/BottomNavigation:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/BottomNavigation:unit_tests_IPHONE_X_IN_11_0
//components/BottomNavigation:unit_tests_IPHONE_X_IN_11_0_test_bundle
//components/BottomNavigation:unit_tests_beta
//components/BottomNavigation:unit_tests_beta_test_bundle
//components/ButtonBar:snapshot_tests
//components/ButtonBar:snapshot_tests_test_bundle
//components/ButtonBar:unit_tests
//components/ButtonBar:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/ButtonBar:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/ButtonBar:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/ButtonBar:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/ButtonBar:unit_tests_IPHONE_X_IN_11_0
//components/ButtonBar:unit_tests_IPHONE_X_IN_11_0_test_bundle
//components/Buttons:snapshot_tests
//components/Buttons:snapshot_tests_test_bundle
//components/Buttons:unit_tests
//components/Buttons:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/Buttons:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/Buttons:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/Buttons:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/Buttons:unit_tests_IPHONE_X_IN_11_0
//components/Buttons:unit_tests_IPHONE_X_IN_11_0_test_bundle
//components/Cards:snapshot_tests
//components/Cards:snapshot_tests_test_bundle
//components/Cards:unit_tests
//components/Cards:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/Cards:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/Cards:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/Cards:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/Cards:unit_tests_IPHONE_X_IN_11_0
//components/Cards:unit_tests_IPHONE_X_IN_11_0_test_bundle
//components/Chips:snapshot_tests
//components/Chips:snapshot_tests_test_bundle
//components/Chips:unit_tests
//components/Chips:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/Chips:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/Chips:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/Chips:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/Chips:unit_tests_IPHONE_X_IN_11_0
//components/Chips:unit_tests_IPHONE_X_IN_11_0_test_bundle
//components/CollectionCells:unit_tests
//components/CollectionCells:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/CollectionCells:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/CollectionCells:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/CollectionCells:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/CollectionCells:unit_tests_IPHONE_X_IN_11_0
//components/CollectionCells:unit_tests_IPHONE_X_IN_11_0_test_bundle
//components/Collections:unit_tests
//components/Collections:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/Collections:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/Collections:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/Collections:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/Collections:unit_tests_IPHONE_X_IN_11_0
//components/Collections:unit_tests_IPHONE_X_IN_11_0_test_bundle
//components/Dialogs:snapshot_tests
//components/Dialogs:snapshot_tests_test_bundle
//components/Dialogs:unit_tests
//components/Dialogs:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/Dialogs:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/Dialogs:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/Dialogs:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/Dialogs:unit_tests_IPHONE_X_IN_11_0
//components/Dialogs:unit_tests_IPHONE_X_IN_11_0_test_bundle
//components/FeatureHighlight:unit_tests
//components/FeatureHighlight:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/FeatureHighlight:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/FeatureHighlight:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/FeatureHighlight:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/FeatureHighlight:unit_tests_IPHONE_X_IN_11_0
//components/FeatureHighlight:unit_tests_IPHONE_X_IN_11_0_test_bundle
//components/HeaderStackView:unit_tests
//components/HeaderStackView:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/HeaderStackView:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/HeaderStackView:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/HeaderStackView:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/HeaderStackView:unit_tests_IPHONE_X_IN_11_0
//components/HeaderStackView:unit_tests_IPHONE_X_IN_11_0_test_bundle
//components/Ink:unit_tests
//components/Ink:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/Ink:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/Ink:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/Ink:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/Ink:unit_tests_IPHONE_X_IN_11_0
//components/Ink:unit_tests_IPHONE_X_IN_11_0_test_bundle
//components/List:snapshot_tests
//components/List:snapshot_tests_test_bundle
//components/List:unit_tests
//components/List:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/List:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/List:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/List:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/List:unit_tests_IPHONE_X_IN_11_0
//components/List:unit_tests_IPHONE_X_IN_11_0_test_bundle
//components/NavigationBar:snapshot_tests
//components/NavigationBar:snapshot_tests_test_bundle
//components/NavigationBar:unit_tests
//components/NavigationBar:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/NavigationBar:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/NavigationBar:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/NavigationBar:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/NavigationBar:unit_tests_IPHONE_X_IN_11_0
//components/NavigationBar:unit_tests_IPHONE_X_IN_11_0_test_bundle
//components/PageControl:unit_tests
//components/PageControl:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/PageControl:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/PageControl:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/PageControl:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/PageControl:unit_tests_IPHONE_X_IN_11_0
//components/PageControl:unit_tests_IPHONE_X_IN_11_0_test_bundle
//component [...]

2019-05-01 06:30 UTC, material-automation commented
bazel detected changes to the following targets:

```
//catalog:MDCCatalog
//catalog:MDCCatalog.apple_binary
//catalog:MDCCatalog.swift_runtime_linkopts
//catalog:MDCCatalogLib
//catalog:MDCDragons
//catalog:MDCDragons.apple_binary
//catalog:MDCDragons.swift_runtime_linkopts
//catalog:MDCDragonsLib
//catalog:MaterialCatalog
//components/ActionSheet:ActionSheet
//components/ActionSheet:ActionSheetThemer
//components/ActionSheet:ColorThemer
//components/ActionSheet:ObjcExamples
//components/ActionSheet:SwiftExamples
//components/ActionSheet:Theming
//components/ActionSheet:TypographyThemer
//components/ActionSheet:privateHeaders
//components/ActionSheet:snapshot_test_lib
//components/ActionSheet:snapshot_tests
//components/ActionSheet:snapshot_tests.swift_runtime_linkopts
//components/ActionSheet:snapshot_tests_test_binary
//components/ActionSheet:snapshot_tests_test_bundle
//components/ActionSheet:unit_test_color_themer_swift_sources
//components/ActionSheet:unit_test_sources
//components/ActionSheet:unit_test_swift_sources
//components/ActionSheet:unit_test_themer_sources
//components/ActionSheet:unit_test_theming_sources
//components/ActionSheet:unit_tests
//components/ActionSheet:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/ActionSheet:unit_tests_IPAD_PRO_12_9_IN_9_3.swift_runtime_linkopts
//components/ActionSheet:unit_tests_IPAD_PRO_12_9_IN_9_3_test_binary
//components/ActionSheet:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/ActionSheet:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/ActionSheet:unit_tests_IPHONE_7_PLUS_IN_10_3.swift_runtime_linkopts
//components/ActionSheet:unit_tests_IPHONE_7_PLUS_IN_10_3_test_binary
//components/ActionSheet:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/ActionSheet:unit_tests_IPHONE_X_IN_11_0
//components/ActionSheet:unit_tests_IPHONE_X_IN_11_0.swift_runtime_linkopts
//components/ActionSheet:unit_tests_IPHONE_X_IN_11_0_test_binary
//components/ActionSheet:unit_tests_IPHONE_X_IN_11_0_test_bundle
//components/ActivityIndicator:ObjcExamples
//components/AnimationTiming:ObjcExamples
//components/AnimationTiming:SwiftExamples
//components/AppBar:AppBar
//components/AppBar:ColorThemer
//components/AppBar:ObjcExamples
//components/AppBar:SwiftExamples
//components/AppBar:Theming
//components/AppBar:TypographyThemer
//components/AppBar:snapshot_test_lib
//components/AppBar:snapshot_tests
//components/AppBar:snapshot_tests.swift_runtime_linkopts
//components/AppBar:snapshot_tests_test_binary
//components/AppBar:snapshot_tests_test_bundle
//components/AppBar:unit_test_sources
//components/AppBar:unit_test_swift_sources
//components/AppBar:unit_tests
//components/AppBar:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/AppBar:unit_tests_IPAD_PRO_12_9_IN_9_3.swift_runtime_linkopts
//components/AppBar:unit_tests_IPAD_PRO_12_9_IN_9_3_test_binary
//components/AppBar:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/AppBar:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/AppBar:unit_tests_IPHONE_7_PLUS_IN_10_3.swift_runtime_linkopts
//components/AppBar:unit_tests_IPHONE_7_PLUS_IN_10_3_test_binary
//components/AppBar:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/AppBar:unit_tests_IPHONE_X_IN_11_0
//components/AppBar:unit_tests_IPHONE_X_IN_11_0.swift_runtime_linkopts
//components/AppBar:unit_tests_IPHONE_X_IN_11_0_test_binary
//components/AppBar:unit_tests_IPHONE_X_IN_11_0_test_bundle
//components/Banner:Banner
//components/Banner:ObjcExamples
//components/Banner:snapshot_test_lib
//components/Banner:snapshot_tests
//components/Banner:snapshot_tests.swift_runtime_linkopts
//components/Banner:snapshot_tests_test_binary
//components/Banner:snapshot_tests_test_bundle
//components/BottomAppBar:BottomAppBar
//components/BottomAppBar:ColorThemer
//components/BottomAppBar:ObjcExamples
//components/BottomAppBar:SwiftExamples
//components/BottomAppBar:snapshot_test_lib
//components/BottomAppBar:snapshot_tests
//components/BottomAppBar:snapshot_tests.swift_runtime_linkopts
//components/BottomAppBar:snapshot_tests_test_binary
//components/BottomAppBar:snapshot_tests_test_bundle
//components/BottomAppBar:unit_test_sources
//components/BottomAppBar:unit_tests
//components/BottomAppBar:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/BottomAppBar:unit_tests_IPAD_PRO_12_9_IN_9_3.swift_runtime_linkopts
//components/BottomAppBar:unit_tests_IPAD_PRO_12_9_IN_9_3_test_binary
//components/BottomAppBar:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/BottomAppBar:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/BottomAppBar:unit_tests_IPHONE_7_PLUS_IN_10_3.swift_runtime_linkopts
//components/BottomAppBar:unit_tests_IPHONE_7_PLUS_IN_10_3_test_binary
//components/BottomAppBar:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/BottomAppBar:unit_tests_IPHONE_X_IN_11_0
//components/BottomAppBar:unit_tests_IPHONE_X_IN_11_0.swift_runtime_linkopts
//components/BottomAppBar:unit_tests_IPHONE_X_IN_11_0_test_binary
//components/BottomAppBar:unit_tests_IPHONE_X_IN_11_0_test_bundle
//components/BottomNavigation:BottomNavigation
//components/BottomNavigation:BottomNavigationBeta
//components/BottomNavigation:ColorThemer
//components/BottomNavigation:ObjcExamples
//components/BottomNavigation:SwiftExamples
//components/BottomNavigation:TypographyThemer
//components/BottomNavigation:snapshot_test_lib
//components/BottomNavigation:snapshot_tests
//components/BottomNavigation:snapshot_tests.swift_runtime_linkopts
//components/BottomNavigation:snapshot_tests_test_binary
//components/BottomNavigation:snapshot_tests_test_bundle
//components/BottomNavigation:unit_test_beta_sources
//components/BottomNavigation:unit_test_sources
//components/BottomNavigation:unit_tests
//components/BottomNavigation:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/BottomNavigation:unit_tests_IPAD_PRO_12_9_IN_9_3.swift_runtime_linkopts
//components/BottomNavigation:unit_tests_IPAD_PRO_12_9_IN_9_3_test_binary
//components/BottomNavigation:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/BottomNavigation:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/BottomNavigation:unit_tests_IPHONE_7_PLUS_IN_10_3.swift_runtime_linkopts
//components/BottomNavigation:unit_tests_IPHONE_7_PLUS_IN_10_3_test_binary
//components/BottomNavigation:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/BottomNavigation:unit_tests_IPHONE_X_IN_11_0
//components/BottomNavigation:unit_tests_IPHONE_X_IN_11_0.swift_runtime_linkopts
//components/BottomNavigation:unit_tests_IPHONE_X_IN_11_0_test_binary
//components/BottomNavigation:unit_tests_IPHONE_X_IN_11_0_test_bundle
//components/BottomNavigation:unit_tests_beta
//components/BottomNavigation:unit_tests_beta.swift_runtime_linkopts
//components/BottomNavigation:unit_tests_beta_test_binary
//components/BottomNavigation:unit_tests_beta_test_bundle
//components/BottomSheet:ObjcExamples
//components/BottomSheet:SwiftExamples
//components/ButtonBar:ButtonBar
//components/ButtonBar:ColorThemer
//components/ButtonBar:ObjcExamples
//components/ButtonBar:SwiftExamples
//components/ButtonBar:Theming
//components/ButtonBar:TypographyThemer
//components/ButtonBar:snapshot_test_lib
//components/ButtonBar:snapshot_tests
//components/ButtonBar:snapshot_tests.swift_runtime_linkopts
//components/ButtonBar:snapshot_tests_test_binary
//components/ButtonBar:snapshot_tests_test_bundle
//components/ButtonBar:unit_test_sources
//components/ButtonBar:unit_test_swift_sources
//components/ButtonBar:unit_tests
//components/ButtonBar:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/ButtonBar:unit_tests_IPAD_PRO_12_9_IN_9_3.swift_runtime_linkopts
//components/ButtonBar:unit_tests_IPAD_PRO_12_9_IN_9_3_test_binary
//components/ButtonBar:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/ButtonBar:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/ButtonBar:unit_tests_IPHONE_7_PLUS_IN_10_3.swift_runtime_linkopts
//components/ButtonBar:unit_tests_IPHONE_7_PLUS_IN_10_3_test_binary
//components/ButtonBar:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/B [...]

2019-05-01 10:45 UTC, jverkoey commented
Please provide the context that is requiring this change either via a bug or cl number.

2019-05-01 10:45 UTC, jverkoey requested changes
Please provide the context that is requiring this change either via a bug or cl number.

2019-05-01 15:03 UTC, wenyuzhang666 commented
@jverkoey The description was updated with a newly added issue.

2019-05-01 15:12 UTC, jverkoey commented
This looks like a fairly substantial change; we'll likely want to add this one to our sprint in terms of time estimation because it may warrant revisiting the design doc for this API.

2019-05-01 15:43 UTC, wenyuzhang666 commented
@jverkoey I agree. It may not be the best way, since we already have method to attach custom curve to font. It was just our FontScaler doesn't provide this functionality. I will bring it up to the sprint.

2019-05-01 16:16 UTC, closed without merging

2019-05-01 16:18 UTC, wenyuzhang666 commented
Closing this PR since it is obsolete. We are not going to expose mutable property for MDCFontScaler  since immutability was made intentionally.

2019-05-02 14:08 UTC, romoore commented
I don't believe this class was meant to be used by other projects. If I understand correctly, @ianegordon expected any other similar implementation to be written independently.