[ActionSheet] Simplify BottomSheet import.
material-components/material-components-ios pull request #7552
Opened 2019-06-10 17:45 UTC by romoore

Using framework-style imports within the same framework is causing
problems for some internal clients. Instead, use simpler file imports.

Closes #7551

2019-06-10 17:47 UTC, jverkoey requested changes
I would expect us to be rewriting these import statements; can you link to the cl/ or b/ that motivated this change?

2019-06-10 17:47 UTC, material-automation commented
bazel detected changes to the following targets:

```
//components/ActionSheet:ActionSheet
//components/ActionSheet:ActionSheetThemer
//components/ActionSheet:ColorThemer
//components/ActionSheet:ObjcExamples
//components/ActionSheet:SwiftExamples
//components/ActionSheet:Theming
//components/ActionSheet:TypographyThemer
//components/ActionSheet:privateHeaders
//components/ActionSheet:snapshot_test_lib
//components/ActionSheet:snapshot_tests
//components/ActionSheet:snapshot_tests.swift_runtime_linkopts
//components/ActionSheet:snapshot_tests_test_binary
//components/ActionSheet:snapshot_tests_test_bundle
//components/ActionSheet:unit_test_color_themer_swift_sources
//components/ActionSheet:unit_test_sources
//components/ActionSheet:unit_test_swift_sources
//components/ActionSheet:unit_test_themer_sources
//components/ActionSheet:unit_test_theming_sources
//components/ActionSheet:unit_tests
//components/ActionSheet:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/ActionSheet:unit_tests_IPAD_PRO_12_9_IN_9_3.swift_runtime_linkopts
//components/ActionSheet:unit_tests_IPAD_PRO_12_9_IN_9_3_test_binary
//components/ActionSheet:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/ActionSheet:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/ActionSheet:unit_tests_IPHONE_7_PLUS_IN_10_3.swift_runtime_linkopts
//components/ActionSheet:unit_tests_IPHONE_7_PLUS_IN_10_3_test_binary
//components/ActionSheet:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/ActionSheet:unit_tests_IPHONE_X_IN_11_0
//components/ActionSheet:unit_tests_IPHONE_X_IN_11_0.swift_runtime_linkopts
//components/ActionSheet:unit_tests_IPHONE_X_IN_11_0_test_binary
//components/ActionSheet:unit_tests_IPHONE_X_IN_11_0_test_bundle
```

<!-- identifier: affected-targets -->

2019-06-10 17:48 UTC, romoore commented
@jverkoey #7551 is the bug tracking this issue.

2019-06-10 17:50 UTC, jverkoey requested changes
Please link to the internal bug or cl that motivated this change. The public issue you're linking to includes no ability to dig in to the internal context that motivated this change.

2019-06-10 17:51 UTC, romoore commented
@jverkoey There's no internal issue for this bug.  It's an internal client building using CocoaPods.

2019-06-10 17:54 UTC, jverkoey commented
If the internal client is using CocoaPods, is this a problem with our CocoaPods code publicly as well?

2019-06-10 17:55 UTC, romoore commented
@jverkoey I don't know. I'm just responding to a client request to unblock their build breakage as they adopt Action Sheet.

2019-06-10 18:02 UTC, jverkoey commented
Can you link me offline to the request here? This is a very surprising PR / internal problem.

2019-06-11 10:48 UTC, jverkoey approved these changes
LGTM after discussion with the  client.

2019-06-11 12:27 UTC, merged