[releasing] Remove excessive pod lib lint
material-components/material-components-ios pull request #7660
Opened 2019-06-20 17:35 UTC by jverkoey

Kokoro lints the podspec, and `pod` lints the podspec as part of the push process. Manually running the linter is unnecessary as part of the releasing process. In the unlikely event that the lint fails as part of the publication then another internal CL may need to be created.

2019-06-20 18:21 UTC, romoore requested changes
I'd like to keep this. More than once we've had to revert a change in the `release-candidate` branch because we misconfigured our various podspecs. Only the linter caught it. If we waited until the internal changes landed, _then_ checked if everything was OK publicly, we'd have to do a separate CL (potentially reverting client changes) in order to get it working.

2019-06-20 19:12 UTC, randallli commented on contributing/releasing.md
> -#### Verify CocoaPods podspec and trunk access
"In the unlikely event that the lint fails as part of the publication then another internal CL may need to be created"
this should be added below in the push instructions then.

2019-06-20 19:12 UTC, randallli commented on contributing/releasing.md
> -#### Verify CocoaPods podspec and trunk access
Actually this was put in place to counter that very use. 

Your status would be: Having it lint fail after you have already pushed to stable and develop. I felt that these instructions above here would catch a bunch of things that would make the release cop's life easier.

Which branch do you apply your fixes to? stable? and then cherry pick them into develop too? or start another release? the release-candidate branch is deleted at this point.

2019-06-21 14:16 UTC, romoore commented
To address your PR summary, there is no functional kokoro job that lints the podspec. The existing ["podspec" job is failing consistently](https://github.com/material-components/material-components-ios/issues/6678) and is no longer required and is ignored. See [the most recent release PR for an example of it failing](https://github.com/material-components/material-components-ios/pull/7653).

2019-07-16 00:22 UTC, yarneo commented
I think that based on recent events this has to be a mandatory bit for release engineers to make sure `pod trunk push` would successfully work, as the CI for `pod lib lint` has been failing continuously since CocoaPods 1.6

2019-09-10 14:03 UTC, closed without merging