WIP [Tabs] Adds safe area inset
material-components/material-components-ios pull request #7753
Opened 2019-06-28 20:28 UTC by leonmz

Add safe area handling to MDCTabBarView
closes #1234

2019-06-28 20:30 UTC, material-automation commented on components/Tabs/src/TabBarView/MDCTabBarView.m
> +
clang-format suggested the following change:


```
-  
+
```

<!-- identifier: clang-format -->
<!-- File: components/Tabs/src/TabBarView/MDCTabBarView.m -->

2019-06-28 20:30 UTC, material-automation commented
clang-format recommended changes.

Consider installing [git-clang-format](https://github.com/llvm-mirror/clang/blob/master/tools/clang-format/git-clang-format) and running the following command:

```bash
git clang-format $(git merge-base origin/develop HEAD)
```

<!-- identifier: clang-format -->

2019-06-28 20:30 UTC, material-automation commented
bazel detected changes to the following targets:

```
//components/Tabs:ObjcExamples
//components/Tabs:TabBarView
//components/Tabs:snapshot_test_lib
//components/Tabs:snapshot_tests
//components/Tabs:snapshot_tests.swift_runtime_linkopts
//components/Tabs:snapshot_tests_test_binary
//components/Tabs:snapshot_tests_test_bundle
//components/Tabs:unit_test_tabbarview_sources
//components/Tabs:unit_tests
//components/Tabs:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/Tabs:unit_tests_IPAD_PRO_12_9_IN_9_3.swift_runtime_linkopts
//components/Tabs:unit_tests_IPAD_PRO_12_9_IN_9_3_test_binary
//components/Tabs:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/Tabs:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/Tabs:unit_tests_IPHONE_7_PLUS_IN_10_3.swift_runtime_linkopts
//components/Tabs:unit_tests_IPHONE_7_PLUS_IN_10_3_test_binary
//components/Tabs:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/Tabs:unit_tests_IPHONE_X_IN_11_0
//components/Tabs:unit_tests_IPHONE_X_IN_11_0.swift_runtime_linkopts
//components/Tabs:unit_tests_IPHONE_X_IN_11_0_test_binary
//components/Tabs:unit_tests_IPHONE_X_IN_11_0_test_bundle
```

<!-- identifier: affected-targets -->

2019-06-28 20:34 UTC, material-automation commented
## API diff detected the following changes

### Tabs+TabBarView

#### MDCTabBarView

*new* property: `edgeInsets` in `MDCTabBarView`

<!-- identifier: apidiff -->

2019-06-29 01:11 UTC, leonmz commented
This PR broken the selection visible function for some reason... looking into it now

2019-06-29 01:44 UTC, leonmz commented
One bug I found is that iPhone 7 iOS 11.2 the tab bar view cannot scroll.

2019-06-29 01:58 UTC, romoore requested changes
Given the concerns you shared about iPhone 7/iOS 11.2 on Xcode 10.1, I want to make sure we diagnose that bug before merging

2019-06-29 01:58 UTC, romoore commented on components/Tabs/src/TabBarView/MDCTabBarView.m
> +/** The constraints that used to set up justified view propertly inseted by safe area. */
Nit/grammar: "Constraints unique to the 'Justified' layout style."

2019-06-29 01:58 UTC, romoore commented on components/Tabs/src/TabBarView/MDCTabBarView.m
> +/** The constraints that used to set up scrollable views */
Nit/grammar: "Constraints unique to the 'Scrollable' layout style."

2019-06-29 01:58 UTC, romoore commented on components/Tabs/src/TabBarView/MDCTabBarView.m
> +@property(nullable, nonatomic) NSArray<NSLayoutConstraint *> *widthConstraints;
Nit/naming: `scrollableLayoutConstraints`.

2019-06-29 01:58 UTC, romoore commented on components/Tabs/src/TabBarView/MDCTabBarView.m
> +@property(nullable, nonatomic) NSArray<NSLayoutConstraint *> *justifiedSafeAreaInsetConstraints;
Nit/naming: `justifiedLayoutConstraints`.

2019-06-29 01:58 UTC, romoore commented on components/Tabs/src/TabBarView/MDCTabBarView.m
> +      self.contentInset = UIEdgeInsetsMake(self.contentInset.top, self.safeAreaInsets.left,
I believe `adjustedContentInset` already includes the `safeAreaInsets` if `contentInsetAdjustmentBehavior` is `.automatic`. Did you not find that to be the case?

2019-06-29 01:58 UTC, romoore commented on components/Tabs/src/TabBarView/MDCTabBarView.m
> +      self.contentInset = UIEdgeInsetsMake(self.contentInset.top, self.safeAreaInsets.left,
Some further reading:
https://medium.com/@wailord/the-particulars-of-the-safe-area-and-contentinsetadjustmentbehavior-in-ios-11-9b842018eeaa

2019-07-01 02:58 UTC, romoore commented
Going to play with this and see if I can figure out what's going wrong on iPhone 7.

2019-07-01 05:02 UTC, romoore commented on components/Tabs/src/TabBarView/MDCTabBarView.m
> +/** The constraints that used to set up justified view propertly inseted by safe area. */
Done.

2019-07-01 05:02 UTC, romoore commented on components/Tabs/src/TabBarView/MDCTabBarView.m
> +@property(nullable, nonatomic) NSArray<NSLayoutConstraint *> *widthConstraints;
Done.

2019-07-01 05:02 UTC, romoore commented on components/Tabs/src/TabBarView/MDCTabBarView.m
> +@property(nullable, nonatomic) NSArray<NSLayoutConstraint *> *justifiedSafeAreaInsetConstraints;
Done.

2019-07-01 05:04 UTC, romoore commented on components/Tabs/src/TabBarView/MDCTabBarView.m
> +      self.contentInset = UIEdgeInsetsMake(self.contentInset.top, self.safeAreaInsets.left,
Able to use `safeAreaLayoutGuide` and `contentLayoutGuide` for the appropriate layout styles. Setting the `contentInsetsAdjustmentBehavior` to `.always` seems to be the correct way to get a UIScrollView to position its content inside the safe area.

2019-07-01 06:14 UTC, romoore approved these changes
I think this works well and the result looks pretty good. I'm not seeing what I'd expect when I apply safe area insets to the bottom of the bar, but those are going to be pretty rare in practice.  It may be simpler in the future to migrate to manual layout for the item views.  At this point, however, I'd say the combination of manual testing and snapshot tests are sufficient to cover the common use cases.

2019-07-01 06:29 UTC, merged

2019-07-01 07:00 UTC, leonmz commented
Thanks a lot for working on this Rob! Appreciate for your time on investigating on this :)