[Snackbar] Add button styling properties to MDCSnackbarManager
material-components/material-components-ios pull request #7832
Opened 2019-07-09 21:02 UTC by bryanoltman

Prework for b/136013556

2019-07-09 21:22 UTC, wenyuzhang666 commented on components/Snackbar/src/MDCSnackbarManager.h
> +@property(nonatomic) BOOL uppercaseButtonTitles;
Nip naming: maybe `uppercaseButtonTitle` to align with the other two property names?

2019-07-09 21:22 UTC, fluxminds requested changes
Left a minor comment.

2019-07-09 21:25 UTC, material-automation commented
bazel detected changes to the following targets:

```
//components/Snackbar:ColorThemer
//components/Snackbar:FontThemer
//components/Snackbar:ObjcExamples
//components/Snackbar:Snackbar
//components/Snackbar:TypographyThemer
//components/Snackbar:snapshot_test_lib
//components/Snackbar:snapshot_tests
//components/Snackbar:snapshot_tests.swift_runtime_linkopts
//components/Snackbar:snapshot_tests_test_binary
//components/Snackbar:snapshot_tests_test_bundle
//components/Snackbar:unit_test_sources
//components/Snackbar:unit_test_swift_sources
//components/Snackbar:unit_tests
//components/Snackbar:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/Snackbar:unit_tests_IPAD_PRO_12_9_IN_9_3.swift_runtime_linkopts
//components/Snackbar:unit_tests_IPAD_PRO_12_9_IN_9_3_test_binary
//components/Snackbar:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/Snackbar:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/Snackbar:unit_tests_IPHONE_7_PLUS_IN_10_3.swift_runtime_linkopts
//components/Snackbar:unit_tests_IPHONE_7_PLUS_IN_10_3_test_binary
//components/Snackbar:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/Snackbar:unit_tests_IPHONE_X_IN_11_0
//components/Snackbar:unit_tests_IPHONE_X_IN_11_0.swift_runtime_linkopts
//components/Snackbar:unit_tests_IPHONE_X_IN_11_0_test_binary
//components/Snackbar:unit_tests_IPHONE_X_IN_11_0_test_bundle
```

<!-- identifier: affected-targets -->

2019-07-09 21:30 UTC, material-automation commented
## API diff detected the following changes

### Snackbar

#### MDCSnackbarManager

*new* property: `uppercaseButtonTitles` in `MDCSnackbarManager`

*new* property: `buttonInkColor` in `MDCSnackbarManager`

*new* property: `disabledButtonAlpha` in `MDCSnackbarManager`

<!-- identifier: apidiff -->

2019-07-09 22:25 UTC, wenyuzhang666 commented on components/Snackbar/tests/unit/MDCSnackbarMessageViewTests.m
> +  self.manager.disabledButtonAlpha = 0.5;
float needs to be casted here.

2019-07-09 22:25 UTC, wenyuzhang666 commented on components/Snackbar/src/MDCSnackbarManager.m
> +    _disabledButtonAlpha = 0.12;
float needs to be casted here.

2019-07-09 23:26 UTC, fluxminds approved these changes

2019-07-09 23:26 UTC, wenyuzhang666 commented on components/Snackbar/src/MDCSnackbarManager.m
> +    _disabledButtonAlpha = 0.12f;
Nip: we usually do `(CGFloat)0.12` more like a convention on the team. `0.12f` is good to use since no precision is lost.

2019-07-09 23:26 UTC, wenyuzhang666 commented on components/Snackbar/tests/unit/MDCSnackbarMessageViewTests.m
> +  self.manager.disabledButtonAlpha = 0.5f;
Nip: same here.

2019-07-10 01:47 UTC, yarneo requested changes
Do you think we may be able to imitate the same flow the `buttonFont` property and others have:
* Consider having for each added property a getter and setter that also allows to apply the change on the already presented snackbar
* In MDCSnackbarMessageView in the initializer the gets the manager, pass the property value to the view.

2019-07-10 01:47 UTC, yarneo commented on components/Snackbar/src/MDCSnackbarManager.h
> +@property(nonatomic) BOOL uppercaseButtonTitle;
we usually explicitly add "assign" to this and the below property

2019-07-10 14:20 UTC, bryanoltman commented
@yarneo With "In MDCSnackbarMessageView in the initializer the gets the manager, pass the property value to the view", are you suggesting adding these three properties to `MDCSnackbarMessageView`'s initializer?

2019-07-10 15:12 UTC, material-automation commented on components/Snackbar/src/MDCSnackbarMessageView.m
> +                                      withManager:manager];
clang-format suggested the following change:


```
-    [self initializeMDCSnackbarMessageViewButtons:message
-                                      withManager:manager];
+    [self initializeMDCSnackbarMessageViewButtons:message withManager:manager];
```

<!-- identifier: clang-format -->
<!-- File: components/Snackbar/src/MDCSnackbarMessageView.m -->

2019-07-10 15:12 UTC, material-automation commented
clang-format recommended changes.

Consider installing [git-clang-format](https://github.com/llvm-mirror/clang/blob/master/tools/clang-format/git-clang-format) and running the following command:

```bash
git clang-format $(git merge-base origin/develop HEAD)
```

<!-- identifier: clang-format -->

2019-07-10 18:55 UTC, yarneo approved these changes

2019-07-10 18:56 UTC, merged