[Collections] Add dynamic color support to Collections
material-components/material-components-ios pull request #7856
Opened 2019-07-10 20:16 UTC by andrewoverton

I'm pretty sure this is very wrong. This is separate from the work that Bryan is doing.

2019-07-10 20:22 UTC, material-automation commented
bazel detected changes to the following targets:

```
//components/Collections:unit_tests
//components/Collections:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/Collections:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/Collections:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/Collections:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/Collections:unit_tests_IPHONE_X_IN_11_0
//components/Collections:unit_tests_IPHONE_X_IN_11_0_test_bundle
```

<!-- identifier: affected-targets -->

2019-07-10 20:22 UTC, material-automation commented
bazel detected changes to the following targets:

```
//catalog:MDCCatalog
//catalog:MDCCatalog.apple_binary
//catalog:MDCCatalog.swift_runtime_linkopts
//catalog:MDCCatalogLib
//components/ActivityIndicator:ObjcExamples
//components/CollectionCells:ObjcExamples
//components/Collections:Collections
//components/Collections:ObjcExamples
//components/Collections:SwiftExamples
//components/Collections:unit_test_sources
//components/Collections:unit_tests
//components/Collections:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/Collections:unit_tests_IPAD_PRO_12_9_IN_9_3.swift_runtime_linkopts
//components/Collections:unit_tests_IPAD_PRO_12_9_IN_9_3_test_binary
//components/Collections:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/Collections:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/Collections:unit_tests_IPHONE_7_PLUS_IN_10_3.swift_runtime_linkopts
//components/Collections:unit_tests_IPHONE_7_PLUS_IN_10_3_test_binary
//components/Collections:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/Collections:unit_tests_IPHONE_X_IN_11_0
//components/Collections:unit_tests_IPHONE_X_IN_11_0.swift_runtime_linkopts
//components/Collections:unit_tests_IPHONE_X_IN_11_0_test_binary
//components/Collections:unit_tests_IPHONE_X_IN_11_0_test_bundle
//components/Dialogs:ObjcExamples
//components/Dialogs:SwiftExamples
//components/FeatureHighlight:ObjcExamples
//components/Slider:ObjcExamples
//components/Snackbar:ObjcExamples
//components/Tabs:ObjcExamples
```

<!-- identifier: affected-targets -->

2019-07-11 12:30 UTC, romoore commented on components/Collections/src/private/MDCCollectionInfoBarView.m
> +  CGFloat white = 0.0f;
Please use either an explicit cast to `(CGFloat)` or use integral values (my preferred option).

```objc
CGFloat white = 0;
white = 1;

// Alternatively
CGFloat white = (CGFloat)0.0;
white = (CGFloat)1.0;
```

2019-07-11 12:33 UTC, romoore requested changes
Small nits in the main code. However, requesting changes because there seem to be no affected tests. At a minimum, please add snapshot tests for this view for this property change.  It looks like unit tests might be possible, but perhaps harder to read/write.

2019-07-11 12:33 UTC, romoore commented on components/Collections/src/private/MDCCollectionInfoBarView.m
> +  _backgroundBorderLayer.borderWidth = 1 / [[UIScreen mainScreen] scale];
Please use `self.window.screen.scale`. Do not rely on the main screen's scale.

2019-07-11 12:58 UTC, romoore commented
Please feel free to dismiss my Changes Requested once the tests have been added.

2019-07-11 13:02 UTC, yarneo reviewed
Andrew and I talked about this offline; the component implementation shouldn't be the one setting a color that reacts to dark mode, but rather it should expose this property so that the color scheme can correctly be applied to this element as well.

However, because Collections don't have any sort of themer/theming/etc, and is a "to be deprecated" component, there isn't much value to start doing all this leg work to make Collections compatible with new features at this time.

2019-07-11 17:06 UTC, andrewoverton commented
Closing this after discussion in today's standup

2019-07-11 17:06 UTC, closed without merging