[BottomAppBar] Add conformance to MDCElevatable, MDCElevationOverriding
material-components/material-components-ios pull request #8094
Opened 2019-07-25 19:59 UTC by bryanoltman

Adds Bottom App Bar conformance to `MDCElevatable` `MDCElevationOverriding`. Note that the bottom app bar view's shadow is not using `MDCShapedShadowLayer`. I explored this in #8092, but the work required to adapt `MDCBottomAppBarLayer` seemed out-of-scope.

Closes #8027

2019-07-25 20:01 UTC, material-automation commented
bazel detected changes to the following targets:

```
//components/BottomAppBar:BottomAppBar
//components/BottomAppBar:ColorThemer
//components/BottomAppBar:ObjcExamples
//components/BottomAppBar:SwiftExamples
//components/BottomAppBar:snapshot_test_lib
//components/BottomAppBar:snapshot_tests
//components/BottomAppBar:snapshot_tests.swift_runtime_linkopts
//components/BottomAppBar:snapshot_tests_test_binary
//components/BottomAppBar:snapshot_tests_test_bundle
//components/BottomAppBar:unit_test_sources
//components/BottomAppBar:unit_tests
//components/BottomAppBar:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/BottomAppBar:unit_tests_IPAD_PRO_12_9_IN_9_3.swift_runtime_linkopts
//components/BottomAppBar:unit_tests_IPAD_PRO_12_9_IN_9_3_test_binary
//components/BottomAppBar:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/BottomAppBar:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/BottomAppBar:unit_tests_IPHONE_7_PLUS_IN_10_3.swift_runtime_linkopts
//components/BottomAppBar:unit_tests_IPHONE_7_PLUS_IN_10_3_test_binary
//components/BottomAppBar:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/BottomAppBar:unit_tests_IPHONE_X_IN_11_0
//components/BottomAppBar:unit_tests_IPHONE_X_IN_11_0.swift_runtime_linkopts
//components/BottomAppBar:unit_tests_IPHONE_X_IN_11_0_test_binary
//components/BottomAppBar:unit_tests_IPHONE_X_IN_11_0_test_bundle
//components/NavigationDrawer:SwiftExamples
```

<!-- identifier: affected-targets -->

2019-07-25 20:05 UTC, material-automation commented
## API diff detected the following changes

### BottomAppBar

#### MDCBottomAppBarView

*new* property: `mdc_elevationDidChangeBlock` in `MDCBottomAppBarView`

*new* property: `elevation` in `MDCBottomAppBarView`

<!-- identifier: apidiff -->

2019-07-26 04:00 UTC, codeman7 approved these changes
Please update the shadow elevation value before merging.

2019-07-26 04:00 UTC, codeman7 commented on components/BottomAppBar/src/MDCBottomAppBarView.h
> +    (MDCBottomAppBarView *_Nonnull object, CGFloat elevation);
_Tip_: Change `object` to `bottomAppBar`

2019-07-26 04:00 UTC, codeman7 commented on components/BottomAppBar/src/MDCBottomAppBarView.h
> + The elevation of the bottom app bar. Defaults to @c MDCShadowElevationBottomNavigationBar.
Can we add MDCShadowElevationBottomAppBar and make that the default?

2019-07-26 13:43 UTC, romoore requested changes
Requesting changes because calling setters with side-effects in `init` is potentially dangerous.

2019-07-26 13:43 UTC, romoore commented on components/BottomAppBar/src/MDCBottomAppBarView.m
> +  self.elevation = MDCShadowElevationBottomNavigationBar;
Please assign the elevation to the ivar directly. Accessing `self` in an initializer is discouraged.  In this case, `setElevation:` calls out to the category method and triggers a bunch of other code.

```objc
_elevation = MDCShadowElevationBottomNavigationBar;
```

2019-07-26 13:43 UTC, romoore commented on components/BottomAppBar/src/MDCBottomAppBarView.m
> +  if (elevation == _elevation) {
Please use `MDCCGFloatEqual()`. Two floats that are very close to one another (but not exactly the same) wouldn't warrant invoking the block below.

2019-07-26 13:43 UTC, romoore commented on components/BottomAppBar/tests/unit/BottomAppBarTests.m
> +- (void)testElevationDidChangeBlockCalledWhenElevationChangesValue {
Please add a test that the default value of `mdc_baseElevation` is negative.

2019-07-26 18:17 UTC, romoore approved these changes

2019-07-26 18:49 UTC, merged