[Buttons] Add missing self to traitCollectionDidChangeBlock
material-components/material-components-ios pull request #8276
Opened 2019-08-09 19:12 UTC by yarneo

As part of our work of adding traitCollectionDidChangeBlocks to components, we add self as a parameter to the block, buttons is the only component that seems to be missing it.

This is essentially a breaking change based on our breaking changes conventions.

2019-08-09 19:19 UTC, fluxminds requested changes

2019-08-09 19:19 UTC, wenyuzhang666 commented on components/Buttons/tests/unit/MDCButtonTests.m
> +  button.traitCollectionDidChangeBlock = ^(MDCButton *_Nonnull b, UITraitCollection *_Nullable previousTraitCollection) {
We usually add a `passedButton` in the test here to verify `self` is passed in.

2019-08-09 19:24 UTC, material-automation commented
bazel detected changes to the following targets:

```
//catalog:MDCCatalog
//catalog:MDCCatalog.apple_binary
//catalog:MDCCatalog.swift_runtime_linkopts
//catalog:MDCCatalogLib
//catalog:MDCDragons
//catalog:MDCDragons.apple_binary
//catalog:MDCDragons.swift_runtime_linkopts
//catalog:MDCDragonsLib
//components/ActionSheet:ObjcExamples
//components/ActivityIndicator:ObjcExamples
//components/AppBar:AppBar
//components/AppBar:ColorThemer
//components/AppBar:ObjcExamples
//components/AppBar:SwiftExamples
//components/AppBar:Theming
//components/AppBar:TypographyThemer
//components/AppBar:snapshot_test_lib
//components/AppBar:snapshot_tests
//components/AppBar:snapshot_tests.swift_runtime_linkopts
//components/AppBar:snapshot_tests_test_binary
//components/AppBar:snapshot_tests_test_bundle
//components/AppBar:unit_test_sources
//components/AppBar:unit_test_swift_sources
//components/AppBar:unit_tests
//components/AppBar:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/AppBar:unit_tests_IPAD_PRO_12_9_IN_9_3.swift_runtime_linkopts
//components/AppBar:unit_tests_IPAD_PRO_12_9_IN_9_3_test_binary
//components/AppBar:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/AppBar:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/AppBar:unit_tests_IPHONE_7_PLUS_IN_10_3.swift_runtime_linkopts
//components/AppBar:unit_tests_IPHONE_7_PLUS_IN_10_3_test_binary
//components/AppBar:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/AppBar:unit_tests_environment
//components/AppBar:unit_tests_environment.swift_runtime_linkopts
//components/AppBar:unit_tests_environment_test_binary
//components/AppBar:unit_tests_environment_test_bundle
//components/Banner:Banner
//components/Banner:ObjcExamples
//components/Banner:snapshot_test_lib
//components/Banner:snapshot_tests
//components/Banner:snapshot_tests.swift_runtime_linkopts
//components/Banner:snapshot_tests_test_binary
//components/Banner:snapshot_tests_test_bundle
//components/Banner:unit_test_sources
//components/Banner:unit_tests
//components/Banner:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/Banner:unit_tests_IPAD_PRO_12_9_IN_9_3.swift_runtime_linkopts
//components/Banner:unit_tests_IPAD_PRO_12_9_IN_9_3_test_binary
//components/Banner:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/Banner:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/Banner:unit_tests_IPHONE_7_PLUS_IN_10_3.swift_runtime_linkopts
//components/Banner:unit_tests_IPHONE_7_PLUS_IN_10_3_test_binary
//components/Banner:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/Banner:unit_tests_environment
//components/Banner:unit_tests_environment.swift_runtime_linkopts
//components/Banner:unit_tests_environment_test_binary
//components/Banner:unit_tests_environment_test_bundle
//components/BottomAppBar:BottomAppBar
//components/BottomAppBar:ColorThemer
//components/BottomAppBar:ObjcExamples
//components/BottomAppBar:SwiftExamples
//components/BottomAppBar:snapshot_test_lib
//components/BottomAppBar:snapshot_tests
//components/BottomAppBar:snapshot_tests.swift_runtime_linkopts
//components/BottomAppBar:snapshot_tests_test_binary
//components/BottomAppBar:snapshot_tests_test_bundle
//components/BottomAppBar:unit_test_sources
//components/BottomAppBar:unit_tests
//components/BottomAppBar:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/BottomAppBar:unit_tests_IPAD_PRO_12_9_IN_9_3.swift_runtime_linkopts
//components/BottomAppBar:unit_tests_IPAD_PRO_12_9_IN_9_3_test_binary
//components/BottomAppBar:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/BottomAppBar:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/BottomAppBar:unit_tests_IPHONE_7_PLUS_IN_10_3.swift_runtime_linkopts
//components/BottomAppBar:unit_tests_IPHONE_7_PLUS_IN_10_3_test_binary
//components/BottomAppBar:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/BottomAppBar:unit_tests_environment
//components/BottomAppBar:unit_tests_environment.swift_runtime_linkopts
//components/BottomAppBar:unit_tests_environment_test_binary
//components/BottomAppBar:unit_tests_environment_test_bundle
//components/BottomNavigation:SwiftExamples
//components/BottomSheet:ObjcExamples
//components/BottomSheet:SwiftExamples
//components/ButtonBar:ButtonBar
//components/ButtonBar:ColorThemer
//components/ButtonBar:ObjcExamples
//components/ButtonBar:SwiftExamples
//components/ButtonBar:Theming
//components/ButtonBar:TypographyThemer
//components/ButtonBar:snapshot_test_lib
//components/ButtonBar:snapshot_tests
//components/ButtonBar:snapshot_tests.swift_runtime_linkopts
//components/ButtonBar:snapshot_tests_test_binary
//components/ButtonBar:snapshot_tests_test_bundle
//components/ButtonBar:unit_test_sources
//components/ButtonBar:unit_test_swift_sources
//components/ButtonBar:unit_tests
//components/ButtonBar:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/ButtonBar:unit_tests_IPAD_PRO_12_9_IN_9_3.swift_runtime_linkopts
//components/ButtonBar:unit_tests_IPAD_PRO_12_9_IN_9_3_test_binary
//components/ButtonBar:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/ButtonBar:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/ButtonBar:unit_tests_IPHONE_7_PLUS_IN_10_3.swift_runtime_linkopts
//components/ButtonBar:unit_tests_IPHONE_7_PLUS_IN_10_3_test_binary
//components/ButtonBar:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/ButtonBar:unit_tests_environment
//components/ButtonBar:unit_tests_environment.swift_runtime_linkopts
//components/ButtonBar:unit_tests_environment_test_binary
//components/ButtonBar:unit_tests_environment_test_bundle
//components/Buttons:ButtonThemer
//components/Buttons:Buttons
//components/Buttons:ColorThemer
//components/Buttons:ObjcExamples
//components/Buttons:ShapeThemer
//components/Buttons:SwiftExamples
//components/Buttons:Theming
//components/Buttons:TitleColorAccessibilityMutator
//components/Buttons:TypographyThemer
//components/Buttons:snapshot_test_lib
//components/Buttons:snapshot_tests
//components/Buttons:snapshot_tests.swift_runtime_linkopts
//components/Buttons:snapshot_tests_test_binary
//components/Buttons:snapshot_tests_test_bundle
//components/Buttons:unit_test_sources
//components/Buttons:unit_test_swift_sources
//components/Buttons:unit_tests
//components/Buttons:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/Buttons:unit_tests_IPAD_PRO_12_9_IN_9_3.swift_runtime_linkopts
//components/Buttons:unit_tests_IPAD_PRO_12_9_IN_9_3_test_binary
//components/Buttons:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/Buttons:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/Buttons:unit_tests_IPHONE_7_PLUS_IN_10_3.swift_runtime_linkopts
//components/Buttons:unit_tests_IPHONE_7_PLUS_IN_10_3_test_binary
//components/Buttons:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/Buttons:unit_tests_environment
//components/Buttons:unit_tests_environment.swift_runtime_linkopts
//components/Buttons:unit_tests_environment_test_binary
//components/Buttons:unit_tests_environment_test_bundle
//components/Cards:SwiftExamples
//components/Dialogs:ColorThemer
//components/Dialogs:DialogThemer
//components/Dialogs:Dialogs
//components/Dialogs:ObjcExamples
//components/Dialogs:SwiftExamples
//components/Dialogs:Theming
//components/Dialogs:TypographyThemer
//components/Dialogs:snapshot_test_lib
//components/Dialogs:snapshot_tests
//components/Dialogs:snapshot_tests.swift_runtime_linkopts
//components/Dialogs:snapshot_tests_test_binary
//components/Dialogs:snapshot_tests_test_bundle
//components/Dialogs:unit_test_sources
//components/Dialogs:unit_test_swift_sources
//components/Dialogs:unit_tests
//components/Dialogs:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/Dialogs:unit_tests_IPAD_PRO_12_9_IN_9_3.swift_runtime_linkopts
//components/Dialogs:unit_tests_IPAD_PRO_12_9_IN_9_3_test_binary
//components/Dialogs:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/Dialogs:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/Dialogs:unit_tests_IPHONE_7_PLUS_IN_10_3.swift_runtime_linkopts
//components/Dialogs:unit_tests_IPHONE_7_PLUS_IN_10_3_test_binary
//components/Dialogs:unit_tests_I [...]

2019-08-09 19:24 UTC, material-automation commented
bazel detected changes to the following targets:

```
//components/AppBar:snapshot_tests
//components/AppBar:snapshot_tests_test_bundle
//components/AppBar:unit_tests
//components/AppBar:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/AppBar:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/AppBar:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/AppBar:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/AppBar:unit_tests_environment
//components/AppBar:unit_tests_environment_test_bundle
//components/Banner:snapshot_tests
//components/Banner:snapshot_tests_test_bundle
//components/Banner:unit_tests
//components/Banner:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/Banner:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/Banner:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/Banner:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/Banner:unit_tests_environment
//components/Banner:unit_tests_environment_test_bundle
//components/BottomAppBar:snapshot_tests
//components/BottomAppBar:snapshot_tests_test_bundle
//components/BottomAppBar:unit_tests
//components/BottomAppBar:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/BottomAppBar:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/BottomAppBar:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/BottomAppBar:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/BottomAppBar:unit_tests_environment
//components/BottomAppBar:unit_tests_environment_test_bundle
//components/ButtonBar:snapshot_tests
//components/ButtonBar:snapshot_tests_test_bundle
//components/ButtonBar:unit_tests
//components/ButtonBar:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/ButtonBar:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/ButtonBar:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/ButtonBar:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/ButtonBar:unit_tests_environment
//components/ButtonBar:unit_tests_environment_test_bundle
//components/Buttons:snapshot_tests
//components/Buttons:snapshot_tests_test_bundle
//components/Buttons:unit_tests
//components/Buttons:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/Buttons:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/Buttons:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/Buttons:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/Buttons:unit_tests_environment
//components/Buttons:unit_tests_environment_test_bundle
//components/Dialogs:snapshot_tests
//components/Dialogs:snapshot_tests_test_bundle
//components/Dialogs:unit_tests
//components/Dialogs:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/Dialogs:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/Dialogs:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/Dialogs:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/Dialogs:unit_tests_environment
//components/Dialogs:unit_tests_environment_test_bundle
//components/NavigationBar:snapshot_tests
//components/NavigationBar:snapshot_tests_test_bundle
//components/NavigationBar:unit_tests
//components/NavigationBar:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/NavigationBar:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/NavigationBar:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/NavigationBar:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/NavigationBar:unit_tests_environment
//components/NavigationBar:unit_tests_environment_test_bundle
//components/Snackbar:snapshot_tests
//components/Snackbar:snapshot_tests_test_bundle
//components/Snackbar:unit_tests
//components/Snackbar:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/Snackbar:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/Snackbar:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/Snackbar:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/Snackbar:unit_tests_environment
//components/Snackbar:unit_tests_environment_test_bundle
//components/Tabs:snapshot_tests
//components/Tabs:snapshot_tests_test_bundle
```

<!-- identifier: affected-targets -->

2019-08-09 19:30 UTC, material-automation commented
## API diff detected the following changes

### Buttons

#### MDCButton

*modified* property: `traitCollectionDidChangeBlock` in `MDCButton`

| Type of change: | Swift declaration |
|---|---|
| From: | `var traitCollectionDidChangeBlock: ((UITraitCollection?) -> Void)? { get set }` |
| To: | `var traitCollectionDidChangeBlock: ((MDCButton, UITraitCollection?) -> Void)? { get set }` |

*modified* property: `traitCollectionDidChangeBlock` in `MDCButton`

| Type of change: | Declaration |
|---|---|
| From: | `@property (readwrite, copy, nonatomic, nullable) void (^)     (UITraitCollection *_Nullable) traitCollectionDidChangeBlock;` |
| To: | `@property (readwrite, copy, nonatomic, nullable) void (^)     (MDCButton *_Nonnull, UITraitCollection *_Nullable)         traitCollectionDidChangeBlock;` |

<!-- identifier: apidiff -->

2019-08-09 19:42 UTC, wenyuzhang666 commented on components/Buttons/tests/unit/MDCButtonTests.m
> +        [expectation fulfill];
Sorry. I should have make a code snippet here like https://github.com/material-components/material-components-ios/blob/develop/components/Dialogs/tests/unit/MDCDialogPresentationControllerTests.m#L36

```
__block MDCButton *passButton;
...{
   passedButton = b;
   [expectation fulfill];
}
XCTAssertEqual(passedButton, button);
```

2019-08-10 15:12 UTC, fluxminds approved these changes

2019-08-12 14:30 UTC, romoore approved these changes

2019-08-12 14:50 UTC, merged