[FeatureHighlight] Add missing test for Dynamic Type and mark mdc_legacyFontScaling deprecated.
material-components/material-components-ios pull request #8309
Opened 2019-08-13 19:29 UTC by wenyuzhang666

Part of https://github.com/material-components/material-components-ios/issues/8304.

2019-08-13 19:31 UTC, jverkoey commented
The pr looks like it’s adding a new api; please update the PR description accordingly.

2019-08-13 19:53 UTC, material-automation commented
bazel detected changes to the following targets:

```
//components/FeatureHighlight:unit_tests
//components/FeatureHighlight:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/FeatureHighlight:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/FeatureHighlight:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/FeatureHighlight:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/FeatureHighlight:unit_tests_environment
//components/FeatureHighlight:unit_tests_environment_test_bundle
```

<!-- identifier: affected-targets -->

2019-08-13 19:59 UTC, material-automation commented
## API diff detected the following changes

### FeatureHighlight

#### MDCFeatureHighlightView

*new* property: `adjustsFontForContentSizeCategoryWhenScaledFontIsUnavailable` in `MDCFeatureHighlightView`

*modified* property: `mdc_legacyFontScaling` in `MDCFeatureHighlightView`

| Type of change: | Deprecation |
|---|---|
| From: | `0` |
| To: | `1` |

*modified* class: `MDCFeatureHighlightView`

| Type of change: | Declaration |
|---|---|
| From: | `@interface MDCFeatureHighlightView : UIView  @property(nonatomic, strong, nullable) UIColor *innerHighlightColor UI_APPEARANCE_SELECTOR; @property(nonatomic, strong, nullable) UIColor *outerHighlightColor UI_APPEARANCE_SELECTOR;  @property(nonatomic, strong, nullable) UIFont *titleFont UI_APPEARANCE_SELECTOR; @property(nonatomic, strong, nullable) UIColor *titleColor UI_APPEARANCE_SELECTOR;  @property(nonatomic, strong, nullable) UIFont *bodyFont UI_APPEARANCE_SELECTOR; @property(nonatomic, strong, nullable) UIColor *bodyColor UI_APPEARANCE_SELECTOR;  /*  Indicates whether the view's contents should automatically update their font when the device’s  UIContentSizeCategory changes.   This property is modeled after the adjustsFontForContentSizeCategory property in the  UIContentSizeCategoryAdjusting protocol added by Apple in iOS 10.0.   Default value is NO.  */ @property(nonatomic, readwrite, setter=mdc_setAdjustsFontForContentSizeCategory:)     BOOL mdc_adjustsFontForContentSizeCategory UI_APPEARANCE_SELECTOR;  /**  Enable legacy font scaling curves for Dynamic Type  Default value is NO.  */ @property(nonatomic, readwrite, setter=mdc_setLegacyFontScaling:) BOOL mdc_legacyFontScaling;  /**  A block that is invoked when the @c MDCFeatureHighlightView receives a call to @c  traitCollectionDidChange:. The block is called after the call to the superclass.  */ @property(nonatomic, copy, nullable) void (^traitCollectionDidChangeBlock)     (MDCFeatureHighlightView *_Nonnull featureHighlight,      UITraitCollection *_Nullable previousTraitCollection);  @end` |
| To: | `@interface MDCFeatureHighlightView : UIView  @property(nonatomic, strong, nullable) UIColor *innerHighlightColor UI_APPEARANCE_SELECTOR; @property(nonatomic, strong, nullable) UIColor *outerHighlightColor UI_APPEARANCE_SELECTOR;  @property(nonatomic, strong, nullable) UIFont *titleFont UI_APPEARANCE_SELECTOR; @property(nonatomic, strong, nullable) UIColor *titleColor UI_APPEARANCE_SELECTOR;  @property(nonatomic, strong, nullable) UIFont *bodyFont UI_APPEARANCE_SELECTOR; @property(nonatomic, strong, nullable) UIColor *bodyColor UI_APPEARANCE_SELECTOR;  /*  Indicates whether the view's contents should automatically update their font when the device’s  UIContentSizeCategory changes.   This property is modeled after the adjustsFontForContentSizeCategory property in the  UIContentSizeCategoryAdjusting protocol added by Apple in iOS 10.0.   Default value is NO.  */ @property(nonatomic, readwrite, setter=mdc_setAdjustsFontForContentSizeCategory:)     BOOL mdc_adjustsFontForContentSizeCategory UI_APPEARANCE_SELECTOR;  /**  Enable legacy font scaling curves for Dynamic Type  Default value is NO.  */ @property(nonatomic, readwrite, setter=mdc_setLegacyFontScaling:)     BOOL mdc_legacyFontScaling __deprecated;  /**  Affects the fallback behavior for when a scaled font is not provided.  If enabled, the font size will adjust even if a scaled font has not been provided for  a given UIFont property on this component.  If disabled, the font size will only be adjusted if a scaled font has been provided.  This behavior most closely matches UIKit's.  Default value is YES, but this flag will eventually default to NO and then be deprecated  and deleted.  */ @property(nonatomic, assign) BOOL adjustsFontForContentSizeCategoryWhenScaledFontIsUnavailable;  /**  A block that is invoked when the @c MDCFeatureHighlightView receives a call to @c  traitCollectionDidChange:. The block is called after the call to the superclass.  */ @property(nonatomic, copy, nullable) void (^traitCollectionDidChangeBlock)     (MDCFeatureHighlightView *_Nonnull featureHighlight,      UITraitCollection *_Nullable previousTraitCollection);  @end` |

#### MDCFeatureHighlightViewController

*new* property: `adjustsFontForContentSizeCategoryWhenScaledFontIsUnavailable` in `MDCFeatureHighlightViewController`

*modified* property: `mdc_legacyFontScaling` in `MDCFeatureHighlightViewController`

| Type of change: | Deprecation |
|---|---|
| From: | `0` |
| To: | `1` |

<!-- identifier: apidiff -->

2019-08-14 13:13 UTC, romoore requested changes
This PR looks like two semi-related changes based on how I'm reading it.  I believe it should be split into two PRs.

1.  Introduce the new `adjustsFontForContentSizeCategoryWhenScaledFontIsUnavailable` API and deprecate `mdc_legacyFontScaling`. I'm concerned that they are currently not backed by the same instance variable and the interaction of the two APIs is confusing based on how I read the public header documentation. This may just be a matter of documentation, but it will help me to see the unit tests to better understand the behavior.
2. It changes the M2 scaling curves to use `mdc_scaledFontForTraitEnvironment:self` rather than `mdc_scaledFontForCurrentSizeCategory`. While this is a rather minor change, it is not necessary for the new API and if the other change needs to be rolled-back, this refactoring would be lost.

2019-08-14 13:13 UTC, romoore commented on components/FeatureHighlight/src/MDCFeatureHighlightViewController.h
> +    BOOL mdc_legacyFontScaling __deprecated;
Please use `__deprecated_msg("Use blah blah API instead")` to mark deprecated APIs that have replacements.

2019-08-14 13:13 UTC, romoore commented on components/FeatureHighlight/src/MDCFeatureHighlightViewController.h
> +    BOOL mdc_legacyFontScaling __deprecated;
Should this pass-through to the new API? That way they both have the same values? If not, it seems like you have to add temporary code to check their states and the interaction seems non-trivial.

If `mdc_legacyFontScaling` is `YES` but `adjustsFontForContentSizeCategoryWhenScaledFontIsUnavailable` is `NO`, should you use the fall-back scaling or not?

2019-08-14 13:13 UTC, romoore commented on components/FeatureHighlight/tests/unit/FeatureHighlightViewControllerTests.m
> +- (void)testFeatureHighlightViewControllerDynamicTypeBehavior {
Please add tests that assert the behavior of the intersection of the two APIs.  It's not clear to me how they would work together given their independent storage in the current version of this PR.

| adjustsFontForContentSizeCategoryWhenScaledFontIsUnavailable | mdc_legacyFontScaling | Font Scaling Type|
|---|---|---|
|N | N | N |
|N | Y | ?? |
|Y | N | ?? |
|Y | Y | Y |

2019-08-14 13:13 UTC, romoore commented on components/FeatureHighlight/tests/unit/FeatureHighlightViewControllerTests.m
> +- (void)testFeatureHighlightViewControllerDynamicTypeBehavior {
Please add a test for the new API's default value.

2019-08-14 13:13 UTC, romoore commented on components/FeatureHighlight/src/private/MDCFeatureHighlightView+Private.m
> +      bodyFont = [bodyFont mdc_scaledFontForTraitEnvironment:self];
Do we need to set the font twice here [due to the way `UILabel` attempts to optimize `UIFont` setting](https://github.com/material-components/material-components-ios/issues/7424)?

2019-09-10 14:06 UTC, jverkoey commented
Closing this due to inactivity, but please reopen if we intend to pursue it again.

2019-09-10 14:06 UTC, closed without merging