[Buttons] overwrite intrinsicContentSize method.
material-components/material-components-ios pull request #8370
Opened 2019-08-26 20:28 UTC by fluxminds

The `instrinsicContentSize` of `MDCButton` was not aware of `minimumSize` property, which is wrong.

Open to use `super.instrinsicContentSize` if reviewer(s) prefer.

2019-08-26 20:32 UTC, material-automation commented
bazel detected changes to the following targets:

```
//catalog:MDCCatalog
//catalog:MDCCatalog.apple_binary
//catalog:MDCCatalog.swift_runtime_linkopts
//catalog:MDCCatalogLib
//catalog:MDCDragons
//catalog:MDCDragons.apple_binary
//catalog:MDCDragons.swift_runtime_linkopts
//catalog:MDCDragonsLib
//components/ActionSheet:ObjcExamples
//components/ActivityIndicator:ObjcExamples
//components/AppBar:AppBar
//components/AppBar:ColorThemer
//components/AppBar:ObjcExamples
//components/AppBar:SwiftExamples
//components/AppBar:Theming
//components/AppBar:TypographyThemer
//components/AppBar:snapshot_test_lib
//components/AppBar:snapshot_tests
//components/AppBar:snapshot_tests.swift_runtime_linkopts
//components/AppBar:snapshot_tests_test_binary
//components/AppBar:snapshot_tests_test_bundle
//components/AppBar:unit_test_sources
//components/AppBar:unit_test_swift_sources
//components/AppBar:unit_tests
//components/AppBar:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/AppBar:unit_tests_IPAD_PRO_12_9_IN_9_3.swift_runtime_linkopts
//components/AppBar:unit_tests_IPAD_PRO_12_9_IN_9_3_test_binary
//components/AppBar:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/AppBar:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/AppBar:unit_tests_IPHONE_7_PLUS_IN_10_3.swift_runtime_linkopts
//components/AppBar:unit_tests_IPHONE_7_PLUS_IN_10_3_test_binary
//components/AppBar:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/AppBar:unit_tests_environment
//components/AppBar:unit_tests_environment.swift_runtime_linkopts
//components/AppBar:unit_tests_environment_test_binary
//components/AppBar:unit_tests_environment_test_bundle
//components/Banner:Banner
//components/Banner:ObjcExamples
//components/Banner:Theming
//components/Banner:snapshot_test_lib
//components/Banner:snapshot_tests
//components/Banner:snapshot_tests.swift_runtime_linkopts
//components/Banner:snapshot_tests_test_binary
//components/Banner:snapshot_tests_test_bundle
//components/Banner:unit_test_sources
//components/Banner:unit_tests
//components/Banner:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/Banner:unit_tests_IPAD_PRO_12_9_IN_9_3.swift_runtime_linkopts
//components/Banner:unit_tests_IPAD_PRO_12_9_IN_9_3_test_binary
//components/Banner:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/Banner:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/Banner:unit_tests_IPHONE_7_PLUS_IN_10_3.swift_runtime_linkopts
//components/Banner:unit_tests_IPHONE_7_PLUS_IN_10_3_test_binary
//components/Banner:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/Banner:unit_tests_environment
//components/Banner:unit_tests_environment.swift_runtime_linkopts
//components/Banner:unit_tests_environment_test_binary
//components/Banner:unit_tests_environment_test_bundle
//components/BottomAppBar:BottomAppBar
//components/BottomAppBar:ColorThemer
//components/BottomAppBar:ObjcExamples
//components/BottomAppBar:SwiftExamples
//components/BottomAppBar:snapshot_test_lib
//components/BottomAppBar:snapshot_tests
//components/BottomAppBar:snapshot_tests.swift_runtime_linkopts
//components/BottomAppBar:snapshot_tests_test_binary
//components/BottomAppBar:snapshot_tests_test_bundle
//components/BottomAppBar:unit_test_sources
//components/BottomAppBar:unit_tests
//components/BottomAppBar:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/BottomAppBar:unit_tests_IPAD_PRO_12_9_IN_9_3.swift_runtime_linkopts
//components/BottomAppBar:unit_tests_IPAD_PRO_12_9_IN_9_3_test_binary
//components/BottomAppBar:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/BottomAppBar:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/BottomAppBar:unit_tests_IPHONE_7_PLUS_IN_10_3.swift_runtime_linkopts
//components/BottomAppBar:unit_tests_IPHONE_7_PLUS_IN_10_3_test_binary
//components/BottomAppBar:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/BottomAppBar:unit_tests_environment
//components/BottomAppBar:unit_tests_environment.swift_runtime_linkopts
//components/BottomAppBar:unit_tests_environment_test_binary
//components/BottomAppBar:unit_tests_environment_test_bundle
//components/BottomNavigation:SwiftExamples
//components/BottomSheet:ObjcExamples
//components/BottomSheet:SwiftExamples
//components/ButtonBar:ButtonBar
//components/ButtonBar:ColorThemer
//components/ButtonBar:ObjcExamples
//components/ButtonBar:SwiftExamples
//components/ButtonBar:Theming
//components/ButtonBar:TypographyThemer
//components/ButtonBar:snapshot_test_lib
//components/ButtonBar:snapshot_tests
//components/ButtonBar:snapshot_tests.swift_runtime_linkopts
//components/ButtonBar:snapshot_tests_test_binary
//components/ButtonBar:snapshot_tests_test_bundle
//components/ButtonBar:unit_test_sources
//components/ButtonBar:unit_test_swift_sources
//components/ButtonBar:unit_tests
//components/ButtonBar:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/ButtonBar:unit_tests_IPAD_PRO_12_9_IN_9_3.swift_runtime_linkopts
//components/ButtonBar:unit_tests_IPAD_PRO_12_9_IN_9_3_test_binary
//components/ButtonBar:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/ButtonBar:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/ButtonBar:unit_tests_IPHONE_7_PLUS_IN_10_3.swift_runtime_linkopts
//components/ButtonBar:unit_tests_IPHONE_7_PLUS_IN_10_3_test_binary
//components/ButtonBar:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/ButtonBar:unit_tests_IPHONE_X_IN_11_0
//components/ButtonBar:unit_tests_IPHONE_X_IN_11_0.swift_runtime_linkopts
//components/ButtonBar:unit_tests_IPHONE_X_IN_11_0_test_binary
//components/ButtonBar:unit_tests_IPHONE_X_IN_11_0_test_bundle
//components/Buttons:ButtonThemer
//components/Buttons:Buttons
//components/Buttons:ColorThemer
//components/Buttons:ObjcExamples
//components/Buttons:ShapeThemer
//components/Buttons:SwiftExamples
//components/Buttons:Theming
//components/Buttons:TitleColorAccessibilityMutator
//components/Buttons:TypographyThemer
//components/Buttons:snapshot_test_lib
//components/Buttons:snapshot_tests
//components/Buttons:snapshot_tests.swift_runtime_linkopts
//components/Buttons:snapshot_tests_test_binary
//components/Buttons:snapshot_tests_test_bundle
//components/Buttons:unit_test_sources
//components/Buttons:unit_test_swift_sources
//components/Buttons:unit_tests
//components/Buttons:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/Buttons:unit_tests_IPAD_PRO_12_9_IN_9_3.swift_runtime_linkopts
//components/Buttons:unit_tests_IPAD_PRO_12_9_IN_9_3_test_binary
//components/Buttons:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/Buttons:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/Buttons:unit_tests_IPHONE_7_PLUS_IN_10_3.swift_runtime_linkopts
//components/Buttons:unit_tests_IPHONE_7_PLUS_IN_10_3_test_binary
//components/Buttons:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/Buttons:unit_tests_environment
//components/Buttons:unit_tests_environment.swift_runtime_linkopts
//components/Buttons:unit_tests_environment_test_binary
//components/Buttons:unit_tests_environment_test_bundle
//components/Cards:SwiftExamples
//components/Dialogs:ColorThemer
//components/Dialogs:DialogThemer
//components/Dialogs:Dialogs
//components/Dialogs:ObjcExamples
//components/Dialogs:SwiftExamples
//components/Dialogs:Theming
//components/Dialogs:TypographyThemer
//components/Dialogs:snapshot_test_lib
//components/Dialogs:snapshot_tests
//components/Dialogs:snapshot_tests.swift_runtime_linkopts
//components/Dialogs:snapshot_tests_test_binary
//components/Dialogs:snapshot_tests_test_bundle
//components/Dialogs:unit_test_sources
//components/Dialogs:unit_test_swift_sources
//components/Dialogs:unit_tests
//components/Dialogs:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/Dialogs:unit_tests_IPAD_PRO_12_9_IN_9_3.swift_runtime_linkopts
//components/Dialogs:unit_tests_IPAD_PRO_12_9_IN_9_3_test_binary
//components/Dialogs:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/Dialogs:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/Dialogs:unit_tests_IPHONE_7_PLUS_IN_10_3.swift_runtime_linkopts
//components/Dialogs:unit_tests_IPHONE_7_PLUS_IN_10 [...]

2019-08-27 01:03 UTC, romoore requested changes
Please add tests for the new behavior.

2019-08-27 03:20 UTC, fluxminds commented
Added tests and removed WIP from title.

2019-08-27 13:35 UTC, randallli approved these changes

2019-08-27 15:30 UTC, romoore approved these changes

2019-08-27 15:30 UTC, romoore commented on components/Buttons/tests/unit/MDCButtonTests.m
> +- (void)testIntrinsicContentSizeWithMinimum {
Tip: Please describe the "outcome" in the test name.  Here and in the others.

2019-08-27 15:47 UTC, fluxminds commented on components/Buttons/tests/unit/MDCButtonTests.m
> +- (void)testIntrinsicContentSizeWithMinimum {
Addressed in df99798

2019-08-27 17:20 UTC, merged