[TextField] Added check on textinput.font set to avoid sideeffects
material-components/material-components-ios pull request #8391
Opened 2019-09-04 06:13 UTC by ggdiez

This PR should be fix this issue: https://github.com/material-components/material-components-ios/issues/8390
#8390 

This PR is part of code of closed PR hadn't merge anymore. #5810

This code only change the font in this method when is different. Doing that we avoid that font size change while the user is typing on textfields.

2019-09-04 12:27 UTC, romoore requested changes
Please provide greater detail about why assigning an identical font can cause unexpected side-effects. It  seems like the correct fix might actually be in MDCTextField and not the controller.

2019-09-04 12:27 UTC, romoore commented on components/TextFields/src/MDCTextInputControllerBase.m
> +		self.textInput.font = font;
From this change, it looks like there is a bug when setting the MDCTextField's `font` property. Could you please describe in the PR summary why the fix needs to be made here and not where the side-effect takes place?

2019-09-04 12:27 UTC, romoore commented on components/TextFields/src/MDCTextInputControllerBase.m
> +	UIFont *font = self.textInputFont;
Nit: Please correct the indentation for this method. It looks like it accidentally changed. It should be 2 spaces from the start of the line for method bodies.

2019-09-12 12:02 UTC, ggdiez commented on components/TextFields/src/MDCTextInputControllerBase.m
> +	UIFont *font = self.textInputFont;
Changed

2019-09-12 12:20 UTC, ggdiez commented on components/TextFields/src/MDCTextInputControllerBase.m
> +		self.textInput.font = font;
This PR is related with bug #8390 
The problem is not in the MCDTextField font is in the flotating placeholder text. 
When use start to type in MCDTextField flotating placeholder text change the size. 
It seems when in the controller the textInput font changes produces size changes in flotating placeholder. 
This code prevent changes in font except when font changes really.

2019-09-12 14:33 UTC, romoore commented on components/TextFields/src/MDCTextInputControllerBase.m
> +		self.textInput.font = font;
@ggdiez Can you see if https://github.com/material-components/material-components-ios/pull/8444 will resolve your issues?  I believe the `didSetFont` behavior was the root cause of the problem.

2019-09-13 06:09 UTC, ggdiez commented on components/TextFields/src/MDCTextInputControllerBase.m
> +		self.textInput.font = font;
Yes, I agree with you. I just test your code and works. I can not reproduce the issue.
Thank you.

2019-09-13 13:24 UTC, romoore commented on components/TextFields/src/MDCTextInputControllerBase.m
> +		self.textInput.font = font;
Awesome, thanks for confirming!

2019-09-13 13:24 UTC, romoore commented
Closing. I believe this will be obsoleted by #8444.

2019-09-13 13:24 UTC, closed without merging