[AppBar] Text accessibility color is not used for the title and back button
material-components/material-components-ios pull request #849
Opened 2016-11-09 23:44 UTC by ShepJGoogle

https://github.com/google/material-components-ios/issues/702

- Created a configurator class for MDCAppBar
- Implemented config method to update colors on MDCAppBar's title and bar button items

Design Doc: https://docs.google.com/a/google.com/document/d/1QHdBcW8pIkmJ796ou_W-wIznLXT_vzcxWwwlqSSN9x8/edit?usp=sharing

2016-11-11 18:59 UTC, ajsecord requested changes
Interesting! We have a similar issue for buttons, so I'd like to know more about the "configurator" approach. Can you please write more about it? If there are references to a known pattern, please include them, too. 
Thanks!

2016-11-14 21:46 UTC, randallli requested changes

2016-11-21 23:08 UTC, randallli requested changes

2016-11-23 14:18 UTC, ajsecord requested changes
I would still like to see a little one-page design doc for this. For example, does the class have a bunch of little methods, or one method per "target", what are they named, etc.

2017-03-03 17:12 UTC, closed without merging

2017-03-03 17:13 UTC, ShepJGoogle commented
Just noticed this was not updated when we switched to the new public repo. Closing this and re-opening new PR: https://github.com/material-components/material-components-ios/pull/1236