[Snackbar] Deprecate adjustsFontForContentSizeCategoryWhenScaledFontIsUnavailable
material-components/material-components-ios pull request #8728
Opened 2019-11-04 21:33 UTC by bryanoltman

Deprecates `adjustsFontForContentSizeCategoryWhenScaledFontIsUnavailable` in `MDCSnackbarMessageView` and `MDCSnackbarManager` and changes the default to `NO` in preparation for dynamic type support.

Part of #8648

2019-11-04 21:35 UTC, material-automation commented
bazel detected changes to the following targets:

```
//components/Snackbar:ColorThemer
//components/Snackbar:FontThemer
//components/Snackbar:ObjcExamples
//components/Snackbar:Snackbar
//components/Snackbar:TypographyThemer
//components/Snackbar:snapshot_test_lib
//components/Snackbar:snapshot_tests
//components/Snackbar:snapshot_tests.swift_runtime_linkopts
//components/Snackbar:snapshot_tests_test_binary
//components/Snackbar:snapshot_tests_test_bundle
//components/Snackbar:unit_test_sources
//components/Snackbar:unit_test_swift_sources
//components/Snackbar:unit_tests
//components/Snackbar:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/Snackbar:unit_tests_IPAD_PRO_12_9_IN_9_3.swift_runtime_linkopts
//components/Snackbar:unit_tests_IPAD_PRO_12_9_IN_9_3_test_binary
//components/Snackbar:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/Snackbar:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/Snackbar:unit_tests_IPHONE_7_PLUS_IN_10_3.swift_runtime_linkopts
//components/Snackbar:unit_tests_IPHONE_7_PLUS_IN_10_3_test_binary
//components/Snackbar:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/Snackbar:unit_tests_environment
//components/Snackbar:unit_tests_environment.swift_runtime_linkopts
//components/Snackbar:unit_tests_environment_test_binary
//components/Snackbar:unit_tests_environment_test_bundle
```

<!-- identifier: affected-targets -->

2019-11-04 21:41 UTC, material-automation commented
## API diff detected the following changes

### Snackbar

#### MDCSnackbarMessageView

*modified* property: `adjustsFontForContentSizeCategoryWhenScaledFontIsUnavailable` in `MDCSnackbarMessageView`

| Type of change: | Deprecation message |
|---|---|
| From: | `` |
| To: | `Use UIFontMetrics and UIContentSizeCategoryAdjusting on iOS 11+ or MDCFontScaler on earlier versions` |

*modified* property: `adjustsFontForContentSizeCategoryWhenScaledFontIsUnavailable` in `MDCSnackbarMessageView`

| Type of change: | Deprecation |
|---|---|
| From: | `0` |
| To: | `1` |

#### MDCSnackbarManager

*modified* property: `adjustsFontForContentSizeCategoryWhenScaledFontIsUnavailable` in `MDCSnackbarManager`

| Type of change: | Deprecation message |
|---|---|
| From: | `` |
| To: | `Use UIFontMetrics and UIContentSizeCategoryAdjusting on iOS 11+ or MDCFontScaler on earlier versions` |

*modified* property: `adjustsFontForContentSizeCategoryWhenScaledFontIsUnavailable` in `MDCSnackbarManager`

| Type of change: | Deprecation |
|---|---|
| From: | `0` |
| To: | `1` |

#### MDCSnackbarMessageView()

*new* category: `MDCSnackbarMessageView()`

*removed* category: `MDCSnackbarMessageView()`

*modified* property: `snackbarMessageViewTextColor` in `MDCSnackbarMessageView()`

| Type of change: | parent.usr |
|---|---|
| From: | `c:objc(ext)MDCSnackbarMessageView@MDCSnackbarMessageView.h@4574` |
| To: | `c:objc(ext)MDCSnackbarMessageView@MDCSnackbarMessageView.h@4637` |

<!-- identifier: apidiff -->

2019-11-05 02:44 UTC, romoore requested changes
Please leave the default as "YES" in this PR. Deprecation in a separate PR from the changed default is better. 

Before changing the default for the API, please update all *affected* internal instances to explicitly set to the current default value. ~We should also have at least one release where the default is announced as planning to change to "NO" in the future.~ Oops, I see it's already documented as "going to change."

2019-11-05 02:46 UTC, romoore commented
Also curious, how is this related to #8648? It seems like this code should not have an affect on UIFontMetrics support.  Could you please provide more detail about why it's blocking #8648?

2019-11-11 16:42 UTC, jverkoey approved these changes

2019-11-11 16:48 UTC, material-automation commented on components/Snackbar/tests/unit/MDCSnackbarMessageViewTests.m
> +    #pragma clang diagnostic ignored "-Wdeprecated-declarations"
clang-format suggested the following change:


```
-    #pragma clang diagnostic push
-    #pragma clang diagnostic ignored "-Wdeprecated-declarations"
+#pragma clang diagnostic push
+#pragma clang diagnostic ignored "-Wdeprecated-declarations"
```

<!-- identifier: clang-format -->
<!-- File: components/Snackbar/tests/unit/MDCSnackbarMessageViewTests.m -->

2019-11-11 16:48 UTC, material-automation commented on components/Snackbar/tests/unit/MDCSnackbarMessageViewTests.m
> +    #pragma clang diagnostic pop
clang-format suggested the following change:


```
-    #pragma clang diagnostic pop
+#pragma clang diagnostic pop
```

<!-- identifier: clang-format -->
<!-- File: components/Snackbar/tests/unit/MDCSnackbarMessageViewTests.m -->

2019-11-11 16:48 UTC, material-automation commented on components/Snackbar/tests/unit/MDCSnackbarMessageViewTests.m
> +    #pragma clang diagnostic ignored "-Wdeprecated-declarations"
clang-format suggested the following change:


```
-    #pragma clang diagnostic push
-    #pragma clang diagnostic ignored "-Wdeprecated-declarations"
+#pragma clang diagnostic push
+#pragma clang diagnostic ignored "-Wdeprecated-declarations"
```

<!-- identifier: clang-format -->
<!-- File: components/Snackbar/tests/unit/MDCSnackbarMessageViewTests.m -->

2019-11-11 16:48 UTC, material-automation commented on components/Snackbar/tests/unit/MDCSnackbarMessageViewTests.m
> +    #pragma clang diagnostic pop
clang-format suggested the following change:


```
-    #pragma clang diagnostic pop
+#pragma clang diagnostic pop
```

<!-- identifier: clang-format -->
<!-- File: components/Snackbar/tests/unit/MDCSnackbarMessageViewTests.m -->

2019-11-11 16:48 UTC, material-automation commented
clang-format recommended changes.

Consider installing [git-clang-format](https://github.com/llvm-mirror/clang/blob/master/tools/clang-format/git-clang-format) and running the following command:

```bash
git clang-format $(git merge-base origin/develop HEAD)
```

<!-- identifier: clang-format -->

2019-11-11 18:43 UTC, bryanoltman commented
@romoore Reverted the change to the default value

2019-11-11 19:19 UTC, romoore approved these changes

2019-11-11 19:21 UTC, merged