Using AccessiblityElements to group the subparts of the MDCMutlilineTextField
material-components/material-components-ios pull request #8988
Opened 2019-11-18 14:57 UTC by randallli

First pass at getting the accessibilty elements API working for MDCMultilineTextField so that the placeholder label is grouped with the textView

2019-11-18 14:59 UTC, material-automation commented on components/TextFields/src/MDCMultilineTextField.m
> +  multilineTextField.accessibilityElements = @[ multilineTextField.textView, multilineTextField.clearButton ];
clang-format suggested the following change:


```
-  multilineTextField.accessibilityElements = @[ multilineTextField.textView, multilineTextField.clearButton ];
+  multilineTextField.accessibilityElements =
+      @[ multilineTextField.textView, multilineTextField.clearButton ];
```

<!-- identifier: clang-format -->
<!-- File: components/TextFields/src/MDCMultilineTextField.m -->

2019-11-18 14:59 UTC, material-automation commented on components/TextFields/src/MDCMultilineTextField.m
>                                          : nil;
clang-format suggested the following change:


```
-  NSString *label = accessibilityStrings.count > 0 ? [accessibilityStrings componentsJoinedByString:@", "]
-                                        : nil;
+  NSString *label =
+      accessibilityStrings.count > 0 ? [accessibilityStrings componentsJoinedByString:@", "] : nil;
```

<!-- identifier: clang-format -->
<!-- File: components/TextFields/src/MDCMultilineTextField.m -->

2019-11-18 14:59 UTC, material-automation commented
clang-format recommended changes.

Consider installing [git-clang-format](https://github.com/llvm-mirror/clang/blob/master/tools/clang-format/git-clang-format) and running the following command:

```bash
git clang-format $(git merge-base origin/develop HEAD)
```

<!-- identifier: clang-format -->

2019-11-18 15:00 UTC, material-automation commented
bazel detected changes to the following targets:

```
//components/Chips:snapshot_tests
//components/Chips:snapshot_tests_test_bundle
//components/Chips:unit_tests
//components/Chips:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/Chips:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/Chips:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/Chips:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/Chips:unit_tests_environment
//components/Chips:unit_tests_environment_test_bundle
//components/TextFields:snapshot_tests
//components/TextFields:snapshot_tests_test_bundle
//components/TextFields:unit_tests
//components/TextFields:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/TextFields:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/TextFields:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/TextFields:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/TextFields:unit_tests_IPHONE_X_IN_11_0
//components/TextFields:unit_tests_IPHONE_X_IN_11_0_test_bundle
```

<!-- identifier: affected-targets -->

2019-11-18 15:04 UTC, randallli commented
One thing that I am not certain about is the required API call for client step set up the elements and labels of the component. I am worried that clients will forget to do so.

2019-11-18 15:06 UTC, material-automation commented
## API diff detected the following changes

### TextFields

#### MDCMultilineTextField

*new* class method: `+setupAccessibilityElements:` in `MDCMultilineTextField`

<!-- identifier: apidiff -->

2019-11-22 03:36 UTC, romoore requested changes
Please include either automated tests (hosted/unhosted) or manual testing steps for use with one of the example view controllers.

2020-01-17 14:31 UTC, jverkoey commented
Closing this PR due to inactivity, but please re-open it again if / when you intend to pursue it.

2020-02-07 14:37 UTC, closed without merging