Revert "[FeatureHighlight] Add a voiceover dismissal affordance for the feature highlight. (#8959)"
material-components/material-components-ios pull request #9015
Opened 2019-11-21 23:35 UTC by jverkoey

This reverts commit 4c7402857c173db101f846409ad716fac8ada4a3, which broke tests.

```
Test Suite 'Selected tests' started at 2019-11-21 18:34:10.629
Test Suite 'MaterialComponents-Unit-FeatureHighlight-UnitTests.xctest' started at 2019-11-21 18:34:10.630
Test Suite 'FeatureHighlightAccessibilityTests' started at 2019-11-21 18:34:10.630
Test Case '-[FeatureHighlightAccessibilityTests testAccessibilityHintDefaultAfterLoadingView]' started.
/Users/featherless/workbench/material-components-ios/components/FeatureHighlight/tests/unit/FeatureHighlightAccessibilityTests.m:45: error: -[FeatureHighlightAccessibilityTests testAccessibilityHintDefaultAfterLoadingView] : ((controller.accessibilityHint) != nil) failed
/Users/featherless/workbench/material-components-ios/components/FeatureHighlight/tests/unit/FeatureHighlightAccessibilityTests.m:46: error: -[FeatureHighlightAccessibilityTests testAccessibilityHintDefaultAfterLoadingView] : ((controller.view.accessibilityHint) != nil) failed
Test Case '-[FeatureHighlightAccessibilityTests testAccessibilityHintDefaultAfterLoadingView]' failed (0.044 seconds).
Test Case '-[FeatureHighlightAccessibilityTests testSetAccessibilityHint]' started.
Test Case '-[FeatureHighlightAccessibilityTests testSetAccessibilityHint]' passed (0.001 seconds).
Test Case '-[FeatureHighlightAccessibilityTests testSetAccessibilityHintNil]' started.
Test Case '-[FeatureHighlightAccessibilityTests testSetAccessibilityHintNil]' passed (0.001 seconds).
Test Suite 'FeatureHighlightAccessibilityTests' failed at 2019-11-21 18:34:10.677.
	 Executed 3 tests, with 2 failures (0 unexpected) in 0.046 (0.047) seconds
Test Suite 'MaterialComponents-Unit-FeatureHighlight-UnitTests.xctest' failed at 2019-11-21 18:34:10.677.
	 Executed 3 tests, with 2 failures (0 unexpected) in 0.046 (0.048) seconds
Test Suite 'Selected tests' failed at 2019-11-21 18:34:10.678.
	 Executed 3 tests, with 2 failures (0 unexpected) in 0.046 (0.049) seconds
Program ended with exit code: 1
```

2019-11-21 23:38 UTC, material-automation commented
bazel detected changes to the following targets:

```
//components/FeatureHighlight:ColorThemer
//components/FeatureHighlight:FeatureHighlight
//components/FeatureHighlight:FeatureHighlightAccessibilityMutator
//components/FeatureHighlight:FontThemer
//components/FeatureHighlight:ObjcExamples
//components/FeatureHighlight:SwiftExamples
//components/FeatureHighlight:TypographyThemer
//components/FeatureHighlight:snapshot_test_lib
//components/FeatureHighlight:snapshot_tests
//components/FeatureHighlight:snapshot_tests.swift_runtime_linkopts
//components/FeatureHighlight:snapshot_tests_test_binary
//components/FeatureHighlight:snapshot_tests_test_bundle
//components/FeatureHighlight:unit_test_sources
//components/FeatureHighlight:unit_tests
//components/FeatureHighlight:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/FeatureHighlight:unit_tests_IPAD_PRO_12_9_IN_9_3.swift_runtime_linkopts
//components/FeatureHighlight:unit_tests_IPAD_PRO_12_9_IN_9_3_test_binary
//components/FeatureHighlight:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/FeatureHighlight:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/FeatureHighlight:unit_tests_IPHONE_7_PLUS_IN_10_3.swift_runtime_linkopts
//components/FeatureHighlight:unit_tests_IPHONE_7_PLUS_IN_10_3_test_binary
//components/FeatureHighlight:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/FeatureHighlight:unit_tests_environment
//components/FeatureHighlight:unit_tests_environment.swift_runtime_linkopts
//components/FeatureHighlight:unit_tests_environment_test_binary
//components/FeatureHighlight:unit_tests_environment_test_bundle
```

<!-- identifier: affected-targets -->

2019-11-22 02:28 UTC, romoore commented
#3644 expected to make the default value "nil". Is there some reason we don't want to move forward with that issue?

2019-11-22 02:31 UTC, romoore requested changes
Since this is only breaking project tests and the change generally improved the component's accessibility, I don't think it should be reverted.  The hint was inaccurate and misleading unless clients attached a gesture recognizer to handle dismissal. We also have #3644 in our backlog to remove the default at some point.

If you feel the inaccurate hint should be restored as a default value (I don't believe it should), then I think that would be a better solution than this roll-back.

2019-11-22 12:33 UTC, jverkoey commented
Superseded by https://github.com/material-components/material-components-ios/pull/9018

2019-11-22 12:33 UTC, closed without merging