[Banner] fix height when no action button shows.
material-components/material-components-ios pull request #9218
Opened 2019-12-09 23:22 UTC by wenyuzhang666

closes https://github.com/material-components/material-components-ios/issues/9217.

`leadingButton`'s height shouldn't be taken into consideration when it is hidden.

2019-12-09 23:25 UTC, material-automation commented
bazel detected changes to the following targets:

```
//components/Banner:snapshot_tests
//components/Banner:snapshot_tests_test_bundle
//components/Banner:unit_tests
//components/Banner:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/Banner:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/Banner:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/Banner:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/Banner:unit_tests_environment
//components/Banner:unit_tests_environment_test_bundle
```

<!-- identifier: affected-targets -->

2019-12-10 13:37 UTC, romoore requested changes
Please add a test to reproduce the bug and verify the fix. A snapshot test merged before this PR would be ideal so the effect is visually apparent.

2019-12-10 17:36 UTC, wenyuzhang666 commented
> Please add a test to reproduce the bug and verify the fix. A snapshot test merged before this PR would be ideal so the effect is visually apparent.

The snapshot changed in this PR includes the original wrong bug.

2019-12-10 19:38 UTC, romoore approved these changes

2019-12-10 19:39 UTC, romoore commented
Sorry, I must have not seen the image or something in my initial review. :(

2019-12-10 19:41 UTC, wenyuzhang666 commented
Thanks for the review!

2019-12-10 19:41 UTC, merged