[NavigationDrawer] Implemented opt-in default empty header.
material-components/material-components-ios pull request #9436
Opened 2020-01-16 15:09 UTC by jakerockland

This PR adds to the MDCBottomDrawerViewController the ability to specify that a default header be used, which prevents the bottom drawer content from conflicting with status bar when a header has not been provided, closing #6434.

This behavior is entirely opt-in as currently implemented, and saves clients from having to each create their own implementation of a similar empty `headerViewController` (which is what we are currently having to do to work around b/123186711).

I wanted to verify whether or not this is fix is something that may be an acceptable fix for #6434 before adding tests, but if it is, I was planning to adding the following tests (and am open to adding additional suggested tests if it seems necessary):

1. Test that verifies `preferredContentSize` height of the `headerViewController` matches that of the collapsed state corner radius, regardless of the order in which `setEmptyHeaderWithBackgroundColor:` and `setCornerRadius:` are called.
2. Test that verifies that the backgroundColor specified when calling `setEmptyHeaderWithBackgroundColor:` matches the backgroundColor of the header both once it is presented and also before presentation if its view is accessed (causing `viewDidLoad:` to fire).

I've also already manually verified that this fix works as a drop-in replacement for our team's existing workaround, and have added a screencast on the internal issue for this ticket b/123186711.

2020-01-17 14:30 UTC, jakerockland commented
An additional thought on this, we may want to parameterize the `preferredContentSize` height of the `headerViewController` matching the `topCornerRadius` making this part of the API for using the empty header. Possibly something along the lines of:

```
setEmptyHeaderWithBackgroundColor:(UIColor *)backgroundColor
           trackingTopCornerRadiusHeight:(BOOL)trackingTopCornerRadiusHeight;
```

2020-01-19 09:46 UTC, yarneo requested changes
Hey @jakerockland,

Thanks for opening the PR! This is a valid workaround for your team to do, as the component currently doesn't provide a good API of achieving this feature. 

However, this being a workaround, I believe if we want to land component code here we should try to find how we can add an opt-in flag in the MDCBottomDrawer API that will allow the drawer without a header to have a "sticky top" so the content won't scroll behind the status bar. This should ideally be achieved by altering the implementation code rather than adding a "empty header" view controller so to imitate the drawer with header code.

Happy to speak offline if you want to discuss this further!

2020-01-19 15:21 UTC, jakerockland commented
Hey yarneo@,

Thanks so much for taking a look at this!

I definitely understand that outlook and will find some time next week to do more poking around at how that aspect of this component works, to see if I can I find a better fix along those lines.

May ping you next week offline to chat more!
On Jan 19, 2020, 2:46 AM -0700, Yarden Eitan , wrote:
> @yarneo requested changes on this pull request.
> Hey @jakerockland,
> Thanks for opening the PR! This is a valid workaround for your team to do, as the component currently doesn't provide a good API of achieving this feature.
> However, this being a workaround, I believe if we want to land component code here we should try to find how we can add an opt-in flag in the MDCBottomDrawer API that will allow the drawer without a header to have a "sticky top" so the content won't scroll behind the status bar. This should ideally be achieved by altering the implementation code rather than adding a "empty header" view controller so to imitate the drawer with header code.
> Happy to speak offline if you want to discuss this further!
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2020-01-21 09:36 UTC, yarneo commented
Sounds great! Thanks @jakerockland . Closing this PR for now, feel free to re-open when it is ready

2020-01-21 09:36 UTC, closed without merging

2020-01-21 14:28 UTC, jakerockland commented
SGTM, thanks Yarden!

Jake Rockland
Software Developer // Product Oriented // Generalist
jakerockland.com
On Jan 21, 2020, 2:36 AM -0700, Yarden Eitan <notifications@github.com>, wrote:
> Closed #9436.
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.