Adding a snapshot test to verify correct layout of actions in edge cases found in issue: #8434.
material-components/material-components-ios pull request #9875
Opened 2020-03-10 19:30 UTC by galiak11

Adding a snapshot test to verify correct layout of actions in edge cases found in issue: #8434.

b/137070719, cl/299739784

2020-03-10 19:41 UTC, material-automation commented on components/Dialogs/tests/snapshot/MDCAlertControllerActionsTests.m
> +      addAction:[MDCAlertAction actionWithTitle:@"OK" emphasis:emphasis handler:nil]];
clang-format suggested the following change:


```
-  [self.alertController
-      addAction:[MDCAlertAction actionWithTitle:@"OK" emphasis:emphasis handler:nil]];
+  [self.alertController addAction:[MDCAlertAction actionWithTitle:@"OK"
+                                                         emphasis:emphasis
+                                                          handler:nil]];
```

<!-- identifier: clang-format -->
<!-- File: components/Dialogs/tests/snapshot/MDCAlertControllerActionsTests.m -->

2020-03-10 19:41 UTC, material-automation commented on components/Dialogs/tests/snapshot/MDCAlertControllerActionsTests.m
> +      addAction:[MDCAlertAction actionWithTitle:@"Cancel" emphasis:emphasis handler:nil]];
clang-format suggested the following change:


```
-  [self.alertController
-      addAction:[MDCAlertAction actionWithTitle:@"Cancel" emphasis:emphasis handler:nil]];
+  [self.alertController addAction:[MDCAlertAction actionWithTitle:@"Cancel"
+                                                         emphasis:emphasis
+                                                          handler:nil]];
```

<!-- identifier: clang-format -->
<!-- File: components/Dialogs/tests/snapshot/MDCAlertControllerActionsTests.m -->

2020-03-10 19:41 UTC, material-automation commented on components/Dialogs/tests/snapshot/MDCAlertControllerActionsTests.m
> +      addAction:[MDCAlertAction actionWithTitle:action emphasis:MDCActionEmphasisLow handler:nil]];
clang-format suggested the following change:


```
-  [self.alertController
-      addAction:[MDCAlertAction actionWithTitle:action emphasis:MDCActionEmphasisLow handler:nil]];
+  [self.alertController addAction:[MDCAlertAction actionWithTitle:action
+                                                         emphasis:MDCActionEmphasisLow
+                                                          handler:nil]];
```

<!-- identifier: clang-format -->
<!-- File: components/Dialogs/tests/snapshot/MDCAlertControllerActionsTests.m -->

2020-03-10 19:41 UTC, material-automation commented
clang-format recommended changes.

Consider installing [git-clang-format](https://github.com/llvm-mirror/clang/blob/master/tools/clang-format/git-clang-format) and running the following command:

```bash
git clang-format $(git merge-base origin/develop HEAD)
```

<!-- identifier: clang-format -->

2020-03-10 19:42 UTC, material-automation commented
bazel detected changes to the following targets:

```
//components/Dialogs:snapshot_test_lib
//components/Dialogs:snapshot_tests
//components/Dialogs:snapshot_tests.swift_runtime_linkopts
//components/Dialogs:snapshot_tests_test_binary
//components/Dialogs:snapshot_tests_test_bundle
```

<!-- identifier: affected-targets -->

2020-03-11 13:00 UTC, material-automation commented on components/Dialogs/tests/snapshot/MDCAlertControllerActionsTests.m
> +    self.recordMode = YES;
clang-format suggested the following change:


```
-    self.recordMode = YES;
+  self.recordMode = YES;
```

<!-- identifier: clang-format -->
<!-- File: components/Dialogs/tests/snapshot/MDCAlertControllerActionsTests.m -->

2020-03-11 13:00 UTC, material-automation commented
clang-format recommended changes.

Consider installing [git-clang-format](https://github.com/llvm-mirror/clang/blob/master/tools/clang-format/git-clang-format) and running the following command:

```bash
git clang-format $(git merge-base origin/develop HEAD)
```

<!-- identifier: clang-format -->

2020-03-11 15:07 UTC, jverkoey requested changes

2020-03-11 15:07 UTC, jverkoey commented on components/Dialogs/tests/snapshot/MDCAlertControllerActionsTests.m
> +
Please pull the refactoring out to a separate PR and then land the new snapshot test independently.

2020-03-12 12:38 UTC, jverkoey commented
To confirm: this new snapshot test is supposed to be revealing a layout bug?

2020-03-12 12:42 UTC, jverkoey commented
If so, please update the PR description accordingly.

2020-03-12 13:21 UTC, galiak11 commented
It reveals 2 layout bugs - added the info in the description.

2020-03-12 13:34 UTC, jverkoey commented
Please remove the other PR description snippets from this PR description; it reads like this PR is fixing the Issues presented. Please focus instead on explaining what Issues this PR is revealing.

2020-03-12 20:10 UTC, galiak11 commented
Please review fixed decsription.

2020-03-12 20:13 UTC, jverkoey approved these changes

2020-03-12 21:57 UTC, merged