[Dialogs] Fix vertical calculations for wide actions view
material-components/material-components-ios pull request #9878
Opened 2020-03-11 04:45 UTC by galiak11

[Dialogs] Fix vertical calculations for wide actions view

This issue is specific to alerts with actions that are wider than the title and the message. The width of the alert, which is based on it's widest part (in this case the actions) did not include the insets in the width, causing differences in calculating the final width of the alerts, and cause long actions to be truncated.

b/137070719, cl/299735845

2020-03-11 04:59 UTC, material-automation commented
bazel detected changes to the following targets:

```
//components/Dialogs:snapshot_tests
//components/Dialogs:snapshot_tests_test_bundle
//components/Dialogs:unit_tests
//components/Dialogs:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/Dialogs:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/Dialogs:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/Dialogs:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/Dialogs:unit_tests_environment
//components/Dialogs:unit_tests_environment_test_bundle
```

<!-- identifier: affected-targets -->

2020-03-11 12:17 UTC, jverkoey reviewed
Similarly here, please either add a unit or snapshot test (preferably), or add an example that demonstrates the incorrect behavior.

2020-03-11 13:52 UTC, galiak11 commented
The snapshot test is added in: https://github.com/material-components/material-components-ios/pull/9875.

2020-03-11 15:08 UTC, jverkoey requested changes
Marking changes requested until this PR demonstrates that a snapshot test is affected.

2020-03-15 13:47 UTC, galiak11 commented
Affected snapshot test was added.

2020-03-15 13:58 UTC, jverkoey commented
Please update the PR description to refer to the specific GitHub Issue it is closing.

2020-03-15 15:37 UTC, yarneo approved these changes
Galia, I added which github issue this helps resolve, please verify that this is correct before merging

2020-03-15 16:09 UTC, galiak11 commented
That is the correct issue.

2020-03-15 16:40 UTC, jverkoey approved these changes

2020-03-15 18:46 UTC, merged