[bottomsheet] fix to allow dismissOnDraggingDownSheet to be set
material-components/material-components-ios pull request #9885
Opened 2020-03-11 21:58 UTC by randallli

sourced from internal bug:
When using a MDCBottomSheetTransitionController with a custom view controller, setting its dismissOnDraggingDownSheet to false has no effect.

The reason seems to be that MDCBottomSheetPresentationController always sets _dismissOnDraggingDownSheet = YES in |presentationTransitionWillBegin|, before creating the sheetView.

_dismissOnDraggingDownSheet = YES should be moved to the initializer, allowing the value to be overridden before the transition begins

https://github.com/material-components/material-components-ios/issues/9723

2020-03-11 21:58 UTC, randallli reviewed
I need to revert the clang formater change.

2020-03-11 22:01 UTC, material-automation commented
bazel detected changes to the following targets:

```
//catalog:MDCCatalog
//catalog:MDCCatalog.apple_binary
//catalog:MDCCatalog.swift_runtime_linkopts
//catalog:MDCCatalogLib
//components/ActionSheet:ActionSheet
//components/ActionSheet:ActionSheetThemer
//components/ActionSheet:ColorThemer
//components/ActionSheet:ObjcExamples
//components/ActionSheet:SwiftExamples
//components/ActionSheet:Theming
//components/ActionSheet:TypographyThemer
//components/ActionSheet:privateHeaders
//components/ActionSheet:snapshot_test_lib
//components/ActionSheet:snapshot_tests
//components/ActionSheet:snapshot_tests.swift_runtime_linkopts
//components/ActionSheet:snapshot_tests_test_binary
//components/ActionSheet:snapshot_tests_test_bundle
//components/ActionSheet:unit_test_sources
//components/ActionSheet:unit_test_swift_sources
//components/ActionSheet:unit_tests
//components/ActionSheet:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/ActionSheet:unit_tests_IPAD_PRO_12_9_IN_9_3.swift_runtime_linkopts
//components/ActionSheet:unit_tests_IPAD_PRO_12_9_IN_9_3_test_binary
//components/ActionSheet:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/ActionSheet:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/ActionSheet:unit_tests_IPHONE_7_PLUS_IN_10_3.swift_runtime_linkopts
//components/ActionSheet:unit_tests_IPHONE_7_PLUS_IN_10_3_test_binary
//components/ActionSheet:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/ActionSheet:unit_tests_IPHONE_X_IN_11_0
//components/ActionSheet:unit_tests_IPHONE_X_IN_11_0.swift_runtime_linkopts
//components/ActionSheet:unit_tests_IPHONE_X_IN_11_0_test_binary
//components/ActionSheet:unit_tests_IPHONE_X_IN_11_0_test_bundle
//components/BottomSheet:BottomSheet
//components/BottomSheet:ObjcExamples
//components/BottomSheet:ShapeThemer
//components/BottomSheet:SwiftExamples
//components/BottomSheet:privateHeaders
//components/BottomSheet:snapshot_test_lib
//components/BottomSheet:snapshot_tests
//components/BottomSheet:snapshot_tests.swift_runtime_linkopts
//components/BottomSheet:snapshot_tests_test_binary
//components/BottomSheet:snapshot_tests_test_bundle
//components/BottomSheet:unit_test_sources
//components/BottomSheet:unit_test_swift_sources
//components/BottomSheet:unit_tests
//components/BottomSheet:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/BottomSheet:unit_tests_IPAD_PRO_12_9_IN_9_3.swift_runtime_linkopts
//components/BottomSheet:unit_tests_IPAD_PRO_12_9_IN_9_3_test_binary
//components/BottomSheet:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/BottomSheet:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/BottomSheet:unit_tests_IPHONE_7_PLUS_IN_10_3.swift_runtime_linkopts
//components/BottomSheet:unit_tests_IPHONE_7_PLUS_IN_10_3_test_binary
//components/BottomSheet:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/BottomSheet:unit_tests_environment
//components/BottomSheet:unit_tests_environment.swift_runtime_linkopts
//components/BottomSheet:unit_tests_environment_test_binary
//components/BottomSheet:unit_tests_environment_test_bundle
//components/Tabs:ObjcExamples
//components/schemes/Shape:ObjcExamples
```

<!-- identifier: affected-targets -->

2020-03-12 17:37 UTC, jverkoey reviewed
Please add a unit test for this.

2020-03-12 17:37 UTC, jverkoey requested changes
Requesting changes.

2020-03-12 18:08 UTC, randallli commented
> Please add a unit test for this.
Interaction tests are hard to unit test
I have added an example that manually tests this use case. 

I took a video of it in action:
[BottomSheet DismissOnDraggingDown.mov.zip](https://github.com/material-components/material-components-ios/files/4325758/BottomSheet.DismissOnDraggingDown.mov.zip)

2020-03-12 18:12 UTC, jverkoey requested changes
> I took a video of it in action:

I believe you that the bug exists. Please write a unit test for it though.

2020-03-12 18:17 UTC, material-automation commented on components/BottomSheet/src/private/MDCSheetContainerView.m
> +  MDCSheetState sheetStateClosable = self.dismissOnDraggingDownSheet ? MDCSheetStateClosed : MDCSheetStatePreferred;
clang-format suggested the following change:


```
-  MDCSheetState sheetStateClosable = self.dismissOnDraggingDownSheet ? MDCSheetStateClosed : MDCSheetStatePreferred;
+  MDCSheetState sheetStateClosable =
+      self.dismissOnDraggingDownSheet ? MDCSheetStateClosed : MDCSheetStatePreferred;
```

<!-- identifier: clang-format -->
<!-- File: components/BottomSheet/src/private/MDCSheetContainerView.m -->

2020-03-12 18:17 UTC, material-automation commented
clang-format recommended changes.

Consider installing [git-clang-format](https://github.com/llvm-mirror/clang/blob/master/tools/clang-format/git-clang-format) and running the following command:

```bash
git clang-format $(git merge-base origin/develop HEAD)
```

<!-- identifier: clang-format -->

2020-03-12 18:22 UTC, jverkoey requested changes
Re-requesting changes for unit test.

2020-03-12 18:42 UTC, material-automation commented on components/BottomSheet/examples/BottomSheetDismissOnDraggingDownExample.m
> +  // The line below is the purpose of this example and is the only delta between this example and the BottomSheetTypicalUseExample.m
clang-format suggested the following change:


```
-  // The line below is the purpose of this example and is the only delta between this example and the BottomSheetTypicalUseExample.m
+  // The line below is the purpose of this example and is the only delta between this example and
+  // the BottomSheetTypicalUseExample.m
```

<!-- identifier: clang-format -->
<!-- File: components/BottomSheet/examples/BottomSheetDismissOnDraggingDownExample.m -->

2020-03-12 18:42 UTC, material-automation commented
clang-format recommended changes.

Consider installing [git-clang-format](https://github.com/llvm-mirror/clang/blob/master/tools/clang-format/git-clang-format) and running the following command:

```bash
git clang-format $(git merge-base origin/develop HEAD)
```

<!-- identifier: clang-format -->

2020-04-09 20:08 UTC, closed without merging

2020-04-09 20:08 UTC, jverkoey commented
Moving this PR to [cl/305744911](http://cl/305744911).