[Dialogs] Publish customization API
material-components/material-components-ios pull request #9893
Opened 2020-03-13 09:38 UTC by galiak11

# Description
Publishing the dialogs' `titleIconView` API.

## Issues
Fixes: #9869
b/150085275

2020-03-13 09:41 UTC, material-automation commented
bazel detected changes to the following targets:

```
//catalog:MDCCatalog
//catalog:MDCCatalog.apple_binary
//catalog:MDCCatalog.swift_runtime_linkopts
//catalog:MDCCatalogLib
//components/Dialogs:ColorThemer
//components/Dialogs:DialogThemer
//components/Dialogs:Dialogs
//components/Dialogs:ObjcExamples
//components/Dialogs:SwiftExamples
//components/Dialogs:Theming
//components/Dialogs:TypographyThemer
//components/Dialogs:snapshot_test_lib
//components/Dialogs:snapshot_tests
//components/Dialogs:snapshot_tests.swift_runtime_linkopts
//components/Dialogs:snapshot_tests_test_binary
//components/Dialogs:snapshot_tests_test_bundle
//components/Dialogs:unit_test_sources
//components/Dialogs:unit_test_swift_sources
//components/Dialogs:unit_tests
//components/Dialogs:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/Dialogs:unit_tests_IPAD_PRO_12_9_IN_9_3.swift_runtime_linkopts
//components/Dialogs:unit_tests_IPAD_PRO_12_9_IN_9_3_test_binary
//components/Dialogs:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/Dialogs:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/Dialogs:unit_tests_IPHONE_7_PLUS_IN_10_3.swift_runtime_linkopts
//components/Dialogs:unit_tests_IPHONE_7_PLUS_IN_10_3_test_binary
//components/Dialogs:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/Dialogs:unit_tests_environment
//components/Dialogs:unit_tests_environment.swift_runtime_linkopts
//components/Dialogs:unit_tests_environment_test_binary
//components/Dialogs:unit_tests_environment_test_bundle
```

<!-- identifier: affected-targets -->

2020-03-13 12:44 UTC, jverkoey requested changes

2020-03-13 12:44 UTC, jverkoey commented on components/Dialogs/src/MDCAlertController+Customize.h
> + The Customize extensions privde APIs that extend the default Material Dialog. Make sure to adjust
provide*

2020-03-13 12:44 UTC, jverkoey commented on components/Dialogs/src/MDCAlertController+Customize.h
> + your custom theming when using these APIs, if you are concerned with conforming to the Material
What does "Make sure to adjust your custom theming" mean in this context? If we're not able to explain in this context, can we link the reader to some additional documentation?

2020-03-13 12:44 UTC, jverkoey commented on components/Dialogs/src/MDCAlertController+Customize.h
> + implementations of the view above the title.
The ", enabling custom implementations of the view above the title." part is implied and can be removed.

2020-03-13 12:44 UTC, jverkoey commented on components/Dialogs/src/MDCAlertController+Customize.h
> + implementations. If both `titleIcon` are `titleIconView` are set, 'titleIconView' is ignored.
> If both `titleIcon` are `titleIconView` are set, 'titleIconView' is ignored.

This behavior is surprising. E.g. with navigationItem, if you provide both a title and a titleView, titleView takes precedent (https://developer.apple.com/documentation/uikit/uinavigationitem/1624935-titleview?language=objc). Please align with UIKit's behavior in this case and make titleIconView take precedence in a PR prior to landing this one.

2020-03-30 18:48 UTC, galiak11 commented
Closing because this was implemented in "cl/303284455 - [Dialogs] Publish Customize API".

2020-03-30 18:48 UTC, closed without merging