[Dialogs] fix vertical actions snapshot test.
material-components/material-components-ios pull request #9896
Opened 2020-03-13 21:09 UTC by galiak11

# Problem
The current snapshot is inaccurate because there is not enough room to layout all the dialog's elements, so spaces between the elements are inaccurate.

# Solution
Using `calculatePreferredContentSizeForBounds:` to let the dialog determine the height needed to display the dialog.

2020-03-13 21:11 UTC, material-automation commented
bazel detected changes to the following targets:

```
//components/Dialogs:snapshot_test_lib
//components/Dialogs:snapshot_tests
//components/Dialogs:snapshot_tests.swift_runtime_linkopts
//components/Dialogs:snapshot_tests_test_binary
//components/Dialogs:snapshot_tests_test_bundle
```

<!-- identifier: affected-targets -->

2020-03-15 13:28 UTC, jverkoey requested changes

2020-03-15 13:28 UTC, jverkoey commented on components/Dialogs/tests/snapshot/MDCAlertControllerActionsTests.m
> +  self.alertController.view.bounds = CGRectMake(0.f, 0.f, bounds.size.width, bounds.size.height);
Is this logic typically what a client would need to do to get the correct sizing behavior? If not, can we adjust this to look more like the expected pattern of use?

2020-03-15 13:28 UTC, jverkoey commented on components/Dialogs/tests/snapshot/MDCAlertControllerActionsTests.m
> +  [self generateSnapshotAndVerifyForView:self.alertController.view];
This line is duplicated; please delete.

2020-03-30 18:52 UTC, galiak11 commented
Closing because this was implemented in: "PR #9918 - [Dialogs] Fix layout of actions snapshot test."

2020-03-30 18:52 UTC, closed without merging