[Dialogs] Calculate title Insets independently of content insets
material-components/material-components-ios pull request #9900
Opened 2020-03-15 03:30 UTC by galiak11

# Description

Insets calculations of the title and content panes in dialogs were using the same insets values, causing various misalignments.  This is fixed by ensuring that title calculations are using the titleInsets and that content calculations (of message or accessory view) are using the content insets.

## Examples misalignments

* Title Label is stretching too long:
titletInsets = UIEdgeInsetsMake(24.f, 24.f, 24.f, 24.f);
contentInsets = UIEdgeInsetsMake(10.f, 10.f, 10.f, 10.f);
![image](https://user-images.githubusercontent.com/2329102/76694455-6a487280-6649-11ea-96e9-5eca7f37b86d.png)

* The title label is too short:
titleInsets = UIEdgeInsetsMake(12.f, 12.f, 12.f, 12.f);
![image](https://user-images.githubusercontent.com/2329102/76694524-391c7200-664a-11ea-9f81-47389711af7f.png)

* This dialog with no message has a message pane (yellow):
![image](https://user-images.githubusercontent.com/2329102/76694587-f4dda180-664a-11ea-979f-ecc45b28966e.png)

* This dialog with no title has a title pane (pink):
![image](https://user-images.githubusercontent.com/2329102/76694595-12127000-664b-11ea-8d22-9d954ad7570b.png)

## Issues
Closes #6289
b/122654717

2020-03-15 03:33 UTC, material-automation commented
bazel detected changes to the following targets:

```
//components/Dialogs:snapshot_tests
//components/Dialogs:snapshot_tests_test_bundle
//components/Dialogs:unit_tests
//components/Dialogs:unit_tests_IPAD_PRO_12_9_IN_9_3
//components/Dialogs:unit_tests_IPAD_PRO_12_9_IN_9_3_test_bundle
//components/Dialogs:unit_tests_IPHONE_7_PLUS_IN_10_3
//components/Dialogs:unit_tests_IPHONE_7_PLUS_IN_10_3_test_bundle
//components/Dialogs:unit_tests_environment
//components/Dialogs:unit_tests_environment_test_bundle
```

<!-- identifier: affected-targets -->

2020-03-16 00:57 UTC, jverkoey requested changes
There is a lot going on in this PR. Please break it up into smaller pieces, focusing on refactorings first and then landing behavioral fixes.

2020-03-16 00:57 UTC, jverkoey commented on components/Dialogs/src/private/MDCAlertControllerView+Private.m
> +/// @returns the space between the title and the title icon, or 0 if any of them is missing.
Please use `//` notation (not `///`) for .m documentation.

2020-03-16 06:30 UTC, material-automation commented on components/Dialogs/src/private/MDCAlertControllerView+Private.m
> +  CGFloat titleWidth = MAX([self.titleLabel sizeThatFits:boundsSize].width, [self titleIconViewSize].width);
clang-format suggested the following change:


```
-  CGFloat titleWidth = MAX([self.titleLabel sizeThatFits:boundsSize].width, [self titleIconViewSize].width);
+  CGFloat titleWidth =
+      MAX([self.titleLabel sizeThatFits:boundsSize].width, [self titleIconViewSize].width);
```

<!-- identifier: clang-format -->
<!-- File: components/Dialogs/src/private/MDCAlertControllerView+Private.m -->

2020-03-16 06:31 UTC, material-automation commented
clang-format recommended changes.

Consider installing [git-clang-format](https://github.com/llvm-mirror/clang/blob/master/tools/clang-format/git-clang-format) and running the following command:

```bash
git clang-format $(git merge-base origin/develop HEAD)
```

<!-- identifier: clang-format -->

2020-03-30 18:43 UTC, galiak11 commented
Closing because this is implemented in PR  #9919: [Dialogs] Calculate title Insets independently of content insets

2020-03-30 18:43 UTC, closed without merging